books/system/cantor-pairing-bijective.lisp

Filled a gap pointed out by Grant Passmore in the proof of surjectivity of cantor-pairing.

Show cantor-pairing-inverse returns nats

---

books/tau/bounders/elementary-bounders.lisp

Tau-bounders are usually called by tau-system, but my project calls them directly.
So I wrote guards for bounders in tau/bounders/elementary-bounders.lisp.

Add guards to tau/bounders/elementary-bounders.lisp

---

books/system/doc/render-doc.lisp

Not sure whether to leave the "[etc]" or make it a "..." like I've seen in most such examples, but there you have it.

Fix formatting in E/D doc topic

---

books/centaur/fty/fixtype.lisp

I found three "hidden" keyword arguments to `deffixtype`, so I wrote a few sentences about them in the doc topic. Of course, I just wrote whatever I could understand from looking at the code, so please let me know if I wrote something wrong that needs to be corrected.

Document some undocumented `deffixtype' arguments

---

books/nonstd/nsa/overspill-test.lisp
books/nonstd/nsa/overspill.lisp

In agreement with Matt Kaufmann, added the updated OVERSPILL macro to the
end of books/nonstd/nsa/overspill.lisp. The use of this macro is illustrated in
books/nonstd/nsa/overspill-test.lisp.

Added the updated OVERSPILL macro to the end of books/nonstd/nsa/overspill.lisp.

---

books/centaur/sv/cosims/Makefile

Hi @solswords @jaredcdavis  ,
Here's a pull request for making the cosim Makefile more generic and basing it off the default CCL settings.  Could you please merge this when you have a moment to update your scripts that call cosim and have them pass in IMG_EXT=ccl ?
-- Andrew and David

Configurable ACL2 path and image extension in SV cosims

---

books/rtl/rel11/support/basic.lisp

Replace `rationalp` by `real/rationalp` in hyps.
Refine rules `rtl::mod-rationalp` and `rtl::mod-realp` to match
arithmetic-5 rules `acl2::mod-rationalp` and `acl2::mod-realp`.

rtl/rel11/basic.lisp in ACL2(r)

---

books/acl2s/defdata/base.lisp
books/acl2s/defdata/defdata-attach.lisp
books/acl2s/defdata/defdata-core.lisp
books/acl2s/defdata/defdata-util.lisp
books/acl2s/defdata/random-state.lisp
books/acl2s/defdata/register-type.lisp
books/acl2s/defdata/top.lisp
books/acl2s/defdata/var-book.lisp

'make acl2s basic' passed, but did not build manual.

Enumerators are truely attachable using defdata-attach.

---

books/rtl/rel11/lib/doc.lisp
books/rtl/rel11/lib/excps.lisp
books/rtl/rel11/lib/masc.lisp
books/rtl/rel11/lib/reps.lisp

Synchronize `doc.lisp` with current online manual.
Uncomment `defsection-rtl` in `reps.lisp` .
Insert naive `defsection-rtl` into `excps.lisp` and `masc.lisp` .

Update linkes from RTL section of ACL2 manual to online RTL manual

---

books/centaur/fty/visitor.lisp

This file had the VL header instead of the FTY header, for some reason. cc/@solswords

Fix header in books/centaur/fty/visitor.lisp

---

books/build/make_cert_help.pl
books/centaur/bitops/fast-rotate.lisp
books/projects/x86isa/machine/instructions-spec/sal-sar-shl-shr-rcl-rcr-rol-ror.lisp

Removed dependency on arithmetic-5 for centaur/bitops/fast-rotate.lisp. Also pushing in Jared's edits to build/make_cert_help.pl to support extracting PBS directives from .acl2 files.

Updates to centaur/bitops/fast-rotate and build/make_cert_help.pl

---

books/centaur/sv/svtv/process.lisp

@solswords Can you please confirm that this was indeed a typo and merge?  It looks to me like `:boolvars` is the right argument to `svtv-run`, not `:boolmasks`, and I'm guessing this documentation just got outdated as you cleaned up the interface.

Fixing a typo

---

books/clause-processors/decomp-hint.lisp

The function needs to accept `state` rather than `world`.  This function
is not actually used anywhere in the books so it seems this bug was
overlooked.
cc @solswords for confirmation

Fix bug in STRUCTURAL-DECOMP-HINT-CAREFUL

---

books/centaur/gl/gl.lisp
books/centaur/gl/gobject-types.lisp

This is so that we can use g-int without having to load the whole GL
library, which takes a long time.

Move g-int to gobject-types.lisp

---

books/demos/tutorial-problems/equivalence-of-two-functions/kaufmann.lisp

Remove `(include-book "arithmetic/top-with-meta" :dir :system)` from `demos/tutorial-problems/equivalence-of-two-functions/kaufmann.lisp`.

ACL2 can certify now one of the demos without including "arithmetic"

---

books/centaur/sv/vl/top.lisp

@solswords or @jaredcdavis Can you please merge as appropriate?
I haven't built the entire regression yet (just the books that I've modified), because it'll be built as part of the port from `testing` to `master`.  But, with this change my massive example is making it to the next stage (still failing though, because the module can't be converted to svex).  I think this change can be confirmed as correct just by inspection.

Fixing bug in vl-to-svex-main

---

books/centaur/vl/transforms/unparam/lineup.lisp
books/centaur/vl2014/transforms/unparam/lineup.lisp

@solswords or @jaredcdavis Can you please merge as appropriate?
I'm pretty sure that the changes are legit.  I haven't built the entire regression yet (just the books that I've modified), because it'll be built as part of the port from `testing` to `master`.  But, with the VL (not VL2014, which I haven't tested at all beyond building the book) my massive example is making it to the next stage (still failing though).  I think these changes can be confirmed as correct just by inspection.

Fixing bug in VL[2014] lineup transform msg

---

books/std/basic/defs.lisp

This is useful for verifying guards in the consequent assuming the truth of the
antecedent, unlike the IMPLIES function.
As suggested by Jared on the mailing list, I'm adding it to std/basic/defs.lisp.
Its definition is slightly different from IMPLIES* in bdd/bdd-primitives.lisp.

Add macro for logical implication defined via IF.

---

books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/gather-paging-structures-thms.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/gather-paging-structures.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/paging-basics.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/paging-pml4-table-lemmas.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/paging-top.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging-lib/x86-ia32e-paging-alt.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/system-level-memory-utils.lisp

Some quick misc. edits to x86isa paging-lib books
- Fixed x86isa doc topics without proper parents, as pointed out by
Matt Kaufmann and Eric Smith (thanks!).
- Included the equality of certain bits of cr0, cr4, and ia32_efer in
the definition of xlate-equiv-x86s.
- Defined alternate versions of rm08 and wm08, called rm08-mapped and
wm08-mapped respectively, for reasoning in the system-level mode.

Fix x86isa doc topics without proper parents and some other misc. changes

---

books/std/lists/nth.lisp

I saw the comment in std/lists/acl2-count.lisp about whether theorems like these should go into that file or into the files for the various list functions. Perhaps they could go into the files for the various list functions, as is already the case in nthcdr.lisp. So this is why I added these to nth.lisp.

Add theorems about ACL2-COUNT of NTH.

---

books/doc/relnotes.lisp

I thank @shigoel  for her patience in combining huge rtl/rel11 commit logs in #572
and add a pair of books to the list of rtl/rel11/support books certifiable by ACL2(r)

rel-notes: Add more rtl/rel11/support books certifiable by ACL2(r)

---

books/kestrel/general/alists.lisp
books/kestrel/general/top.lisp

I used 'programming' as additional xdoc parent for now, but perhaps 'std/alists' might be more appropriate?

Type of alists from symbols to symbols, nil-terminated.

---

books/kestrel/system/world-queries-tests.lisp
books/kestrel/system/world-queries.lisp

As pointed out by Matt Kaufmann, a NON-EXECUTABLEP property with value NIL is
not the same as the function being "executable" in an intuitive sense. It just
means that the function has not been explicitly marked as non-executable
(e.g. via a DEFUN-NX). So the new system utility just returns the value of that
property; its documentation clarifies the relationship between the result and
"executability".

Replace EXECUTABLEP system utility with NON-EXECUTABLEP.

---

books/arithmetic/equalities.lisp
books/centaur/fty/tests/terms.lisp
books/cowles/acl2-agp.lisp
books/cowles/acl2-asg.lisp
books/cowles/acl2-crg.lisp
books/cowles/package.lsp
books/workshops/1999/knuth-91/aof.lisp
books/workshops/2006/cowles-gamboa-euclid/Euclid/ed1.lisp
books/workshops/2006/cowles-gamboa-euclid/Euclid/ed3.lisp

Books cowles/acl2-*.lisp define equivalence relation `equiv`.
It is desirable if other functions in these books
would respect this relation by full set of congruence rules.
This fix also uses macros `defequiv` and `defcong`
instead of boilerplate equivalence/congruence text.
Below is an example of concrete abelian semigroup functions.
They pass `defattach` before the change, but some congruences fail.
`defattach` fails after the change.
```lisp
(in-package "ACL2")
(include-book "misc/assert" :dir :system)
(include-book "cowles/acl2-asg" :dir :system)
(defn my-pred (x)
(booleanp x))
(defn my-equiv (x y)
(iff x y))
(defn my-op (x y)
(if (equal x 0) (not y) (and x y)))
(defattach
(acl2-asg::pred my-pred)
(acl2-asg::equiv my-equiv)
(acl2-asg::op my-op))
(assert! (acl2-asg::equiv
0
t)) …
```

More congruences in Cowles algebra books.

---

books/centaur/bitops/top.lisp
books/cowles/acl2-agp.lisp
books/cowles/acl2-asg.lisp
books/cowles/acl2-crg.lisp
books/cowles/package.lsp
books/doc/more-topics.lisp
books/ihs/ihs-doc-topic.lisp
books/rtl/rel11/lib/doc.lisp

There were a discussion in #585 a few months ago about adding a new MATH topic directly under TOP, moving the existing ARITHMETIC topic to be a child of MATH. 
Sorry for a long delay. This pull request tries to implement that discussion
Organize some of math XDOC stuff in such a hierarchy:
```
Math
Algebra
Abelian-groups
Abelian-semigroups
Commutative-rings
Arithmetic
Arith-equivs
Arithmetic-1
Lispfloat
Proof-by-arith
Bit-vectors
Bitops
Ihs
Rtl
```

Math XDOC topic.

---

books/projects/doc.lisp
books/projects/quadratic-reciprocity/euclid.lisp
books/projects/quadratic-reciprocity/euler.lisp
books/projects/quadratic-reciprocity/fermat.lisp
books/projects/quadratic-reciprocity/support/euclid.lisp

Avoid name conflict between `s` functions in `euclid.lisp` and `record.lisp`.
Create XDOC topic `number-theory`. It's parent is `arithmetic`.
Write markup for some books of @russinoff and attach them to the new topic.

Xdoc number theory

---

books/centaur/bitops/congruences.lisp
books/centaur/bitops/parity.lisp
books/centaur/sv/svex/lattice.lisp
books/ihs/basic-definitions.lisp
books/ihs/logops-definitions.lisp
books/ihs/logops-lemmas.lisp
books/models/jvm/m5/demo.lisp
books/projects/symbolic/m5/demo.lisp
books/projects/x86isa/machine/instructions/fp/fp-cvt-base.lisp
books/projects/x86isa/machine/instructions/rotates.lisp
books/projects/x86isa/machine/x86-register-readers-and-writers.lisp
books/std/basic/arith-equivs.lisp
books/std/basic/defs.lisp
books/std/strings/binary.lisp
books/workshops/2003/moore_vcg/support/demo.lisp
books/workshops/2006/pike-shields-matthews/core_verifier/Fibonacci/proof-fibs.lisp
books/workshops/2006/pike-shields-matthews/core_verifier/RC6/proof-RC6.lisp

These commits update some bit-level reasoning libraries (primarily ihs and centaur/bitops) to take advantage of ACL2's new ability to regard `bitp` as a typeset.  This is fairly disruptive to some libraries.  I have fixed the breakage this causes within the community books but I decided to make a pull request rather than just pushing because it might also cause breakage in non-public books.
Especially, @shigoel -- this affects proofs in the x86 model in a few places.  That said, I think this is an improvement in reasoning power and should eventually be incorporated.

Bitp updates

---

books/projects/x86isa/machine/guard-helpers.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-arithmetic-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-bitscan-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-convert-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-logical-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-mov-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-mxcsr-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-shuffle-and-unpack-instructions.lisp
books/projects/x86isa/machine/instructions/fp/x86-fp-simd-integer-instructions.lisp
books/projects/x86isa/machine/instructions/x86-arith-and-logic-instructions.lisp
books/projects/x86isa/machine/instructions/x86-bit-instructions.lisp
books/projects/x86isa/machine/instructions/x86-conditional-instructions.lisp
books/projects/x86isa/machine/instructions/x86-divide-instructions.lisp
books/projects/x86isa/machine/instructions/x86-exchange-instructions.lisp
books/projects/x86isa/machine/instructions/x86-jump-and-loop-instructions.lisp
books/projects/x86isa/machine/instructions/x86-move-instructions.lisp
books/projects/x86isa/machine/instructions/x86-multiply-instructions.lisp
books/projects/x86isa/machine/instructions/x86-push-and-pop-instructions.lisp
books/projects/x86isa/machine/instructions/x86-rotate-and-shift-instructions.lisp
books/projects/x86isa/machine/instructions/x86-segmentation-instructions.lisp
books/projects/x86isa/machine/instructions/x86-subroutine-instructions.lisp
books/projects/x86isa/machine/x86-decoding-and-spec-utils.lisp
books/projects/x86isa/machine/x86-programmer-level-memory.lisp
books/projects/x86isa/machine/x86-top-level-memory.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy-init.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy.lisp

- Added functions to read/write 6 and 10 bytes of memory.  Thanks to @nadezhin for this suggestion that comes in useful to read memory operands of the form m16:32 and m16:64. 
- Added alignment checking support that is cognizant of whether a 32-bit memory operand is of the form m16:16 or simply m32 --- the natural boundary in the former case is any even address and in the latter case is an address divisible by 4.
- Proved that rm-size and wm-size are equal to rb and wb, respectively. Unlike other rm*/wm* functions, rm-size and wm-size are not defined in terms of rb and wb. That may happen in the future.
- Fixed some conflicts.

Added support for checking alignment of memory operands of the form m<x>:<y>

---

books/build/make_cert_help.pl

Perl gives me a warning on every output of month during certification on my Locale.
It looks like:
Wide character in print at /export/home/dn146861/dist/acl2/acl2-devel.defprod/books//build/make_cert_help.pl line 526.
Making /export/home/dn146861/t/ole72a/fgu/acl2/models/concrete/ma/xmontmul-proof.cert on 13-сен-2016 15:09:53
`сен` is Septemeber in Russian.
The line 526 of make_cert_help.pl is:
print "Making $printgoal on " . strftime('%d-%b-%Y %H:%M:%S',localtime) . "\n";
So `srtftime` gives UTF8 month on my locale and this causes warnings.
To avoid warnings I suggest to allow perl to output UTF8 month by:
use utf8;
binmode(STDOUT,':utf8');

Avoid perl warnings during certification.

---

books/centaur/sv/cosims/Makefile
books/centaur/sv/cosims/run.lsp
books/centaur/sv/cosims/test.sv

`centaur/sv/cosims` contains cosimulation script for two commercial
Verilogs: `vcs` and `ncv`. Some users or students haven't access to commercial
Verilogs. It would be good to give them opportunity to compare ACL2 Verilog
with some open-source Verilog, for example with Icarus Verilog.
This patch modifies scripts to give oppotunity it use `iv` (Icarus Verilog)
and marks those tests where Icarus Verilog fails. There are 117 `no_iv` marks
while there are only 16 `no_vcs` marks and 37 `no_ncv` marks.
So some of these tests may become bug reports to Icarus Verilog developers.

Cosimulation with Icarus verilog

---

books/std/io/read-file-lines-no-newlines.lisp
books/std/io/read-file-lines.lisp
books/std/io/top.lisp

This is a variant of read-file-lines by @jaredcdavis.  I copied it and made a few small changes.  Not sure if we should drop the mention of Kookamara as the contact (either way is fine with me).

add read-file-lines-no-newlines

---

books/projects/x86isa/machine/x86.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/marking-mode-top.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/marking-mode-utils.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/non-marking-mode-top.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging/common-paging-lemmas.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging/page-walk-side-effects.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/paging/top.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy-init.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy-part-1.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy-part-2.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy.lisp
books/projects/x86isa/proofs/zeroCopy/non-marking-mode/zeroCopy.lisp
books/projects/x86isa/tools/execution/examples/zeroCopy/zero-copy-precond-check.lsp

These functions collect the physical addresses of the paging entries
that govern the translation of a given linear address.  The old name
that began with the prefix "translation-governing-addresses" was
misleading.  The new prefix is "xlation-governing-entries-paddrs".

x86isa: Renamed all functions with the prefix "translation-governing-addresses"

---

books/centaur/sv/tutorial/alu16.v
books/centaur/sv/tutorial/lib/flop.v

I tried loading the example verilog code from the SV tutorial into a verilog simulator and got some errors. I know nothing about verilog, but apparently the output wire from the flip-flop module should be a register...? Hence this pull request. (Plus an extra commit to fix indentation.) Sorry if I'm barking up the wrong tree!

Mark flip-flop output as register

---

books/centaur/sv/cosims/run.lsp

Drop comment lines fro Icaruse Verilog output.
This was in the pull requets #641, but lost.

Drop comment lines fro Icaruse Verilog output.

---

books/centaur/sv/svtv/process.lisp

Removed some extraneous words and commas.  Removed `:ones` signals
from the examples because the text later says they're deprecated in
favor of the integer literal `-1`.

Tweak :DOC SV::SVTV-STIMULUS-FORMAT

---

books/build/make_cert_help.pl

A lot of books certify in "0s" or "1s", so I thought it would be nice to
offer a little higher precision for ranking purposes.  Millisecond
precision is also the default output for the `time` command in recent
Bash versions.
The Time::HiRes module is shipped with the base Perl system since Perl
5.8, which was released in 2002, so I think it should be safe to use.

Display cert.pl build times to the millisecond

---

books/centaur/sv/svtv/process.lisp

When printing `svex-env-p` values using `svtv-print-alist-readable`,
every 4vec value which has some non-Boolean component (i.e. is not a
2vec) is (before this commit) displayed with a comment off to the
right giving a "non-Boolean mask", which is a bitvector showing which
bits are either X or Z, i.e. not a Boolean value 0 or 1.
This commit moves the non-Boolean mask to a separate line and aligns
it with the upper and lower components of the 4vec.  With the new
positioning, it's easier to visually compare the non-Boolean mask with
the 4vec's components, as well as with other nearby values of the same
bit width.
Also, this change makes it far less likely for the pretty-printed
svex-env-p value to run into word wrapping issues.  Formerly, due to
the spacing used, the non-Boolean mask would …

Improve formatting of non-Boolean masks

---

books/centaur/sv/svtv/process.lisp

At some point, more keyword arguments were added to `svtv-run`, but
the theorems associated with `svtv-run` don't account for these
arguments.  This commit attempts to fix that situation by generalizing
the `svtv-run` theorems to account for cases where the user used
`:include`, `:simplify`, and `:readable`.
----
Note: some of these changes are just simple generalizations of the LHS, but others materially change the RHS of the rule, so please check that I haven't done anything stupid.

Extend svtv-run theorems to other keyword args

---

books/build/certlib.pl

Struct `Certinfo` has no member `certparams`, but it does have a
member `params`.  I presume that's what was intended here.

Make `cert.pl -v` not crash

---

books/misc/find-lemmas.lisp

`find-lemmas-fn` was repeatedly calling `deref-macro-name` on the
function names supplied by the user, every time it inspected an event
recorded in the world.  When the world is very long, this can be very
time consuming because `deref-macro-name` uses tables, which as
pointed out in `:doc tables` are "not especially efficient".
This commit makes it so that `deref-macro-name-list` is only called
once per invocation of `find-lemmas`.  In one example, running
`find-lemmas` in a world containing more than 1.5 million triples used
to take more than 5 minutes, but now it completes in 0.15 seconds.

Make `find-lemmas` much faster

---

books/nonstd/nsa/continuity.lisp

The comments Matt added in 04a6f6d9084a647dccee1e508e108895bb8c0e6a are no longer meaningful, so this commit removes them.  An alternative would be to edit the comments so it's clear they are historical.  In any case, the `cert_param` declaration seems unnecessary.
(Please check -- I'm not too familiar with how ACL(r) books are certified.)

Remove obsolete comments (followup to #693)

---

books/build/make_cert_help.pl

Currently, the cert.pl-based certification process mentions each
certificate in three separate messages -- once when it starts
building, and twice when it finishes building.
Example:
Making /acl2/books/centaur/sv/svtv/decomp.cert on 04-Apr-2017 10:55:48
Built /acl2/books/centaur/sv/svtv/decomp.cert (28.753s)
-rw-rw-r-- 1 kini kini 334873 Apr  4 10:56 decomp.cert
Of the two messages seen when the certificate has finished building,
the first one has plenty of useful information, such as the full path
of the certificate and the amount of time taken to build it, as well
as a nice ANSI color when printed in the terminal.
The final message is just output from `ls -l`.  It only contains the
relative path of the certificate, and some various filesystem metadata
which I imagine is not really …

Don't ls cert after announcing successful build

---

books/centaur/sv/svex/4vec.lisp

SVEX: Minor documentation fix in `3vec-==` and `4vec-==`.
Also clean trailing blanks.

SVEX: Minor documentation fix in 3vec-== and 4vec-==.

---

books/doc/relnotes.lisp

As discussed in the ACL2 2017 Workshop, I've added the skeleton for :doc note-7-5-books in books/doc/relnotes.lisp.
I also edited topics github-commit-code-using-push and github-commit-code-using-pull-requests to urge people to add high-level information about their changes to the appropriate note-x-x-books topic.

Added the skeleton for :doc note-7-5-books

---

books/std/io/open-channels.lisp

`open-input-channel-p1` and `open-output-channel-p1` have no doc
topics about them, so I changed the @(tsee)s to @({})s.
This should fix a build failure caused by #742.

Fix XDOC errors

---

books/coi/defung/defung.lisp
books/ordinals/lexicographic-book.lisp

There's a perfectly good nat-listp function built into ACL2 which could be used instead.  I also made one of the theorems local, since it's not a theorem about symbols introduced in the book and seems irrelevant to the purpose of the book (other than that it's used in the proofs of the main theorems in the book).

Remove natp-listp from ordinals/lexicographic-book

---

books/doc/relnotes.lisp
books/interface/infix/infix.lisp
books/std/std-customization.lsp

Starting with a7ad6e8b7f80ca87777d6ff679975efd3d21118c (in 2015),
`:monitor` has been able to accept symbols and some other runic
designators instead of just runes, as before.  So `why` and
`why-explain` need no longer wrap symbol names with `(:rewrite ...)`.
This generalizes `why` and `why-explain` by allowing one to monitor
linear rules as well, for example.

Generalize `why` and `why-explain`

---

books/add-ons/hash-stobjs.lisp

I put the functions in the same order they're in in the system code, and synced them up a bit -- some usages of `the$` were missing, and some optimizations that prevented useless `type` declarations from being generated.  It might be helpful to look at the two commits here separately, because the first commit does the reordering without making changes, and the second commit does the actual changes without moving anything.

Clean the redef'd system functions in `hash-stobjs.lisp` a bit

---

books/xdoc/fancy/xdata2html.pl
books/xdoc/fancy/xslt.js
books/xdoc/parse-xml.lisp
books/xdoc/prepare-topic.lisp

This also fixes the broken build caused by the &ndash; entities I
added in 5ff084930591689ca022e7d2bca65b976a10fe8a.
Thanks to @acoglio for noticing the build failure and letting me know.

Add support for &ndash; to XDOC

---

books/centaur/bitops/ihsext-basics.lisp
books/projects/x86isa/machine/x86-ia32e-paging.lisp
books/projects/x86isa/machine/x86.lisp
books/projects/x86isa/proofs/popcount/popcount-general.lisp
books/projects/x86isa/proofs/utilities/system-level-mode/marking-mode-utils.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy-init.lisp
books/projects/x86isa/proofs/zeroCopy/marking-mode/zeroCopy.lisp
books/projects/x86isa/proofs/zeroCopy/non-marking-mode/zeroCopy.lisp

The enabled rule `bitops::unsigned-byte-p-when-unsigned-byte-p-less`
is an duplicate of the disabled rule `bitops::unsigned-byte-p-incr`.
To simplify this state of affairs, I removed the former and enabled
the latter.

Remove duplicate rule in bitops library

---

books/centaur/bitops/ihsext-basics.lisp

In the previous commit, I enabled unsigned-byte-p-incr.  This commit
enables the corresponding rule for signed-byte-p.
Followup to #767.

Enable signed-byte-p-incr to match

---

books/misc/untranslate-patterns.lisp

I surmise that at some point, tabs in this file were converted to an incorrect number of spaces, so this PR fixes that. The first, more important commit fixes only example forms in docstrings, which affects how the XDOC manual looks. The second commit fixes indentation of actual code in the file. If you don't want the second commit, I can roll it back.

Fix indentation in misc/untranslate-patterns

---

books/ihs/logops-definitions.lisp

This way you can use it by just enabling it, rather than by needing to write a `:use` hint.

Make unsigned-byte-p-unsigned-byte-p a disabled rule

---

books/xdoc/parse-xml.lisp
books/xdoc/word-wrap.lisp

Most of the code comments and XDOC docstrings in the ACL2 codebase are
written with double spaces between sentences.  This is natural since
many ACL2 developers are Emacs users, and by default Emacs considers
sentence boundaries to contain a double space (i.e. the Emacs Lisp
variable `sentence-end-double-space` is set to `t` by default).
However, when XDOC docstrings are converted into plain text for use in
the acl2-doc Emacs documentation browser, those double spaces are
converted into single spaces during "whitespace normalization".
That inconsistency always got on my nerves, and this commit finally
gets around to fixing it.  The sentence end detection logic is
simplistic, but it seems to work in most cases.  It looks for periods,
exclamation points, and question marks, possibly behind …

(setq sentence-end-double-space t)

---

books/projects/avr-isa/avr8_isa.lisp
books/projects/avr-isa/avr8_isa_lemmas.lisp

Written permission to release under MIT/X11 obtained in a
personal email from Julien to David Rager, sent on October 9th
and 10th.
Code taken from http://www.win.tue.nl/~jschmalt/publications/acl215/avr_isa.tar.gz
Copyright and license added (again, with permission) as a
courtesy by David Rager.

Adding AVR model by Julien Schmaltz

---

books/xdoc/topics.lisp

I always search for `xdoc::syntax` in the manual before remembering
the correct doc topic name is `xdoc::markup`, so I figure this alias
might help someone else in the future.
Also corrected an example in :doc defpointer while I was at it.

Link :doc xdoc::syntax to :doc xdoc::markup

---

books/acl2s/cgen/top.lisp
books/xdoc/top.lisp
books/xdoc/topics.lisp

Previously, defpointer took its arguments and ignored what package
they were in, incorrectly using the symbols with the same names in the
current package instead.  Now it respects the package in which its
arguments lie.
In making this change, I also had to decide what the link text of the
pointer should look like, depending on what package the linked doc
topic's symbol was in.  I decided that if the `from` and `to` symbols
were both in the same package, we should leave off the package
qualification in the text, and otherwise we should include it.
I also added a guard to the macro to ensure that only symbols are
accepted.
----
Something's still kind of weird here -- if you look at the generated HTML manual, XDOC's notion of what the "base package" is for both the …

 Make defpointer support package-external symbols

---

books/projects/stateman/README
books/projects/stateman/acl2-customization.lsp
books/projects/stateman/byte-addressed-state.lisp
books/projects/stateman/cert.acl2
books/projects/stateman/package.lsp
books/projects/stateman/portcullis.acl2
books/projects/stateman/portcullis.lisp
books/projects/stateman/stateman22.lisp

Moved stateman into SMAN package.  Turns out the .lsp file didn't need to be updated -- potentially a sign of a good interface.
I may add some more license information later.

Move stateman into SMAN package

---

books/GNUmakefile

The comment says that if this hack is no longer needed by December
2015, it should be removed.  Clearly, it is already past December
2015, so we should remove it.
---
Or so confidently declares my commit message, but what do you think?

Remove ACL2_SAVE_QUICKLISP hack in Makefile

---

books/doc/top-topic.lisp

Somehow, through dozens if not hundreds of C-t g keystrokes, I never noticed that one of the first hyperlinks is broken! This pull request tries to fix that.

Replace a defunct link

---

books/README.md

Thanks to Dave Hardin for noticing that the instructions for downloading stable
releases using git were not working shortly after the release of ACL2 8.0.
While making fixes to address this, I decided to make various other changes as
well.

Rework README

---

books/finite-set-theory/set-theory.acl2
books/finite-set-theory/set-theory.lisp

The function `packn-in-pkg` in this file duplicates the system function `packn-pos`, so this commit removes the function definition and replaces calls of it with calls of `packn-pos`.
One reason to reject this pull request might be that this book's didactic purpose makes it desirable to define `packn-in-pkg` in the book so readers can easily see what it does, whereas `packn-pos`'s definition is elsewhere, in the ACL2 sources.
Another reason to reject this pull request might be that because it is the companion file to J's paper "Finite Set Theory in ACL2", it shouldn't be changed if possible, lest it diverge from the exposition in the paper.
As an aside, there are many books in the repository which are companion files to publications, such as most of the books in the `workshops` directory. …

Remove duplicate function in set-theory.lisp

---

books/projects/filesystems/block-listp.lisp
books/projects/filesystems/file-system-1.lisp
books/projects/filesystems/file-system-2.lisp
books/projects/filesystems/file-system-3.lisp
books/projects/filesystems/file-system-4.lisp
books/projects/filesystems/file-system-5.lisp
books/projects/filesystems/file-system-6.lisp
books/projects/filesystems/find-n-free-blocks.lisp

Thanks are owed to @myall86 who suggested proving results about overlapping reads in the context of read-over-write properties, during my seminar talk. Such a result already existed for L1 (defthm l1-stat-after-write ...), but I have now done the thing for L2, L3, L4 and L6 as well. This also allowed me to revise my existing read-after-write proofs and speed them up in some cases. I've also re-factored in order to move certain functions and related theorems to a separate book. Finally, I've added read-over-write proofs for L6.
(These changes have been tested with "make all" in the books/ directory.)

Add some theorems left out from the last pull request

---

books/std/typed-lists/unsigned-byte-listp.lisp

This is handy while reasoning about unsigned-byte arrays within stobjs.

Add a lemma

---

books/std/osets/computed-hints.lisp
books/std/package.lsp

The function defined by automate-instantiation computes a hint, prints it as a "suggestion" to the user, and then immediately provides that same hint to the theorem prover.
Since the hint is being provided to the prover anyway, there doesn't seem to be a need to also tell the user about it, and these hints are often very large and contribute a lot of noise to the proof output when trying to prove a large theorem that uses pick-a-point subset reasoning a lot.
So, this commit greatly abbreviates the message that the computed hint prints.  The new message is only one or two lines long, and still tells the user how to disable the hint (in case the pick a point strategy is ruining the proof), but doesn't supply any further information.
---
If you don't want to abbreviate the message, I could …

Abbreviate output from osets pick-a-point strategies

---

books/projects/smtlink/doc.lisp

These additional notes provide slightly alternative instructions, for installing Z3 machine-wide on Mac.
I'm making a pull request instead of pushing because this is @pennyan's file and so she has to agree to the change. Alternatively, I can create a separate file somewhere else with :doc z3-installation as :parent.
Also, if any Python experts have corrections or improvements in regard to the prefix/package issue, please let me know.

Expand the manual page about Z3 installation.

---

books/centaur/sv/failtest/Makefile
books/centaur/vl/linttest/parse/check.rb
books/centaur/vl/linttest/parse/spec.sv
books/centaur/vl/loader/parser/clocking.lisp
books/centaur/vl/loader/parser/elements.lisp
books/centaur/vl/loader/parser/interfaces.lisp
books/centaur/vl/loader/parser/modules.lisp
books/centaur/vl/mlib/fmt.lisp
books/centaur/vl/mlib/immdeps.lisp
books/centaur/vl/mlib/print-context.lisp
books/centaur/vl/mlib/writer.lisp
books/centaur/vl/parsetree.lisp
books/centaur/vl/transforms/annotate/make-implicit-wires.lisp
books/centaur/vl/transforms/annotate/shadowcheck.lisp

Fix confusion in the parsing code for clocking blocks.  We had been using
backtracking to handle cases where the clocking_event begins with an
identifier, but that is impossible: they always start with @.  Also fix an
oversight in the element parsing code: it was only invoking the clocking block
parser for "clocking", but not for "default clocking."
Add a parser and representation for "default disable" blocks.  Note that like
clocking blocks, these are effectively ignored throughout most of VL and are
not supported in any sensible way, but at least we will now be able to parse
them.
Extend linttest/parse to check that we can parse a module with a default
clocking block and a default disable construct.

VL: clocking blocks and "default disable" parsing

---

books/projects/smtlink/verified/Smtlink.lisp
books/projects/smtlink/verified/extractor.lisp
books/projects/smtlink/verified/uninterpreted-fn-cp.lisp

Fixing non-existent parents warning from Smtlink documentation

Fixing Smtlink documentation

---

books/centaur/sv/vl/trunc.lisp
books/centaur/vl/lint/leftright.lisp
books/centaur/vl/lint/qmarksize-check.lisp
books/centaur/vl/linttest/fussy/check.rb
books/centaur/vl/linttest/fussy/spec.sv
books/centaur/vl/linttest/trunc/check.rb
books/centaur/vl/linttest/trunc/spec.sv
books/centaur/vl/mlib/json.lisp
books/centaur/vl/mlib/selfsize.lisp

- Suppress truncation and extension warnings when the RHS has the form {n{0}}.
In either case you're just getting zeroes anyway and this seems fine.
- Suppress extension warnings when the RHS has the form {'0,...}.  This will
get zero extended as intended so all is well.
- For fussy size-warnings, treat integer-valued system calls like
$countones(...) more like plain integer constants.
- Suppress qmark-width warnings for (foo ? bar : baz) where foo refers to a
plain, untyped parameter.  This is a bow to, e.g., `parameter WITH_FOO = 1`
where the user intends the parameter to be 0 or 1 but has not bothered to
give a type.
- Treat all expressions within parameter declarations as "indexy" for the
purposes of left-right checking.  This should suppress warnings about
constructs like `parameter …

VL: linter tweaks

---

books/doc/relnotes.lisp
books/projects/filesystems/fat32.lisp
books/projects/filesystems/file-system-2.lisp
books/projects/filesystems/file-system-3.lisp
books/projects/filesystems/file-system-lemmas.lisp
books/projects/filesystems/file-system-m1.lisp
books/projects/filesystems/file-system-m2.lisp
books/projects/filesystems/find-n-free-blocks.lisp

This pull request touches only my own books, with one exception. I have reworked some of @MattKaufmann 's edits to the 8.2 release notes from earlier today, to correct the unintended implication that the std/io byte-combining libraries are part of the Kestrel books - so it would be neat if he could review and merge.

Update filesystem books

---

books/projects/async/de.lisp
books/projects/async/fifo/comp-v-or.lisp
books/projects/async/gcd/README
books/projects/async/gcd/comp-gcd-body.lisp
books/projects/async/gcd/comp-gcd-body2.lisp
books/projects/async/gcd/comp-gcd-cond.lisp
books/projects/async/gcd/comp-gcd.lisp
books/projects/async/gcd/comp-gcd2.lisp
books/projects/async/gcd/comp-gcd3.lisp
books/projects/async/gcd/gcd-alg.lisp
books/projects/async/gcd/gcd-spec.lisp
books/projects/async/gcd/gcd.lisp
books/projects/async/gcd/q10-comp-gcd3.lisp
books/projects/async/gcd/q10-gcd.lisp
books/projects/async/hard-spec.lisp
books/projects/async/macros.lisp
books/projects/async/serial-adder/32-bit-serial-adder-old/de.lisp
books/projects/async/serial-adder/serial-add.lisp
books/projects/async/serial-adder/serial-sub.lisp
books/projects/async/serial-adder/sipo-sreg.lisp
books/projects/async/utils.lisp

ASYNC: Replaced 'pairs' with 'pairlis$' in the definitions of the 'se' and 'de' functions

ASYNC: Replaced 'pairs' with 'pairlis$' in 'se' and 'de'

---

books/centaur/aignet/mark-impls.lisp
books/projects/filesystems/file-system-lemmas.lisp
books/projects/filesystems/file-system-m2.lisp
books/std/lists/nth.lisp

This pull request trims an unnecessary function call from an STD rule, fixes a regression which arises, and incorporates the new rule into the filesystem books.

Trim an STD rule

---

books/system/doc/developers-guide.lisp

This clears up a part of the developers' guide that I found a little
hard to follow. It also, while keeping the end result the same,
slightly changes the order of operations in the process of merging
a contributor's branch, in order to reduce the number of merge commits
produced. Since this pull request follows personal discussions as well as list discussions with @MattKaufmann , I'd prefer that he should merge.

Update developers' guide

---

books/build/jenkins/build-single.sh

I don't know how the bash alias ever worked, but changing it to
an environment variable should do the trick.

Changing startjob from bash alias to env variable

---

books/build/jenkins/build-multi.sh

Use environment variable for startjob in jenkin's multiple lisp script.

Use env var for startjob in jenkins multi script

---

books/centaur/fty/basetypes.lisp
books/doc/relnotes.lisp
books/std/basic/pos-fix.lisp

The function POS-FIX, along with its accompanying theorems and XDOC topic, has
been moved from [books]/centaur/fty/basetypes.lisp to a new file
[books]/std/basic/pos-fix.lisp, for improved modularity.
:DOC POS-FIX has been slightly modified: (1) the FTY::BASETYPES parent has been
removed because it is now a more general independent topic compared to its role
in FTY, and (2) the wording has been tweaked.

[Std & FTY] Factor out POS-FIX.

---

books/GNUmakefile
books/doc/top-slow.lisp
books/doc/top.lisp

Renamed doc/top to doc/top-slow, renamed doc/top-fast to doc/top. Added doc/top-slow to list of slow books in GNUMakefile.
Will merge this in a day or two unless anyone wants to weigh in.

Replace doc/top with doc/top-fast

---

books/acl2s/mode-acl2s-dependencies.lisp
books/doc/relnotes.lisp
doc/acl2-code-size.txt
doc/home-page.html
other-events.lisp

add xdoc links from 8.3 relnotes to ecurve, ecdsa, and keccak

add xdoc links from 8.3 relnotes to ecurve, ecdsa, and keccak

---

books/centaur/vl/lint/ifdef-report.lisp
books/centaur/vl/mlib/json.lisp

Re-fixing issue from last JSON VL check-in
Fixing this again with hopefully no merge conflicts. Fixing the redundant definition issue I messed up in check-in last night.

Re-fixing issue from last JSON VL check-in

---

books/kestrel/java/atj/code-generation.lisp
books/kestrel/java/atj/pre-translation.lisp
books/kestrel/java/package.lsp
books/kestrel/std/system/remove-trivial-vars.lisp
books/kestrel/std/system/remove-unused-vars.lisp
books/kestrel/std/typed-alists/symbol-symbol-alistp-tests.lisp
books/std/alists/remove-assocs.lisp

I saw a couple of built-in functions, first-n-ac and make-list-ac, which seemed like they should have documentation topics even if only one line long.

Small xdoc changes

---

books/centaur/fty/bitstruct.lisp
books/centaur/gl/def-gl-rewrite.lisp
books/centaur/ipasir/ipasir-logic.lisp
books/ihs/logops-definitions.lisp
books/kestrel/crypto/ecdsa/deterministic-ecdsa-secp256k1.lisp
books/projects/x86isa/machine/decoding-and-spec-utils.lisp
books/projects/x86isa/machine/linear-memory.lisp
books/projects/x86isa/machine/prefix-modrm-sib-decoding.lisp
books/projects/x86isa/machine/segmentation.lisp
books/projects/x86isa/tools/execution/init-state.lisp
books/projects/x86isa/tools/execution/top.lisp

I'm making a PR, instead of pushing directly, because this affects books written by others, in particular @MattKaufmann, @jaredcdavis, @solswords, @shigoel, and @bendyarm. If nobody objects, I'll merge this in a few days.
This is a follow-up  to an email sent by @MattKaufmann on the acl2-books mailing list.

Remove TABs from XDOC strings.

---

books/quicklisp/top.lisp

[I'm making a PR, instead of pushing directly, so that anybody interested in this can review.]
Mention that OpenSSL may need to be installed, as recently discussed on the ACL2
Help and ACL2 Books mailing lists.

Improve the documentation of Quicklisp.

---

books/kestrel/utilities/system/event-form-lists.lisp
books/kestrel/utilities/system/event-forms.lisp
books/system/pseudo-good-worldp.lisp

This is for @MattKaufmann to merge.
This is in file [books]/system/pseudo-good-worldp.lisp. The changes to this file
have been written by Matt Kaufmann, but I'm the one creating this commit because
of necessary changes in some Kestrel files noted below. The update consists in
replacing PSEUDO-FORMP, which was used for both event and command forms, and
also allowed atoms, with two new functions PSEUDO-EVENT-FORMP and
PSEUDO-COMMAND-FORMP with more specific checks for events and commands; there
are also the -LISTP versions of both predicates, replacing PSEUDO-FORM-LISTP.
The new functions PSEUDO-EVENT-FORMP and PSEUDO-EVENT-FORM-LISTP are equivalent
to the ones in [books]/kestrel/utilities/system/event-forms.lisp and
[books]/kestrel/utilities/event-form-lists.lisp, which have been tweaked …

Replace PSEUDO-FORMP, used in PSEUDO-GOOD-WORLDP.

---

books/system/pseudo-event-form-listp.lisp
books/system/pseudo-event-formp.lisp
books/system/pseudo-good-worldp.lisp

@MattKaufmann Can you please quickly review and either merge or ask me to make changes?
This was discussed with Matt and J.
The functions PSEUDO-EVENT-FORMP and PSEUDO-EVENT-FORM-LISTP in
[books]/system/pseudo-good-worldp.lisp have been moved to two separate
files. The comment block just after 'EVENT-LANDMARK [GLOBAL-VALUE]' has been
moved to the new file pseudo-event-formp.lisp, and slightly tweaked, since it
essentially referred to event forms.
A :GUARD T declaration has been added to both functions, since they are no
longer under the VERIFY-GUARDS-EAGERNESS 2 setting of pseudo-good-worldp.lisp.
This way, they are still guard-verified.
Now pseudo-good-worldp.lisp includes pseudo-event-form-listp.lisp (which
obviously includes pseudo-event-formp.lisp). A comment has been added just …

Factor two functions out of pseudo-good-worldp.lisp.

---

books/doc/relnotes.lisp
books/std/typed-lists/string-or-symbol-listp.lisp
books/system/pseudo-good-worldp.lisp

Since this affects Std, I'm making a PR instead of pushing directly. I'll merge in a few days if there are no objections.
The recognizer has been factored out of [books]/system/pseudo-good-worldp.lisp.
Also added an XDOC topic for this.

[Std/typed-lists] Add lists of strings and symbols.

---

books/workshops/2020/hardin/README.md
books/workshops/2020/hardin/stk-thms.lisp
books/workshops/2020/hardin/stk.cpp
books/workshops/2020/hardin/stk.h
books/workshops/2020/hardin/stk.lisp

A basic example for my talk at the 2020 ACL2 Workshop.
ACL2 books (stk and stk-thms) should certify with standard cert.pl.
The .c and .h files are only "for show" -- the stk.lisp code is generated from them 
using Russinoff's RAC tools, but those tools aren't normally built, and there's no 
reason for the average user to concern themselves with recapitulating the 
C -> ACL2 translation.
Please let me know if there are any issues with these files.
-- David Hardin

Hardin 2020 ACL2 Workshop Materials (Try #2)

---

books/projects/smtlink/examples/examples.lisp
books/projects/smtlink/z3_interface/ACL2_to_Z3.py

Andrew Walter and Pete Manolios have brought to our attention of a soundness bug in Smtlink. It is recommended that theorems depending on Smtlink (especially ones using the macro /)should be recertified using this new version of Smtlink. Sorry for the trouble.
The bug is from how I handled the translation of unary-/. For example, when encountering (unary-/ x) where x is of integerp, Smtlink will translate it into 1.0/x. Z3 does not follow the Python convention but uses integer division in this expression.
In file examples.lisp, the diff is an example showing the soundness problem of this translation. Below theorem gets proved because of this bug.
```
(defthm smt-not-integer-division
(implies (and (integerp x)
(integerp y)
(integerp z)
(>= x 10)
(= y (* (unary-/ x) z)))
(= y 0))
:hints …
```

Fixing the soundness bug that unary-/ can be interpreted as integer division in Smtlink

---

books/doc/relnotes.lisp
books/std/util/deflist-base.lisp
books/std/util/tests/deflist.lisp

I'm making a PR since this affects STD::DEFLIST. But it shouldn't cause any issues for existing uses.
I'll merge this in a few days if there are no objections.
Now DEFLIST supports the :PREPWORK option, like other macros in Std/util (and in
FTY).

[Std/util] Extend DEFLIST with :PREPWORK.

---

books/projects/leftist-trees/leftist-tree-sort.lisp
books/sorting/convert-perm-to-how-many.lisp
books/sorting/how-many.lisp
books/sorting/ordered-perms.lisp
books/sorting/orderedp.lisp

This pull request deals with an upcoming name conflict on 'perm'.  The
leftist-trees project brings in a definition of perm from books/sorting/.
However, leftist-trees doesn't need to export anything involving perm.
Furthermore, this version of perm comes into the manual only via leftist-trees.
The changes are in two parts:
1. In books/sorting/, split two functions, how-many and orderedp, into separate
small books containing only these definitions.
2. Change leftist-trees to include these new, smaller books (non-locally) and
to include a book about perm only locally.
The result is that the version of perm from books/sorting/ is not in the manual
and so doesn't conflict with the one in books/kestrel/lists-light/perm (which
we use fairly extensively, including in material we hope to add to …

Reduce deps of leftist trees

---

books/build/features.sh
books/std/util/defrule.lisp

I found this commit lying around on an old branch and figured I'd submit a PR. I ran a regression successfully except that I ran out of "immobile space" in SBCL when building the manual (I'm pretty sure that's unrelated to this change, though).
----
Before this commit, `defrule` would always add keyword arguments `:hints`, `:otf-flg`, and `:instructions` to the generated `defthm` form, even when their values were `nil` (i.e. equal to their default values).  Now it doesn't add those arguments unless they're necessary, which makes `:pe` output a little less verbose.
Before:
```
ACL2 !>:trans1 (defrule foo bar)
(DEFTHM FOO BAR
:HINTS NIL
:OTF-FLG NIL
:INSTRUCTIONS NIL)
```
After:
```
ACL2 !>:trans1 (defrule foo bar)
(DEFTHM FOO BAR)
```

defrule: suppress nil keyword arguments to defthm

---

books/centaur/satlink/solvers/satlink_lib.pl

The `centaur/satlink/solvers/test-glucose-cert.lisp` books builds with this change.
It seems like the `drup-trim` reference is no longer best practices.  My guess is
that this change is already intended, but just hasn't been done yet.

Update satlink_lib.pl to use drat-trim

---

books/std/lists/list-defuns.lisp
books/std/lists/sets.lisp

The removed lemma, set-equiv-implies-iff, is completely subsumed by set-equiv-implies-iff-member-2 from the same file, as demonstrated here:
```
(make-event `(thm ,(formula 'set-equiv-implies-iff t (w state)) :hints
(("goal" :in-theory (union-theories '(set-equiv-implies-iff-member-2)
(theory 'minimal-theory))))))
```

Remove a redundant lemma

---

books/interface/emacs/mfm.el

As string-to-int is deleted function in Emacs 26.x, I replaced it with string-to-number.
We can use string-to-number even before Emacs 26.x. Thus, this request is not a breaking change for users who are using Emacs 25.x .

Remove string-to-int

---

books/std/strings/digit-to-char.lisp

Since this affects Std/strings, I'm making a PR.
I'll merge in a few days if nobody objects.
The new theorem could perhaps be enabled by default, since arguably the right-hand side is simpler than, or preferable to, the left-hand side, but I'm being more conservative for now.

[Std/strings] Add a theorem about DIGIT-TO-CHAR.

---

books/projects/milawa/doc.lisp

This patch fixes various XDOC links to the Milawa documentation. The documentation has been moved from the University of Texas CS department user pages to Jared Davis's personal website.

Fix Milawa links

---

books/GNUmakefile
books/doc/relnotes.lisp

I started down the route of changing GNUmakefile but stopped, because I wasn't sure how to go about testing all of the changes in a reasonable amount of time.  Do I need to test it on every Lisp?  Do I need to test it with every version of ACL2?  Do I need to test all of the different targets?  I did test it on CCL with the default (hons) version of ACL2.
Also, I'd feel more comfortable if someone were to check the logic changes for removing the slow books.  I know it is a change, but is it a reasonable one, and did I implement it correctly?  Please keep in mind that the primary goal is to make the build more maintainable, and having all sorts of random functionality isn't all that important relative to that first goal, imho.
Please don't merge this directly.  I've used "WIP:" as a …

Improve books makefile

---

books/nonstd/nsa/sqrt-iter.lisp
books/workshops/2018/gamboa-cowles/complex-continuity.lisp

This is at least a partial fixing of the ACL2(r) build.
The key was to make the inclusion of arithmetic/top local.  I think it's unreasonable to roast @kini for this oversight, because he had clearly asked for a review.  It was interesting to me how many books broke as a result.
I'm currently running both a vanilla and acl2(r) build overnight on leeroy2 (see http://leeroy2.defthm.com/job/fixing-acl2r/) and will merge accordingly tomorrow.  I'll need to merge in the latest from the testing branch before doing that, but I don't plan to worry about it too much.
Please nobody "undo" Keshav's PR #1135.  At this point, let's just push through with it.  Hopefully Keshav can address whatever feedback Ruben has in a follow-up commit.

Make include-book local; change a few references

---

books/build/features.sh
books/build/shell.nix
books/centaur/ipasir/ipasir-logic.lisp
books/centaur/ipasir/load-ipasir-sharedlib-raw.lsp

The doc topic IPASIR::BUILDING-AN-IPASIR-SOLVER-LIBRARY claims that to
get the ipasir shared library working, it is sufficient to set
$IPASIR_SHARED_LIBRARY to the library's filename alone, and put its
directory in the $LD_LIBRARY_PATH list.
Unfortunately, while the loading code in load-ipasir-sharedlib-raw.lsp
itself is able to handle this, features.sh is stricter and requires
$IPASIR_SHARED_LIBRARY to contain a full path to the shared library,
so running `make regression` will skip the ipasir books if the library
is pointed to by a directory path in $LD_LIBRARY_PATH and a filename
in $IPASIR_SHARED_LIBRARY.
This commit generally expands the different ways in which the user is
able to provide an ipasir shared library for the ipasir-related books
to build from.  See the changes made to …

Be more flexible in loading libipasirglucose4.so

---

books/centaur/4v-sexpr/sexpr-loop-debug.lisp
books/defsort/defsort.lisp
books/defsort/generic.lisp
books/projects/filesystems/abs-syscalls.lisp
books/projects/filesystems/file-system-lemmas.lisp
books/std/lists/nthcdr.lisp

I thought it would be nice to have the obvious set-equiv theorem automatically generated by defsort. I mostly stuck to local events, but I did add an event to the nthcdr book. Additionally, I made local copies of lemmas that appear in other books, such as subsetp-trans, subsetp-member and subsetp-append1. Let me know if you would prefer me to include those books instead.
The filesystem books are also updated as part of this pull request.

Add to the lemmas automatically generated by defsort

---

books/projects/filesystems/abs-syscalls.lisp
books/projects/filesystems/abstract-separate.lisp
books/projects/filesystems/hifat-syscalls.lisp
books/projects/filesystems/hifat.lisp
books/std/alists/abstract.lisp
books/std/typed-alists/string-string-alistp.lisp
books/std/typed-alists/string-symbollist-alistp.lisp
books/std/typed-alists/symbol-pseudoterm-alistp.lisp
books/std/typed-alists/symbol-symbollist-alistp.lisp

There's a fairly common kind of rule which can be automatically generated by `fty::defalist`. I removed some existing rules which either had a name conflict with the newly generated rules, or else did the same thing under a different name.
The filesystem books are also updated as part of this pull request.

Automatically generate some rules

---

books/std/alists/abstract.lisp
books/std/typed-alists/keyword-symbol-alistp.lisp
books/std/typed-alists/keyword-truelist-alistp.lisp
books/std/typed-alists/string-symbollist-alistp.lisp
books/std/typed-alists/symbol-pseudoterm-alistp.lisp
books/std/typed-alists/symbol-symbol-alistp.lisp
books/std/typed-alists/symbol-symbollist-alistp.lisp
books/std/typed-alists/symbol-truelist-alistp.lisp

There's another fairly common kind of rule which can be automatically generated by fty::defalist. I removed some existing rules which either had a name conflict with the newly generated rules, or else did the same thing under a different name.

 Automatically generate some rules

---

books/system/to-do.txt

There's no real urgency about this. I was trying to make a hypothesis-free rewrite rule about subseq (disabled in my books) and append, and the number of cases blew up - hence this suggestion.

Add a to-do list item about subseq and subseq-list

---

books/projects/filesystems/file-system-lemmas.lisp
books/projects/filesystems/hifat-to-lofat-inversion.lisp
books/projects/filesystems/hifat.lisp
books/projects/filesystems/tar-stuff.lisp
books/std/strings/eqv.lisp

This lemma follows from the definition of charlisteqv, but doesn't seem to exist although I grepped for similar lemmas.
The filesystem books are also updated as part of this pull request.

Add a lemma about str::charlisteqv

---

books/tools/run-script.lisp
books/xdoc/constructors.lisp

I changed the wording a little in run-script that cleared up a misunderstanding I had when I first read it, and added some links that explain the keyword arguments.
The only change in xdoc was a cut-and-paste error where it referred to csee when it should have referred to tsee.

small doc changes to run-script and xdoc

---

books/centaur/misc/starlogic.lisp

Unless I'm mistaken, if* has its own documentation topic and is separate from star logic.

Remove reference to if*, unrelated to non-case-splitting-logic

---

books/centaur/sv/mods/alias-norm.lisp
books/centaur/sv/mods/lhs.lisp
books/centaur/sv/mods/moddb.lisp

[This is the next step, after adding `:executablep` to `deffixtype`.]
Replace uses of :EXECP with the new :EXECUTABLEP.

Update use of keyword in DEFFIXTYPE.

---

books/clause-processors/join-thms.lisp

This fixes two calls of (er soft ...) which previously led to bad calls of FMT1.
To reproduce the problem fixed by this commit, do:
(include-book "clause-processors/join-thms" :dir :system)
(defevaluator evl evl-list nil)
(def-join-thms ev)

[join-thms] Fix two error messages.

---

books/centaur/fty/fixtype.lisp

Before merging this PR, users of `fty::deffixtype` who use `:execp` in non-community-book files should update those files to use `:executablep` instead, which is the option described in the user documentation. (All the community books that used `:execp` have already been updated to use `:executablep` in a previous commit.)
The second commit is purely aesthetic.

Remove :execp from fty::deffixtype

---

books/build/cert.pl

This PR only affects whitespace in generated output.

Delete (some) trailing whitespace from generated makefiles

---

books/kestrel/apt/simplify-defun-doc.lisp

I was trying out simplify-defun earlier, and I had to spend a while figuring out the correct book to include. Perhaps adding this line will help the next reader.

Make a minor addition to :doc apt::simplify-defun-examples

---

books/std/alists/alistp.lisp

[Making a PR since it affects Std. I'll merge in a few days if there are no objections.]
This is disabled by default, because the hypothesis is about alists while the
conclusion is about lists and involves a common predicate.
There is already a compound recognizer version of this rule, but in some cases
the rewrite rule seems needed. This new theorem can be enabled in those cases.
Another option could be to just add :rewrite to the rule classes of the existing
compound recognizer rule. Maybe there should be a more unified policy about
this, at least in the Std library, ideally as a more general ACL2 style guide.

[Std/alists] Add theorem.

---

books/projects/filesystems/hifat.lisp
books/std/lists/prefixp.lisp

This lemma probably shouldn't cause excessive backchaining, because it only gets tried when prefixp is already being reasoned about.

Move a lemma to community books

---

books/std/lists/prefixp.lisp

This generalisation, applied to both these lemmas, is somewhat limited
because ACL2 is often able to draw the obvious conclusion when two
number-valued terms satisfy <= and >= at the same time. Sometimes ACL2
isn't, though, and that makes this generalisation worthwhile. It
brings in a case-split arising from the definitions of <= and >=
respectively, but that has not proven to be a problem anywhere in the
regression suite.

Slightly generalise two lemmas

---

books/xdoc/fancy/xdoc.js

This patch improves the ACL2 manual by making the file paths shown at the top of each topic be clickable links to GitHub.
When the path is something like "[books]/path/to/file.lisp" the link goes to that particular file on GitHub.
When the path is just "ACL2 sources", the link goes to the GitHub page that lists the files in the main ACL2 directory (since we can't tell from the text "ACL2 Sources" which source file should be shown).
Warning: This required editing Javascript, but I don't know Javascript!

Make file locations shown at top of xdoc topic pages be links

---

books/centaur/fty/docgen.lisp

This pull request addresses a minor xdoc issue that produces warnings like this:
WARNING: in topic AIGNET::AXI-LIT, subtopic order mentions topics that
are not children: AIGNET::AXI-LIT.
Note that the topic is being listed among its own children, which I think never makes sense.  Disclaimer: I don't know much about defflexsum, but the call (member x.name type-names) a few lines above my change indicates that this situation can happen.
With this change, the related warnings go away.

Minor xdoc fix for defflexsum

---

books/centaur/aignet/abc.lisp
books/centaur/misc/tshell-tests.lisp
books/centaur/misc/tshell.lisp
books/centaur/satlink/top.lisp

Tshell currently depends (transitively, including via local includes) on 200 books.  Many of these seem unnecessary, such as IHS and osets and much more.  This change cuts the dependencies down to 24 books.
The comment "used in the raw code" on an include-book that I commented out gave me pause, but it doesn't seem to be true.  Everything still seems to build (after I added a few include-books in other places).
We have a use case where it would be very nice to have tshell depend on less stuff, because it supports an application we want to package up with Docker, and we want to certify and ship less stuff.

[centaur] Reduce dependencies of tshell.

---

books/projects/arm/utils/aarch64-specs.lisp
books/projects/arm/utils/rtl-utils.lisp
books/projects/rac/lisp/internal-fns-gen.lisp

Fixed a bug in projects/rac/lisp/internal-fns-gen.lisp reported by Matt. The bug is in the following binding.
(sub-pairs-with-dots (pairlis$ (strip-cars sub-pairs)
(strip-cars (strip-cdrs sub-pairs))))
(strip-cars (strip-cdrs sub-pairs)) may cause error when (strip-cdrs sub-pairs) returns a non-empty list, but not an alist.
My fix is to change the binding above to the following,
(sub-pairs-with-dots (pairlis$ (strip-cars sub-pairs)
(strip-cars-hack (strip-cdrs sub-pairs))))
where strip-cars-hack behaves like strip-cars, except that it also collects atom elements when walking through its list argument. For example, (strip-cars-hack '((A) B (C))) would return '(A B C).

Fixed a bug in projects/rac/lisp/internal-fns-gen.lisp

---

books/projects/smtlink/config.lisp
books/projects/smtlink/examples/examples.lisp
books/projects/smtlink/smtlink-config

/usr/bin/env is not available in Nix build environments, and its use
in the smtlink default configs seems to be redundant.

Remove "/usr/bin/env" in smtlink config

---

books/projects/x86isa/doc.lisp

Duplicate of #1303 but merging into `acl2:testing` instead of `acl2:master`.

Remove duplicate entry in x86isa publications list

---

books/std/util/defines.lisp

Fixes issue #1309.  An existing code comment mentioned this issue but seems wrongheaded, as exemplified by the issue filed by Eric McCarthy.  It seems perfectly reasonable to supply return value types in :program mode, either simply as documentation or because some code is in :program mode only temporarily.  In that case, this commit ensures that defines will not fail.
Normally, generated theorems would be simply skipped in :program mode.  The failure here is caused by the use of defthm-flag to prove them, since the corresponding make-flag is skipped in :program mode.
Standard disclaimers apply: My head is not really in this code.

[DEFINES] Suppress return-value theorems in :program mode.

---

books/centaur/fty/fixtype.lisp

This calls translate-cmp with logic-modep=nil, to prevent an error when the form involved contains :program mode functions.
This is related to deffixequiv and seems needed to allow a define with :hooks (:fix) to work when submitted in :program mode.  My head's not in this machinery, and perhaps there is a legitimate reason to ban this.  But I suspect this use case was simply not considered.  Ideally, tools like define would still work even in :program mode (but proofs would be skipped, of course).

[FTY] Tweak a call of translate-cmp.

---

books/kestrel/utilities/directed-untranslate.lisp

This fixes a crash in directed-untranslate.  To see the crash, do this:
(include-book "kestrel/utilities/directed-untranslate" :dir :system)
(defun foo (a b) (mv a b))
(directed-untranslate
;; uterm:                                                                                                                                                    
'(mv-let (a b) (foo 1 0) (declare (ignore b)) a)
;; translated form of uterm:                                                                                                                                 
'((lambda (mv)
((lambda (a b) a)
(mv-nth '0 mv)
(hide (mv-nth '1 mv))))
(foo '1 '0))
;; term to untranslate (same as previous argument): …

[directed-untranslate] Fix crash in handling of mv-let.

---

GNUmakefile

Currently, when creating the target `doc` the dependency acl2-manual
is invoked. acl2-manual does not use the MAKE variable but instead
uses the make command directly. The target
books/system/doc/rendered-doc.lsp does the same. According to the
make manual, "recursive make commands should always use the variable
MAKE, not the explicit command name ‘make’" [1]. Since both of these
are recursive calls, the variable should be used instead.
This has already been patched and tested within the Gentoo science
repository [2]. Gentoo's package manager portage will throw a Q/A issue:
"make[1]: warning: jobserver unavailable: using -j1. Add '+' to parent
make rule" when compiling from source code if the patch is not applied.
This further suggests that this change is necessary.
[1] …

Use $(MAKE) variable, not the explicit command name ‘make’

---

books/std/system/irrelevant-formals-input.lsp
books/std/system/irrelevant-formals-log.txt
books/std/system/irrelevant-formals.lisp

Here is an example for which the old version gave what seems to be the wrong answer:
(irrelevant-formals-info
'(mutual-recursion
(defun even-natp (x irrelevant1 irrelevant2)
(if (zp x)
t
(not (odd-natp (+ -1 x) irrelevant1 irrelevant2))))
(defun odd-natp (x irrelevant3 irrelevant4)
(if (zp x)
nil
(not (even-natp (+ -1 x) irrelevant3 irrelevant4))))))
It gave:
((EVEN-NATP . IRRELEVANT2)
(ODD-NATP . IRRELEVANT4))
which is missing irrelevant1 and irrelevant3.  After this change, it gives:
((EVEN-NATP IRRELEVANT1 IRRELEVANT2)
(ODD-NATP IRRELEVANT3 IRRELEVANT4))

Irrelevant formals fix

---

books/kestrel/auto-termination/README
books/kestrel/auto-termination/termination-database.lisp
books/kestrel/auto-termination/write-td-cands.lsp
books/top.acl2
books/top.lisp

This was discussed on the acl2-books mailing list.  See also the comments at the top of books/top.lisp.
I believe, but am not positive, that I've updated the auto-termination stuff appropriately after this change.

Move books/doc/top-slow.lisp to books/top.lisp.

---

books/doc/relnotes.lisp

This is the documentation for the cert-heed-useless-runes-2 branch PR#1341.
This does not include the three derived files `doc.lisp doc/acl2-code-size.txt doc/home-page.html`
because I think it is possible that there will be merges that would require they be regenerated.
I can add them to this PR if needed.

doc corresponding to change making cert.pl use useless runes

---

books/nonstd/nsa/Banach-Tarski/README.md
books/nonstd/nsa/Banach-Tarski/banach-tarski-b-0.lisp
books/nonstd/nsa/Banach-Tarski/banach-tarski-s2.lisp
books/nonstd/nsa/Banach-Tarski/banach-tarski.lisp
books/nonstd/nsa/Banach-Tarski/countable-sets.lisp
books/nonstd/nsa/Banach-Tarski/free-group.lisp
books/nonstd/nsa/Banach-Tarski/groups.lisp
books/nonstd/nsa/Banach-Tarski/hausdorff-paradox-1.lisp
books/nonstd/nsa/Banach-Tarski/hausdorff-paradox-2.lisp
books/nonstd/nsa/Banach-Tarski/rotations.lisp
books/nonstd/nsa/Banach-Tarski/supportive-theorems.lisp

rotation.lisp: Added a lemma about r3-rotationp
banach-tarski-s2.lisp: Added a lemma about rotation-3d.
banach-tarski.lisp: Contains proof of the Banach-Tarski theorem on the unit ball.
Changed descriptions in the beginning of the files.
Updated README.md

A Formal Proof of the Banach-Tarski Theorem in ACL2(r)

---

books/xdoc/top.lisp

This pull request fixes a problem that occurs when defpointer is used to point to an xdoc topic whose name is an unusual symbol, such as a symbol that includes spaces. Without this patch, the following gives an error:
(include-book "xdoc/topics" :dir :system)
(defxdoc |foo bar| :short "example")
(defpointer my-pointer |foo bar|)
:doc my-pointer
The error message is:
; xdoc error in MY-POINTER:
"In SEE directive, expected ) after FOO. Near See @(see acl2::foo bar)..".
ACL2::MY-POINTER -- Current Interactive Session
Note the space between foo and bar in the generated @(see ...) form; this is not suitable for reading back in the symbol |foo bar|.
This fix is more conservative than one I proposed a long time ago in that it always includes the package of the symbol.

[xdoc] Fix defpointer to tolerate symbols with unusual names.

---

books/doc/relnotes.lisp
books/projects/x86isa/machine/cpuid.lisp
books/projects/x86isa/machine/dispatch-macros.lisp

This is as discussed with Shilpi.
The added documentation (easily in the diff) explains this change.

[X86ISA] Improve modeling of CPUID features.

---

books/centaur/vl/doc.lisp
books/centaur/vl2014/doc.lisp
books/std/osets/top.lisp

This changes two links in the xdoc to match the links from the workshop page  
https://www.cs.utexas.edu/users/moore/acl2/workshop-2004/
Not changed, but needs to be changed:  
A grep turns up two more broken links that I did not change
because I did not see an appropriate link target.  Those links are
```
./books/centaur/vl2014/doc.lisp:href='http://www.cs.utexas.edu/users/jared/publications/2013-doform-embedding/embedding.pdf'>Embedding
./books/centaur/vl/doc.lisp:href='http://www.cs.utexas.edu/users/jared/publications/2013-doform-embedding/embedding.pdf'>Embedding
```
Maybe Jared or another knowledgeable reviewer can update these other broken links.

fix links to 2004 workshop paper and slides on std/osets

---

books/projects/x86isa/machine/instructions/divide-spec.lisp

It appears that the lower and upper bounds of the signed quotient were slightly
off, as they should be the normal two's complement limits. This commit fixes
them.
This issue was first noticed by Eric Smith.

[X86ISA] Fix bounds in IDIV specification.

---

books/std/util/bstar.lisp

Reduces size of B*-binders xdoc page from ~2000 entries to <40 entries.

Don't create xdoc for b*-binder unless parents, short, or long given

---

books/tools/flag.lisp

When defthm-flag-xxx is called with no arguments, it creates a template form for the user to fill out.  That form includes placeholder hyps for each template theorem.  Previously these were always literally (AND HYP1 HYP2), with the user expected to replace the meaningless HYP1 and HYP2 with meaningful hyps (or delete them).  Now, for a function with a non-trivial guard, that guard is used for the hyp instead, since it is fairly likely to be needed in theorems about the function.  The user is still welcome to edit the hyps, of course.
Here is an example for all-vars1 (note the hyps):
Old behavior:
```
(DEFTHM-FLAG-ALL-VARS1 (DEFTHM THEOREM-FOR-ALL-VARS1
(IMPLIES (AND HYP1 HYP2)
(PROP (ALL-VARS1 TERM ANS)))
:FLAG ALL-VARS1)
(DEFTHM THEOREM-FOR-ALL-VARS1-LST
(IMPLIES (AND HYP1 HYP2)
(PROP …
```

[make-flag] Improve defthm-flag.

---

books/kestrel/fty/deffixequiv-sk-doc.lisp
books/kestrel/fty/defunit-doc.lisp
books/xdoc/cert.acl2

Prior to this change, books/xdoc/cert.acl2 contained:
(include-book "centaur/fty/portcullis" :dir :system)
which seemed unnecessary.  I don't see any mentions of fty in xdoc/, and nothing broke when I removed this include-book.
The include-book led to unnecessary dependencies, for example b* depending on books/centaur/bitops/portcullis.lisp (since fty depends on centaur/bitops/portcullis).

[xdoc] Avoid including centaur/fty/portcullis in xdoc/cert.acl2.

---

books/projects/paco/database.lisp

With ACL2 8.4 on Linux, proving a (trivial) theorem using Paco results in the following error:
```
ACL2 !>(include-book "projects/paco/paco" :dir :system)
Summary
Form:  ( INCLUDE-BOOK "projects/paco/paco" ...)
Rules: NIL
Time:  5.53 seconds (prove: 0.00, print: 0.02, other: 5.52)
"/home/kazarmy/tar/acl2-8.4/books/projects/paco/paco.lisp"
ACL2 !>:paco
"PACO"
PACO !>(dthm true t)
Computing and transferring the ACL2 environment to Paco...
ACL2 Error in ACL2::TRANSFER-NUME-TO-RUNE-MAP:  Theory invariant 1,
defined in book
"/home/kazarmy/tar/acl2-8.4/books/arithmetic/equalities.lisp", failed
on the theory produced by
(ACL2::UNIVERSAL-THEORY-FN :HERE (ACL2::W ACL2::STATE)).  Theory invariant
1 is
(NOT (AND (ACL2::ACTIVE-RUNEP '(:REWRITE ACL2::UNIQUENESS-OF-*-INVERSES))
(ACL2::ACTIVE-RUNEP …
```

Use `current-theory` in Paco's `transfer-nume-to-rune-map` function instead of `universal-theory`

---

books/centaur/aig/aig2c.lisp
books/centaur/bigmem/bigmem.lisp
books/centaur/defrstobj/defrstobj.lisp
books/centaur/defrstobj2/defrstobj.lisp
books/centaur/glmc/glmc-generic-proof.lisp
books/centaur/vl/util/namedb.lisp
books/projects/x86isa/machine/environment.lisp

This change prevents centaur/vl/util/namedb from including centaur/vl/util/defs.  Various include-books have to be added in namedb.lisp, and other files, to compensate, but the net effect is to greatly reduce what is included by namedb and tools that include it, including defrstobj, the x86 model, and Axe.
This change reduces the number of books included by defrstobj2 from 213 to 127.  Among the things no longer included are utilities for encoding strings in HTML!   The number of books included by kestrel/axe/top decreases from 1238 to 1169.  And projects/x86isa/top goes from 398 books to 329 books.
Further improvements could probably be made in vl by reducing what is included in centaur/vl/util/defs.lisp itself (e.g., not including std/strings/top, which is presumably what brings in the …

[VL] Reduce deps of vl/util/namedb.

---

books/quicklisp/base-raw.lsp
books/quicklisp/bundle/local-projects/fastnumio/read-hex.lisp
books/quicklisp/bundle/local-projects/fastnumio/write-hex.lisp
books/quicklisp/fastnumio-raw.lsp

Also allows it to work on M1 Macs
Also removes bug workaround that was fixed long ago

Fix fastnumio on sbcl

---

books/std/util/bstar.lisp

In
```
(b* (...
((er x) <something>)
...)
...)
```
if `<something>` returns `(mv erp val state)` with non-`nil` `erp`, the `b*` also returns
`(mv erp val state)`.
Instead, in
```
(b* (...
((er x :iferr eval) <something>)
...)
...)
```
if `<something>` returns `(mv erp val state)` with non-`nil` `erp`, the `b*` returns `(mv
erp eval state)`, i.e. the chosen `eval` instead of `val`.
This is useful, for example, when writing code that traffics in error triples
whose value components must have different types, when we want those types to be
unconditional. For instance, the `b*` could be in a function `g` whose returned `val`
is unconditionally a string, while `<something>` is a call of a function `f` whose
returned `val` is unconditionally an integer: using just `(er x)` would lead to a
type …

[Std/util] Add an :IFERR option to the ER binder.

---

books/centaur/fty/top.lisp

Closes #446 (it looks like the changer macros for defprod have already been
documented in :doc defprod).

[FYT] Slightly expand some documentation.

---

books/kestrel/apt/propagate-iso-test-4.lisp
books/kestrel/apt/propagate-iso.lisp

Allows reordering of arguments in translated functions
Simplify resulting lambda applications
Add test file to test new capability

propagate-iso: Allow translation of functions to lambda terms

---

books/projects/async/macros.lisp
books/projects/async/package.lsp

This allows me to get the ADE package (in the async books) without having to also take std/strings/istrprefixp, which can cause name clashes.
I had to include define in one book, to compensate for this change.

[async] Reduce dependencies of ASYNC package.

---

books/projects/rp-rewriter/meta/cons-to-list-meta.lisp
books/projects/rp-rewriter/meta/equal-meta.lisp
books/projects/rp-rewriter/meta/fast-alist-free-meta.lisp
books/projects/rp-rewriter/meta/hons-acons-meta.lisp
books/projects/rp-rewriter/meta/hons-get-meta.lisp
books/projects/rp-rewriter/meta/mv-nth-meta.lisp
books/projects/rp-rewriter/portcullis.acl2
books/projects/rp-rewriter/portcullis.lisp
books/projects/rp-rewriter/proofs/local-lemmas.lisp

Similar to a recent change.  The goal is to let me get the package from the portcullis without getting any books not necessary for that.

[rp-rewriter] Remove include-books from portcullis book.

---

books/build/lib/Certlib.pm
books/build/make_cert_help.pl

Recent changes broke cert.pl for many of us.  The issue seems to be that it isn't finding the system books dir using the ACL2 environment variable, due to the function determine_acl2_dirs returning before it can reach the fourth way of setting acl2_books.  So I just conditionalized that return (in the code for the third way).
Big disclaimer: I don't know perl, or anything about cert.pl, so somebody should review this.

[cert.pl] Attempt to fix cert.pl.

---

books/acl2s/installation.lisp

Fix the Eclipse links in the macOS instructions
Substantially update the Windows installation instructions to use the prebuilt distro image
Update Linux instructions to install plugin manually like macOS users

[acl2s] Update ACL2s installation instructions

---

books/acl2s/installation.lisp

[acl2s] Fix issue with ACL2s Windows installation instructions

---

books/acl2s/extra-doc.lisp
books/acl2s/installation.lisp

Fix a markup issue in the ACL2s Windows installation instructions
Add comments about Smartscreen and BAT file downloading in the ACL2s Windows installation instructions
Update the ACL2s tutorial so that it is consistent with our updated ACL2s plugin and Eclipse 2022-09

[acl2s] Minor improvements to ACL2s installation instructions and tutorial

---

books/projects/sb-machine/package.lsp
books/projects/sb-machine/sb.lisp

This allows the package to be obtained without also getting those books.  Add some includes to another book to compensate.

[sb-machine] Reduce dependencies of package.lsp.

---

books/kestrel/apt/isodata-doc.lisp
books/kestrel/apt/isodata-tests.lisp
books/kestrel/apt/isodata.lisp

This option is processed in largely the same way as in `apt::restrict`. It affects what term is placed in the else branch of the top-level `mbt$` conditional of the new function.
The default value of the `:undefined` option is `:auto`, in which case it will default to the current behavior of using `nil` or `(mv nil ... nil)` for single-value and multi-value functions respectively. Note that one can use the quoted value `':auto` if one actually wishes the term `:auto` to be used as the "undefined" value.

Add :undefined option to apt::isodata 

---

books/kestrel/apt/isodata-doc.lisp
books/kestrel/apt/isodata-tests.lisp
books/kestrel/apt/isodata.lisp
books/kestrel/apt/utilities/find-a-base-case-tests.lisp
books/kestrel/apt/utilities/find-a-base-case.lisp

This adds `:base-case` and `:base-case-then` as options to `isodata`'s `:undefined` parameter. When either of these options are provided, `isodata` will choose the undefined value by looking for a base case within the newly generated function. A base case of a term may either be the whole term when the term does not include a recursive call, or if the term is an `if`, then it may be a base case of the `then` or `else` branch. A term may have several base cases; the `:base-case` option is biased toward selecting base cases in `else` branches, while `:base-case-then` is biased toward `then` branches.
The motivation for this feature is that a base-case will likely have a desirable type, and the result may be amenable to combining nested `if`s.

Add base case option to `isodata` `:undefined` parameter

---

books/kestrel/apt/isodata.lisp
books/kestrel/apt/utilities/find-a-base-case-tests.lisp
books/kestrel/apt/utilities/find-a-base-case.lisp

This moves `find-a-base-case` functions to the APT package to avoid potential name clashes with functions in the default ACL2 package.

Move find-a-base-case to APT package

---

books/std/basic/defs.lisp
books/std/basic/maybe-natp.lisp
books/std/basic/top.lisp

Move `maybe-natp` to a separate file, for greater modularity.
Also add an XDOC parent to `pos-fix`.

[Std/basic] Refactor some code.

---

books/std/util/support.lisp

Avoid the `(program)` declaration in the middle of the file, and instead add `:mode :program` to the functions that are not immediately accepted in logic mode. Several functions, previously in program mode, are now accepted in logic mode (and guard-verified). It may be actually easy to put more functions in this file in logic mode (and guard-verified), but this is just a simple change for now.
Also clean up a few commented-out fragments that do not seem to serve a purpose at this point.

[Std/util] Put some code in logic mode.

---

books/acl2s/installation.lisp

Add a FAQ item to the ACL2s installation FAQ regarding how to deal with Eclipse codesigning issues.

[acl2s] Add codesign question to ACL2s installation FAQ

---

books/std/util/support.lisp

The theorem is disabled by default because `true-listp` is a common function.

[Std/util] Add a theorem and disable a function.

---

books/build/jenkins/Makefile

Complete the removal of old code for classic (non-hons) builds.  Non-hons builds are not really supported any more, and that code has been commented out for 5 years.
Avoid setting ACL2_HONS when calling make, since that has no effect.  Also tweak the messages printed to not mention 'h' in the ACL2 variant names.
Add more example usages in comments at top of file.

[jenkins] Simplify Makefile.

---

books/misc/symbol-print-full-escapes.lisp
books/xdoc/top.lisp

Also moved bar-escaping code to a more general location and package so that it can be more easily used for other thiings than xdoc.

fix bugs where backslashes in names were not escaped

---

books/misc/seq.lisp

The `:w=` and `:s=` operators enforce inequalities on the lengths, not the counts, as is evident by looking at the code that implements them.

[Seq] Fix user documentation.

---

books/std/util/defaggregate.lisp

This avoids putting in (logic) or (program) when not needed, since those prevent the defaggregate from being local.  Defaggregate uses progn instead of encapsulate (see comment in defaggregate.lisp), and ACL2 doesn't allow things like (local (progn (logic))).

[defaggregate] Allow a defaggregte to be local in most cases.

---

books/misc/seq.lisp

Instead of returning the original stream if the `mbt` check fails, return the remaining stream from the call that fails the `mbt` check. The advantage is that often the stream processing functions fix the stream to its type, and therefore unconditionally return a remaining stream of the right type. However, if `:s=` and `:w=` return the initial stream, which is not fixed to the right type, then functions using these operators need conditional return theorems. Note that the exact stream returned if the `mbt` check fails does not matter in guard-verified code, because it is provably never returned. But I'm not sure if there are good use cases for returning the original stream instead, when the code is not guard-verified (e.g. in program mode).

[Seq] Improve `:s=` and `:w=`.

---

books/kestrel/c/atc/tests/conversions.lisp

This enables c::bit-width-value-choices where needed in the ATC tests.

[ATC] Enable bit width rules in ATC tests

---

books/centaur/fty/deftypes.lisp

Disabling built-in functions, including `alistp`, reveals that `fty::defprod` relies on `alistp` to be enabled in order for the proofs generated by `fty::defprod` to work. This commit enables `alistp` locally inside the events generated by `fty::defprod`. Enabling this locally to the events makes `fty::defprod` more robust.

[FTY] Enable `alistp` in fixtype macros.

---

books/centaur/fty/deftypes.lisp

Disabling the built-in functions reveals that some FTY macros expect `identity` to be enabled. This commit adds this definition to the theory used in the FTY macros.

[FTY] Locally enable `identity`.

---

books/std/util/da-base.lisp

This prevents defaggregate from failing when hons is disabled.

[std] Tweak hints in defaggregate, etc.

---

books/std/typed-lists/symbol-listp.lisp

The new rule backchains from `true-listp` to `symbol-listp` without limit; it is disabled by default.
The renamed rule is one that backchains at most once, and is enabled.
It seems that using the unqualified `true-listp-when-symbol-listp-rewrite` for the first rule is more consistent with other libraries. This is the reason for renaming the second rule in a way that describes its specific characteristics.

[Std/typed-lists] Add a rule and rename another rule.

---

books/projects/rac/src/Makefile

C++ 17 is now required to compile the RAC parser but in the previous commits, the makefile was still using C++11.

[RAC] Now use C++17

---

books/projects/x86isa/machine/cpuid.lisp
books/projects/x86isa/machine/dispatch-macros.lisp

Before this commit, a file in the X86ISA project defined a `subset-equal` function that is similar to the built-in `subsetp-equal` except for a slightly weaker guard. This commit removes that function, using the built-in `subsetp-equal` instead. A guard of another function had to be slightly strengthened so that its call of `subsetp-equal` can be guard-verified.

[X86ISA] Avoid `subset-equal`.

---

books/kestrel/c/atc/defstruct.lisp
books/kestrel/c/atc/tests/defstruct.lisp

Quoted theories are added to generated forms to reduce proof time.
This commit also adds a static theory to be used by forms which do not include explicit theories. The thought here is that there are many proofs generated by the macro that are already fast, but I don't think we want their success to be dependent on the current user's theory.
Finally, another struct example is added to the `defstruct` tests. This example is large and uses all supported field types (integer members, fixed array members, flexible array members). The `defstruct` is also invoked in an empty theory to show that the macro is independent of the current theory.

[ATC] Add quoted theories to some generated defstruct forms.

---

books/std/lists/rev.lisp

This avoids a double (nested) induction in the proof of `rev-of-rev`. It also seems more natural for `rev-of-append` to immediately follow `rev-of-cons`. Now that `rev-of-append` precedes `rev-of-rev`, the latter is proved with a single induction.

[Std/lists] Swap two theorems in a file.

---

books/interface/emacs/acl2-indent.el

The defaults match my preferences! I am open to persuasion on any of these. I use it with acl2-mode but I tested that it also works in lisp-mode in emacs -q (in Emacs 28.2). Let me know if it behaves badly in any situation. It is generally good enough to be applied to complete files even though its main use is incremental.
Some of the possible customizations:
(defcustom indent-first-function-arg 1
"Amount to indent first argument of a function relative to function”
This gives indentation like:
```
(pseudo-termp
(list* x1 ...
```
To get the previous default behavior set this to 0:
```
(pseudo-termp
(list* x1 ...
```
(defcustom indent-close-paren-to-open nil
"Indent line beginning with close paren to position of matching open paren”
This give indentation like:
```
(let ((x y))
(foo x)
;; …
```

Improved emacs indentation for acl2. Easily customizable.

---

books/build/cert.pl

There are two new lines here.
The line `print $mf "\n\n";`
is needed to close off the list of images so the following comment doesn't start at the end of the previous line.
The `print $mf " \;\@:";` line turns off the message
```
make: Nothing to be done for 'all-cert-pl-images'.
```
that those of us that don't use images are now seeing on every call to `cert.pl`.
It does that by appending an empty recipe.
If you use images and you want to see this message when there aren't any,
then it will have to be done differently---in that case
maybe it could be conditioned on one of the image-related environment variables.

[cert.pl] add newlines after setting CERT_PL_IMAGES; also turn off msg

---

books/quicklisp/zippy-raw.lsp

[zippy] make include-raw of zippy-raw.lsp be idempotent by undoing the renamed package

---

books/quicklisp/bundle/bundle.lisp

Fixes issue #1508 .
After this PR, redoing (include-raw "bundle/bundle.lisp" ..)
(which is called from "quicklisp/base")
does not reset the asdf info since it recognizes it has already been done
in the current environment.
So the second part of the instructions in the comment on issue #1508  becomes:
; 2. Now load the main quicklisp loader book.
ACL2 !>(include-book "quicklisp/base" :dir :system)
ACL2 !>:q
* (asdf:already-loaded-systems)
(... "zippy" ...)

[quicklisp] make the asdf bundle info remember it was loaded and do nothing if reloaded

---

books/std/util/define.lisp

Avoid turning error output back on if it is already inhibited when define is called.
This allows, for example, building tools such as improve-book that submit events that are expected to sometimes fail where we want the failures to be silent.

[DEFINE] Tweak printing.

---

books/coi/osets/set-order.lisp
books/std/osets/primitives.lisp
books/std/osets/top.lisp

- Slightly simplified a theorem (along with two redundant instances of it):
- In the first case, if `X` satisfies `empty`, its `sfix` is always `nil`.
- In the second case, we know that `X` does not satisfy `empty`, and thus it always satisfies `setp`, and there's no need to fix it with `sfix`.
- Fixed and updated some documentation.

[Std/osets] Minor improvements

---

books/projects/smtlink/examples/examples.lisp

Smtlink example 2 shows how to extend smtlink's functionality with a custom python module. Unfortunately, the example also hardcodes the user-configurable python program name, smt-cmd. This change restores the expected behaviour, which pairs the custom module with the user-configured python executable.

Removes hard-coded python name from expt example config

---

books/acl2s/installation.lisp

- Removed discussion of Khoury VDI as that was sunset. 
- Explicitly call out some issues on the macOS installation side. 
- Update Java version referenced in Linux instructions

Several updates to ACL2s installation docs

---

books/workshops/2023/walter-etal/README.md
books/workshops/2023/walter-etal/acl2s-setup.lisp

I removed [extended package prefix syntax](https://www.sbcl.org/manual/#Extended-Package-Prefix-Syntax) from acl2s-setup.lisp, as it picked up in the regression-everything build that Leeroy performs with CCL. CCL does not support extended package prefix syntax, which is why this caused a failure on Leeroy.
I also added a comment in the README that SBCL is required for building this system locally, as the non-ACL2-book parts of the system use this syntax extensively.

[walter-acl2-workshop-2023] Remove extended package prefix syntax from acl2s-setup.lisp

---

books/projects/x86isa/machine/instructions/fp/cmp-spec.lisp

For the double-precision case, the result must be turned into a 64-bit quantity.
This issue was noticed by Eric Smith.
I checked that against the Intel instruction manual.

[X86ISA] Fix typo in code.

---

books/projects/x86isa/machine/instructions/fp/arith-spec.lisp
books/projects/x86isa/machine/instructions/fp/cvt-spec.lisp

These are similar to the one in a previous commit.
Eric Smith first noticed these.
I checked these against the Intel manual.

[X86ISA] Fix two typos in code.

---

books/projects/x86isa/machine/instructions/divide.lisp

The width should be the same as the low bit index, i.e. 8 times the operand size in bytes (i.e. the operand size in bits). It is actually equivalent, because the extra bits are 0, but it seems cleaner to do it this way.
This issue was brought up by Eric Smith.
A guard verification lemma had to be tweaked in order for the guard proofs to go through.

[X86ISA] Tweak models of `div` and `idiv`.

---

books/build/make_cert_help.pl

This can be used to override the default of printing 300 lines of cert.out files for failed (or interrupted) certifications.

[build] Have cert.pl check FAILURE_LINES var.

---

books/projects/schroder-bernstein/acl2-customization.lsp
books/projects/schroder-bernstein/chains.lisp
books/projects/schroder-bernstein/package.lsp
books/projects/schroder-bernstein/portcullis.lisp
books/projects/schroder-bernstein/schroder-bernstein.lisp
books/projects/schroder-bernstein/setup.lisp
books/projects/schroder-bernstein/witness.lisp

This renames the package from `SB` to `SBT` to avoid overlap with the other `SB` package (in `books/projects/sb-machine`).

Rename package of Schröder-Bernstein project

---

books/projects/arm/utils/aarch64-specs.lisp
books/projects/rac/lisp/alt-const-fns-gen.lisp
books/rtl/rel11/lib/defs.lisp
books/rtl/rel11/lib/reps.lisp
books/rtl/rel11/support/definitions.lisp
books/rtl/rel11/support/excps.lisp
books/rtl/rel11/support/verify-guards.lisp

Needed to weaken guards for nencode function.
Also made a minor unrelated change in alt-const-fns-gen.

Modify aarch64 specs to handle AHP mode

---

books/misc/profiling-raw.lsp

Some of the raw Lisp code for `misc/profiling` was gated on the `acl2-mv-as-values feature`, which was removed from ACL2 in August 2021 as it is true on all of the Lisps that ACL2 supports at this time. This meant that the raw Lisp code would never evaluate, preventing `misc/profiling` from working. This PR modifies the code to stop gating the relevant code on the `acl2-mv-as-values` feature.

Remove unneeded acl2-mv-as-values from misc/profiling raw code

---

books/acl2s/interface/acl2s-interface-utils.lsp

An incorrect type specifier in the raw Lisp acl2s-interface-utils file was causing issues on SBCL with safety settings turned up.

[acl2s] Fix incorrect type specifier in acl2s-interface-utils

---

books/acl2s/interface/acl2s-interface-utils.lsp
books/acl2s/interface/acl2s-interface.lsp
books/acl2s/interface/acl2s-utils/extras.lsp

Fix some broken links in the ACL2s interface documentation. Add documentation for quiet mode hooks.

[acl2s] Fix documentation for the ACL2s interface

---

books/xdoc/importance.lisp

The guards on the `extend-links-fal` function in `books/xdoc/importance.lisp` were inconsistent with comments in that file, and the actual types of arguments that were being passed in. This caused `xdoc::save` to fail for me. I updated the guards so that they are consistent with comments and the actual types of arguments being passed in.
I'm not 100% sure why this wasn't caught by anyone else previously - maybe something about the environment in which I call `xdoc::save`?

[xdoc] Fix guards on XDOC `extend-links-fal`

---

books/workshops/2023/kumar-etal/attacks/cert.acl2
books/workshops/2023/kumar-etal/cert.acl2
books/workshops/2023/kumar-etal/demo.lsp
books/workshops/2023/kumar-etal/msgs-state.lisp
books/workshops/2023/kumar-etal/nbrs-topics-state.lisp
books/workshops/2023/kumar-etal/network.lisp
books/workshops/2023/kumar-etal/peer-state.lisp
books/workshops/2023/kumar-etal/scoring.lisp
books/workshops/2023/kumar-etal/utils.lisp

Setting global timeout values and getting rid of overriding timeouts on properties, which were causing issues on slow machines.

set global timeouts

---

books/acl2s/defdata/random-state-basis1.lisp
books/acl2s/defdata/random-state.lisp

I replaced the PRNG used by ACL2s with the Thrust PRNG, which is designed to work with 63-bit state (the seed) and 64-bit outputs. My implementation is an adaptation of Tommy Ettinger's C implementation, which Tommy dedicated to the public domain. The implementation is here: https://gist.github.com/tommyettinger/e6d3e8816da79b45bfe582384c2fe14a
Some quick-and-dirty benchmarking indicates that this implementation is about 2x faster than the previous one.
I also needed to update some of the theorems that were being proved about `genrandom-seed` and `genrandom-state`, as they often used `car` to access the first element of the MV that those functions return. I replaced `car` with `mv-nth 0` in those theorems, which eliminated failures that were occurring in random-state.lisp.
I tested this …

[acl2s] Replace ACL2s' PRNG with the Thrust PRNG

---

books/GNUmakefile
books/build/cert.pl
books/build/doc.lisp
books/build/features.sh
books/kestrel/c/syntax/cert.acl2
books/kestrel/c/syntax/package.lsp
books/kestrel/c/syntax/preprocess-file.lisp
books/kestrel/c/syntax/tests/acl2-customization.lsp
books/kestrel/c/syntax/tests/cert.acl2
books/kestrel/c/syntax/tests/preprocess-file.lisp
books/kestrel/c/syntax/tests/stdbool.c
books/kestrel/c/syntax/tests/stdint.c

Since the preprocessing utility is open-ended in its system dependencies, I've added the cert_param flag "uses-preprocessor" as well as the Makefile variable "USE_PREPROCESSOR" to control certification of books using the tool, such as this new test book.
The feature does not attempt to auto-detect dependencies, and defaults to "off". Thus, you must explicitly set `USE_PREPROCESSOR=1` when invoking make to build the relevant books.
The names of these variables is easy to change. We might consider renaming it to "USE_C_PREPROCESSOR" to be more specific. Or "USE_C_UTILITIES" if we expect other similar utilities to require conditional certification.

Add test cases for c$ preprocessing utility

---

books/kestrel/c/syntax/preprocess-file.lisp
books/kestrel/c/syntax/tests/preprocess-file.lisp

The `oslib::tempfile` utility may return a filepath whose directory does not yet exist. This changes `preprocess-file` to now create said directory before invoking the preprocessor.
This also removes the supporting `absolute-filepath` utility, in favor of the built-in and superior `canonical-filepath`.
Finally, this changes the file extension of files generated by `preprocess-files` to `.i` (which is the expected file extension and understood by compilers).

[c$] Fix tempfile creation in preprocess-file

---

books/kestrel/c/syntax/read-and-parse-files.lisp
books/kestrel/c/syntax/read-files.lisp
books/kestrel/c/syntax/tests/read-and-parse-files.lisp
books/kestrel/c/syntax/tests/read-files.lisp

This changes the boolean `:preprocess` flag in `read-files` and `read-and-parse-files` to `:preprocessor`, which may be either `nil` or a string. If it is a string, it indicates the name of the preprocessor to be used. The default is `"cpp"` (in contrast to the old flag which defaulted to `nil`).

[c$] Change preprocessing-related flags in tools

---

books/std/util/defines.lisp
books/std/util/tests/defines.lisp

This mirrors the existing option provided by `define`.
The only notable implementation change is that `make-fn-defsection` is modified to return two sets of events. The produced `defsection` is split right after the returns theorems (if `:returns-no-induct t` and `:verify-guards :after-returns`) to allow for the `verify-guards` event to be place before the functions' additional events.

Add `:verify-guards :after-returns` option to `defines`

---

books/std/util/defines.lisp
books/std/util/tests/defines.lisp

The generated `verify-guards` event was erroneously using the name of the clique, instead of the name of one of the functions.
Thanks @acoglio for reporting.

Fix clique name bug for `defines` `:verify-guards :after-returns`

---

books/std/io/file-measure.lisp

I noticed that this file was slow to certify.  This change speeds the proofs up by about 100x (~50 seconds to ~0.5 seconds on a very fast machine).

[std/io] Speed up file-measure proof.

---

books/workshops/2023/walter-etal/induction-proof-checker.lisp

Minor changes that drastically reduce the time it takes to certify workshops/2023/walter-etal/induction-proof-checker. Should resolve regression timeouts related to this book.

[workshops] Drastically reduce cert time for 2023/walter-etal

---

books/projects/pdf-parser/pdf-parser.lisp

Add hints for CCG that drastically speed up termination analysis for some functions in projects/pdf-parser/pdf-parser. Should resolve regression timeouts related to this book.

[pdf-parser] Drastically speed up certification of pdf-parser

---

books/kestrel/c/syntax/abstract-syntax-symbols.lisp
books/kestrel/c/syntax/abstract-syntax.lisp
books/kestrel/c/transformation/package.lsp
books/kestrel/c/transformation/rename.lisp
books/kestrel/c/transformation/split-fn.lisp
books/kestrel/c/transformation/tests/split-fn.lisp
books/kestrel/c/transformation/top.lisp
books/kestrel/c/transformation/utilities/acl2-customization.lsp
books/kestrel/c/transformation/utilities/cert.acl2
books/kestrel/c/transformation/utilities/free-vars.lisp
books/kestrel/c/transformation/utilities/top.lisp

This transformation splits a function after a certain number of block items, factoring out the remainder of the function into a new function.
It also provides a couple test cases. The transformation is not yet fully robust. I expect it may currently fail when multiple variables are declared at once, when variables are declared but not immediately initialized, or when variables are declared with type/storage specifiers that cannot or should not be duplicated in the new function's parameter declarations.

[c2c] Add `split-fn` transformation

---

books/centaur/bigmem-asymmetric/bigmem-asymmetric.lisp
books/centaur/bigmem-asymmetric/concrete-asymmetric.lisp
books/kestrel/axe/x86/support-axe.lisp
books/projects/x86isa/virtualization/top.lisp

This has two commits. One updated support-axe.lisp and marks books/projects/x86isa/virtualization/top.lisp as ccl-only. These are necessary to get the regression to succeed.
The other one marks both the concrete and abstract stobjs created by bigmem-asymmetric as non-executable. They each require 6 GB of memory, so this change drastically reduces the amount of memory necessary to certify books. This wasn't done before because :non-executable was not supported on abstract stobjs until recently. I can't certify the doc book on my machine without this change, but it shouldn't be necessary on a machine with more memory.
This has been tested on ACL2 built with CCL.
CC: @solswords @ericwhitmansmith

Fixes for merging updated x86isa model into acl2

---

books/projects/x86isa/virtualization/top.lisp

This resolves the issue introduced in 651623a77e. In an attempt to prevent build failures on non-CCL lisps, the books/projects/x86isa/virtualization/top.lisp book was marked CCL-only because the raw lisp it includes only works on CCL. This causes cert.pl to not build the book when the host lisp isn't CCL. However, this book is a dependency of the doc, so this prevented the doc from building.
This was resolved by, instead of marking the book CCL-only, using #+ccl to only include the raw lisp if the host lisp is CCL. Thus, the virtualization/top.lisp book can and is built when using non-CCL lisps, allowing for the doc to be built, but the raw lisp is not included.
CC: @ericwhitmansmith

Fix doc not building on non-CCL lisps

---

books/std/osets/membership.lisp

Continuation of PR#1583.
Also added a comment about the defthms in the defsection not being found by xdoc::get-event.

[Std/osets] rename empty- to emptyp- in defsection subset-theorems

---

books/centaur/bigmem-asymmetric/bigmem-asymmetric.lisp

The default parents was set to bigmem-asymmetric::bigmem in the bigmem-asymmetric book, likely since that line was copied from the bigmem book, but no such topic exists. This fixes the non-existant parent warnings by setting the default parent to bigmem-asymmetric::bigmem-asymmetric, which is the correct topic.

Fix non-existant parents warning for bigmem-asymmetric when building doc

---

books/acl2s/installation.lisp

In the installation instructions for ACL2s, we now tell macOS users to preemptively re-sign the Eclipse app after installing the ACL2s plugin, to make this issue more visible to users.

[acl2s] Tell macOS users to preemptively re-sign Eclipse

---

books/projects/x86isa/machine/instructions/pio.lisp

The x86isa printk model call passed the string to output directly to
`cw`. This meant that `cw` would interpret it as a format string. This
can cause issues if the string to be printed has a `~` in it.

Fix x86isa modelcall-printk interpreting output as format string

---

books/xdoc/fancy/Dockerfile

While this change was made to support the development of #1635, it is independent from it.
CC: @mister-walter
The old XDOC fancy viewer Dockerfile did not support PHP. The seo friendly version of the manual relies on PHP. This adds support for PHP so that one can use the Dockerfile to test the seo friendly XDOC viewer.

Update XDOC Dockerfile to add support for PHP

---

books/projects/x86isa/machine/decoding-and-spec-utils.lisp
books/projects/x86isa/machine/instructions/x87.lisp

The x86isa/machine/instructions/x87.lisp book, which contains
definitions for the instructions fxsave and fxrstor, was very slow to
certify (~15 minutes on my machine with CCL). This change disables some
runes and adds some lemmas to make this much faster (~200 seconds).
Thanks to Eric for suggesting I look at the reported splitter runes.

Speed up certification of x86isa's x87.lisp (fxsave/fxrstor defs)

---

books/kestrel/c/syntax/parser.lisp

This was found through round-trip testing.  Example input that shows the issue:
union foo { int x; };

[C$] Fix a case where a union was parsed as a struct.

---

books/tools/flag-tests.lisp
books/tools/flag.lisp

When `make-flag` is invoked on a trivial mutual recursion with just one function in the clique, the generated defthm-flag macro fails on subsequent theorems due to a generated lemma being instantiated with the flag variable, but the lemma not actually containing said flag variable. (The lemma would normally be a case statement on the flag variable, but since the clique has just one member, the case statement only has the final "otherwise" condition.)
This PR fixes the issue by adding the `:extra-bindings-ok` keyword, telling the system to just ignore the extra binding when it would otherwise trigger an error.
I also added a test to `flag-tests.lisp` which demonstrates the use case where `make-flag`'s generated defthm macro was previously failing.
(I should probably acknowledge that it is …

Fix `make-flag`-generated macro for mutual recursions with single-function cliques

---

books/projects/x86isa/machine/instructions/psub.lisp

Previously, `simd-sub-spec` would perform a packed add rather than a
packed subtraction. This caused the packed subtraction instrctions (PSUB
and its variants) to perform adds instead of subtractions. This fixes
that bug.

Fix packed subtraction instructions

---

books/projects/x86isa/machine/decoding-and-spec-utils.lisp
books/projects/x86isa/machine/instructions/syscall.lisp
books/projects/x86isa/machine/instructions/top.lisp

This reduces the dependence on other-non-det, which has a ttag and is only used for a few instructions that currently live in machine/instructions/top.lisp.  Future commits could reduce mentions of the :other-non-det ttag.  This is a step towards building x86-related tools (e.g., Axe) without needing (so many) ttags.

[X86ISA] Reduce dependence on other-non-det.lisp.

---

books/tools/include-raw.acl2

A ttag is not needed to certify or include include-raw, only to call it.  A comment in include-raw.lisp seems to indicate that previously a ttag was needed.

[tools] Drop cert-flags for include-raw.

---

books/arithmetic-5/lib/basic-ops/simple-equalities-and-inequalities.lisp

See the comment I added in the file.  Previously, for (equal 5 (+ 0 m)), the rule would add -5 to both sides, which could begin a loop if certain rules are disabled.  It seems better to refrain and hope that other rules simplify the (+ 0 m).
I ran a regression-everything after this change, with no failures found.

[arithmetic-5] Change find-constant-addend to avoid certain loops.

---

books/std/io/read-ints.lisp

While the definition of read-bytes$ supports 8 byte reads, the guard
disallowed them. This fixes the guard to allow 8 byte reads.

Fix read-bytes$ guard for 8-byte reads

---

books/centaur/bigmems/bigmem/bigmem.lisp
books/centaur/bigmems/bigmem/concrete.lisp
books/centaur/defrstobj2/defrstobj.lisp

- **Make the concrete stobj generated by defrstobj2 non-executable**
The concrete stobj generated by defrstobj2 is abstracted away from the
user. Thus, it is never directly used. Making it non-executable saves
memory.
- **Make bigmem::mem and bigmem::mem$c non-executable**
While bigmem::mem itself doesn't use much memory, if one attaches the
bigmem-asymmetric::mem to it, the memory usage can be substantial.
bigmem::mem is generally not used directly, so making it non-executable
to save on memory makes sense and if needed one can use
`add-global-stobj` to use it at the top level.
bigmem::mem$c is only used to back bigmem::mem so making it
non-executable as well shouldn't be an issue and saves some (although
probably insignificant) memory.

Make some stobjs non-executable

---

books/std/osets/intersect.lisp
books/std/osets/top.lisp

The new rules work with certain proofs where the empty set `nil` is involved, which does not match with the `(emptyp ...)` term.
The old rules rewrite terms of the form `(emptyp (intersect x y))` to `t`. The new rules first rewrite that to `(emptyp nil)`, and then the executable counterpart of `emptyp`, which is normally enabled, should turn that into `t`.
Although the matching terms of these rules are quite generic (i.e. `(intersect x y)`, the Std/osets library has other rules with similarly generic matching terms (e.g. `(union x y)` and `(subset x y)`) that are also enabled by default and have no backchain limits. We should probably make all of these disabled by default at some point, and perhaps add them to the `expensive-rules` rule set in Std/osets, or other rule set that can be …

[Std/osets] Make two rules more applicable.

---

books/std/util/def-bound-theorems.lisp

Supplying :gen-rewrite nil now causes the omission of the :rewrite rule class.  This can be useful if such a rewrite rule already exists, to avoid adding an indentical :rewrite rule when creating :type-prescription and/or :linear rules.

[STD/UTIL] Allow def-bound-theorems utils to suppress the :rewrite rule.

---

books/projects/x86isa/machine/application-level-memory.lisp
books/projects/x86isa/machine/instructions/fp/mxcsr.lisp
books/projects/x86isa/machine/instructions/jump-and-loop.lisp
books/projects/x86isa/machine/instructions/push-and-pop.lisp
books/projects/x86isa/machine/instructions/syscall.lisp
books/projects/x86isa/machine/paging.lisp
books/projects/x86isa/machine/register-readers-and-writers.lisp
books/projects/x86isa/machine/segmentation.lisp
books/projects/x86isa/machine/state.lisp
books/projects/x86isa/machine/top-level-memory.lisp

Previously these were spread across various books where needed.  Now they all live in the file where XR is defined.
I suspect that this will help us reduce dependencies (specifically, I saw an unrelated guard proof fail when push-and-pop.lisp was not included, seemingly because push-and-pop.lisp is where n32p-xr-rflags happened to be defined).
Perhaps i48p-xr-rip should be moved too, but I held back because that would have taken it out of its enclosing defsection.
I think there is some duplication between the :rewrite rules generated by these forms and the rules generated by defrstobj.  I plan to look into that.

[X86ISA] Collect type theorems about XR.

---

books/kestrel/x86/x86-changes.lisp
books/projects/x86isa/machine/inst-listing.lisp
books/projects/x86isa/machine/instructions/arith-and-logic.lisp
books/projects/x86isa/machine/instructions/exchange.lisp
books/projects/x86isa/machine/instructions/fp/simd-integer.lisp
books/projects/x86isa/machine/instructions/pcmp.lisp
books/projects/x86isa/machine/instructions/rotate-and-shift.lisp
books/projects/x86isa/machine/instructions/shifts-spec.lisp
books/projects/x86isa/machine/rflags-spec.lisp

- **Fix some x86isa shifts**
The flag computation for SAR treated the CF as undefined when the shift
count was greater than the operand size, but that is incorrect.
Additionally, the count mask was computed incorrectly for byte operands
with a REX prefix
- **Fix x86isa cmpxchg computing incorrect flags**
- **x86isa Fix large SSE2 shift counts causing Lisp errors**
The SSE2 packed shift instructions which take the count as an XMM
register could have a huge (128-bit wide) shift count. These cause CCL
to throw when passed to `ash`.
Clamping the shift count to the el-width resolves this issue. This
commit also cleans up some of the SSE2 shift implementation code.
- **x86isa Implement pcmpgt(b/w/d) instructions**

x86isa: implement pcmpgt and some instruction bugfixes

---

books/projects/x86isa/tools/execution/execloaders.lisp
books/projects/x86isa/tools/execution/init-state.lisp
books/projects/x86isa/tools/execution/instrument/top.lisp

The book about initializing the x86 state doesn't need all the instruction semantic functions.  As is common with this sort of change, include-books had to be added to some downstream books, but overall the dependencies were reduced.
(This change was enabled by an earlier change that collected rules about XR.)

[X86ISA] Reduce inclusion.

---

books/projects/x86isa/proofs/codewalker-examples/base.lisp
books/projects/x86isa/proofs/dataCopy/dataCopy.lisp
books/projects/x86isa/proofs/dataCopy/init.lisp
books/projects/x86isa/proofs/dataCopy/loop-base.lisp
books/projects/x86isa/proofs/dataCopy/loop-recur.lisp
books/projects/x86isa/proofs/dissertation-examples/clc-stc-app-view.lisp
books/projects/x86isa/proofs/factorial/fact-inductive-assertions.lisp
books/projects/x86isa/proofs/factorial/fact-wormhole-abstraction.lisp
books/projects/x86isa/proofs/popcount/popcount-general.lisp
books/projects/x86isa/proofs/popcount/popcount.lisp
books/projects/x86isa/proofs/powOfTwo/powOfTwo.lisp
books/projects/x86isa/proofs/wordCount/wc.lisp

The app-view proofs now include the app-view/top proof-utilities book, which is the official book to include for such proofs.

[X86ISA] Standardize includes of proofs.

---

books/kestrel/x86/support-x86.lisp
books/projects/x86isa/proofs/utilities/general-memory-utils.lisp

This is subsumed by x86p-xw, which is much more general.  That rule is:
(defthm x86p-xw
(implies (x86p x86)
(x86p (xw fld index val x86))))
My only hesitation in removing x86p-!rip-when-val-is-canonical-address-p is that it has a force on the x86p hyp (so x86p-xw may not be strictly better), but the forcing doesn't seem to be needed anywhere.

[X86ISA] Remove subsumed rule.

---

books/projects/x86isa/machine/state.lisp

These are already introduced by defrstobj.  Excluding them uses the new :gen-rewrite option to defthm-signed-byte-p and defthm-unsigned-byte-p.

[x86isa] Exclude duplicate rules.

---

books/centaur/misc/tarjan.lisp
books/std/basic/arith-equivs.lisp

Remove nfix-gt-0 as it is the same as the rule nfix-positive-to-non-zp in the same file.

[Std/basic] Remove duplicate rule.

---

books/workshops/2002/cowles-flat/support/flat.acl2

This lets me get the FLAT package by loading flat.acl2, without causing certification to be attempted.  The build system no-longer requires a .acl2 file to include a certify-book command.

[cowles-flat] Remove legacy certify-book command.

---

books/kestrel/x86/support-x86.lisp
books/projects/x86isa/proofs/utilities/app-view/environment-utils.lisp
books/projects/x86isa/proofs/utilities/app-view/top.lisp
books/projects/x86isa/proofs/utilities/app-view/user-level-memory-utils.lisp
books/projects/x86isa/proofs/utilities/basics.lisp
books/projects/x86isa/proofs/utilities/general-memory-utils.lisp
books/projects/x86isa/proofs/utilities/row-wow-thms.lisp
books/projects/x86isa/proofs/utilities/sys-view/marking-view-top.lisp
books/projects/x86isa/proofs/utilities/sys-view/marking-view-utils.lisp
books/projects/x86isa/proofs/utilities/sys-view/non-marking-view-top.lisp
books/projects/x86isa/proofs/utilities/sys-view/physical-memory-utils.lisp

Most of these books don't need to include all the instructions.  I did ensure that the top.lisp books still include everything that they did before.

[X86ISA] Reduce dependencies of proof utils.

---

books/projects/x86isa/machine/catalogue-data.lisp
books/projects/x86isa/machine/inst-listing.lisp
books/projects/x86isa/machine/xedscan.py

I generated basic opcode map entries for the x87 instructions from the XED datafile xed-isa.txt, just scanning it with a python script. This should be sufficient for matching the instructions to their opcode/mod/reg/rm combinations. I didn't try to generate argument entries -- I think we need some new types of entries for that. I also didn't read the exceptions from xed, just generated them with exceptions common to x87 instructions.
Note the SDM is pretty confusing in how it talks about X87 operations. They're not listed in the regular opcode maps, instead they have their own sub-tables (volume 2, appendix A-5). But for all that they are really just opcodes qualified by some extra fields of the mod/rm, which our opcode maps are already able to handle.

x86isa: Update opcode maps to include X87 instructions

---

books/projects/x86isa/utils/basic-structs.lisp
books/projects/x86isa/utils/fp-structures.lisp
books/projects/x86isa/utils/paging-structures.lisp
books/projects/x86isa/utils/segmentation-structures.lisp
books/projects/x86isa/utils/structures.lisp

Each call to defbitstruct locally includes some helper books.  To avoid doing those includes over and over, we do them (locally) at the start of each book that calls defbitstruct repeatedly.
This saves about 14 seconds of the 60 seconds needed for this directory, on a very fast machine.

[X86ISA] Speed up bitstruct proofs.

---

books/projects/x86isa/tools/execution/asmtest/.gitignore
books/projects/x86isa/tools/execution/asmtest/Makefile
books/projects/x86isa/tools/execution/asmtest/asmtest.lisp
books/projects/x86isa/tools/execution/asmtest/check-test.lsp
books/projects/x86isa/tools/execution/asmtest/get-results.sh
books/projects/x86isa/tools/execution/asmtest/run-tests.sh
books/projects/x86isa/tools/execution/asmtest/snippet_table.py
books/projects/x86isa/tools/execution/asmtest/testgen/.gitignore
books/projects/x86isa/tools/execution/asmtest/testgen/Makefile
books/projects/x86isa/tools/execution/asmtest/testgen/testgen.c
books/projects/x86isa/tools/execution/asmtest/testgen/unsupported.h

`testgen` uses XED to iterate over x86 instructions and generate tests
for them. It has some restrictions on instructions it supports. The big
ones are it only works with instructions that operate on flags, gprs,
xmm registers, and immediates. Beyond introducing `testgen`, this also
introduces some scripts to make it easy to run all snippets with random
inputs.
At the moment there are a few issues:
- XED errors when trying to encode some instructions. I don't know why
exactly that is.
- `asmtest` crashes with various errors when running some tests.
- Some instructions fail tests because some flags are undefined. We
handle undefined flags correctly but flags which are undefined
only sometimes can't easily be dealt with in an automated fashion.
That being said, these issues are handled …

x86isa: Introduce `testgen` a test generator for asmtest

---

books/std/util/def-bound-theorems-tests.lisp
books/std/util/def-bound-theorems.lisp

When :bound is 1, have it generate a stronger :type-prescription rule (that the value is a bit, not just a natural).
This is used quite a bit in the x86isa model.
To see the main change, just look at the first commit.

Improve defthm-unsigned-byte-p.

---

books/kestrel/x86/rflags-spec-sub.lisp
books/kestrel/x86/rflags.lisp
books/kestrel/x86/rflags2.lisp
books/projects/x86isa/machine/instructions/add-spec.lisp
books/projects/x86isa/machine/instructions/and-spec.lisp
books/projects/x86isa/machine/instructions/or-spec.lisp
books/projects/x86isa/machine/instructions/rotates-spec.lisp
books/projects/x86isa/machine/instructions/shifts-spec.lisp
books/projects/x86isa/machine/instructions/sub-spec.lisp
books/projects/x86isa/machine/instructions/xor-spec.lisp
books/projects/x86isa/machine/paging.lisp
books/projects/x86isa/machine/register-readers-and-writers.lisp
books/projects/x86isa/machine/rflags-spec.lisp

Compensate by adding some includes in less fundamental books and tweaking a few Kestrel books.

Remove unnecessay inclusion of application-level-memory book

---

books/projects/x86isa/machine/linear-memory.lisp
books/projects/x86isa/machine/top-level-memory.lisp

This is enabled by preventing xr-las-to-pas from being local to its encapsulate.

[X86ISA] Generalize some rules by commenting out hyps.

---

books/projects/x86isa/machine/linear-memory.lisp

Las-to-pas returns a single flag, so use FLG rather than FLGS to represent it.

[X86ISA] Clarify code.

---

books/centaur/fty/database.lisp

A guard for the world parameter had to be added.

[FTY] Put a function in guard-verified logic mode.

---

books/projects/x86isa/machine/paging.lisp

I tried to follow existing conventions used by the model.
Later, I hope to speed up some proofs involving la-to-pa by keeping it disabled.

[X86ISA] Add :returns for la-to-pa and 2 rules about it.

---

books/projects/x86isa/machine/linear-memory.lisp
books/projects/x86isa/proofs/utilities/sys-view/marking-view-top.lisp
books/projects/x86isa/proofs/zeroCopy/marking-view/zeroCopy.lisp

Remove some make-events that generate dozens of special cases of general rules (each specialized rule talking about a single field of the x86 state).  Instead, just use a general rule in each case.  There are some comments indicating that the specialized rules are faster, but I believe that is incorrect.  The dozens of specialized rules are hung on common functions like mv-nth and xr and will cause a lot of wasted time trying and failing to match.  The general rules have hyps that should either succeed or fail quickly.  Indeed, this change seems to reliably speed up the big zeroCopy-part-2 proof by about 85 seconds (from ~820 seconds to ~735 seconds).

[X86ISA] Replace many specialized rules with general rules.

---

books/projects/x86isa/machine/guard-helpers.lisp
books/projects/x86isa/proofs/codewalker-examples/factorial.lisp
books/projects/x86isa/proofs/dataCopy/init.lisp
books/projects/x86isa/proofs/utilities/sys-view/gl-lemmas.lisp
books/projects/x86isa/utils/utilities.lisp

Include it only where needed, so that including the model doesn't bring it in.

[X86ISA] Reduce includes of defthm-using-gl.

---

books/kestrel/axe/x86/rule-lists.lisp
books/projects/x86isa/machine/linear-memory.lisp
books/projects/x86isa/proofs/zeroCopy/marking-view/zeroCopy-part-2.lisp

As usual, I tried to follow existing conventions in the model (e.g., for names and forms of rules).
Also removed a couple of hyps.  Also updated some Kestrel material (lists of rules for Axe to use).

[x86] Replace many more special case rules with general rules.

---

books/acl2s/aspf/simple-tcp-service/.gitignore
books/acl2s/aspf/simple-tcp-service/LICENSE
books/acl2s/aspf/simple-tcp-service/README.md
books/acl2s/aspf/simple-tcp-service/examples/basic-json/README.md
books/acl2s/aspf/simple-tcp-service/examples/basic-json/example.lsp
books/acl2s/aspf/simple-tcp-service/examples/basic-json/try-load-quicklisp.lsp
books/acl2s/aspf/simple-tcp-service/examples/basic-server/.gitignore
books/acl2s/aspf/simple-tcp-service/examples/basic-server/Makefile
books/acl2s/aspf/simple-tcp-service/examples/basic-server/README.md
books/acl2s/aspf/simple-tcp-service/examples/basic-server/build.lsp
books/acl2s/aspf/simple-tcp-service/examples/basic-server/demo.py
books/acl2s/aspf/simple-tcp-service/examples/basic-server/handler.lsp
books/acl2s/aspf/simple-tcp-service/examples/basic-server/try-load-quicklisp.lsp
books/acl2s/aspf/simple-tcp-service/python-interface/.gitignore
books/acl2s/aspf/simple-tcp-service/python-interface/README.md
books/acl2s/aspf/simple-tcp-service/python-interface/acl2s.py
books/acl2s/aspf/simple-tcp-service/simple-tcp-service.asd
books/acl2s/aspf/simple-tcp-service/src/json/json.lisp
books/acl2s/aspf/simple-tcp-service/src/json/package.lisp
books/acl2s/aspf/simple-tcp-service/src/tcp-worker/package.lisp
books/acl2s/aspf/simple-tcp-service/src/tcp-worker/string-trim.lisp
books/acl2s/aspf/simple-tcp-service/src/tcp-worker/tcp-server.lisp

Add the simple-tcp-service library to the ACL2s books. This library allows one to set up a service in raw Lisp with endpoints that can be interacted with using a basic Python library.

[acl2s] Add simple-tcp-service library

---

books/centaur/fty/top.lisp

The existing XDOC page for `defoption` is only a placeholder with a "TODO" message.
The PR adds a basic description of `defoption` and demonstrates its syntax and keyward options.

Add XDOC for `fty::defoption`

---

books/kestrel/x86/floats.lisp
books/projects/x86isa/machine/instructions/fp/arith-spec.lisp
books/projects/x86isa/machine/instructions/fp/cmp-spec.lisp
books/projects/x86isa/machine/instructions/fp/cvt-spec.lisp
books/projects/x86isa/machine/register-readers-and-writers.lisp
books/projects/x86isa/utils/fp-structures.lisp

These backchain from unsigned-byte-p to the specific bitstruct predicates.  So they can introduce reasoning about the bitstructs out of nowhere in unrelated contexts.  Thus, I think we don't want them enabled by default.  I re-enabled them only where needed.
Example of problematic rule:
(DEFTHM UNSIGNED-BYTE-P-WHEN-MXCSRBITS-P
(IMPLIES (MXCSRBITS-P X)
(UNSIGNED-BYTE-P 32 X)))
If people approve this change, I can make similar changes for other bitstructs.  Even better would be to have defbitstruct (optionally) disable these rules.

[X86ISA] Disable some rules generated by defbitstruct.

---

books/projects/x86isa/machine/instructions/segmentation.lisp

[X86ISA] Avoid including guard-helpers book.

---

books/projects/x86isa/machine/linear-memory.lisp

Previously its guard included both (canonical-address-p lin-addr) and (signed-byte 48 lin-addr), which mean the same thing.  I added :split-types so that the signed-byte-p claim is used only as a :type, not in the guard.  I then had to add (member-eq r-x '(:r :x)) to the guard so that it implies the :type.
If people approve this PR, I can make similar changes to other functions.  A goal is to be able to keep canonical-address-p disabled more (e.g., to speed up some slow proofs involving linear-memory).

[x86isa] Improve guard of rml08.

---

books/projects/x86isa/machine/guard-helpers.lisp
books/projects/x86isa/machine/linear-memory.lisp

Simplify hints and remove dependence on guard-helpers book.  Comment out unneeded stuff in guard-helpers book.
Now linear-memory.lisp doesn't depend on GL (except gl/portcullis).

[X86ISA] Improve guard proofs in linear-memory.lisp.

---

books/projects/x86isa/machine/linear-memory.lisp

Use :split-types (analogous to the recent change to rml08).

[X86ISA] Avoid redundancy in more guards.

---

books/centaur/vl/loader/parser/seq.lisp
books/centaur/vl2014/loader/parser/seq.lisp
books/misc/seq.lisp

The Linter revealed that the calls to ER were missing the context arguments (so ER treated the format string as the context and the first value as the format 'string').  The calls of ER are in generated code, and it might be best to use the surrounding function name as the ctx.  However, I didn't see a nice, general way to access that, so I just used 'seq-process-bind as the context argument.
BTW, there seem to be 3 copies of the seq.lisp book.  It would be nice to have only one.  Two of the copies (in vl and vl2014) are identical except for the package and copyright years.

[vl/vl2014/misc] Fix error messages in SEQ books.

---

books/projects/x86isa/linux/doc.lisp
books/projects/x86isa/machine/state.lisp

Just realized that I never sent a PR to merge this old change

x86isa Remove include-book from docs on changing memory model

---

books/projects/x86isa/machine/linear-memory.lisp

Perhaps the rules should also be renamed, since their names mention 'app-view' but those hyps are not needed.

[X86ISA] Comment out some unneeded hyps.

---

books/std/util/define-sk.lisp

Have guard proof failures show on the screen.

[Std/util] Improve `define-sk`.

---

books/projects/x86isa/doc.lisp
books/projects/x86isa/machine/x86.lisp

So I can get machine/x86 without having to include those docs.

[X86ISA] Move includes of docs.

---

books/std/util/deflist-base.lisp

Avoid putting in :guard-debug nil, since nil is the default.
Makes definitions a bit simpler and makes the Linter happy.  :-)

[Std/util] Tweak deflist.

---

books/centaur/fty/fty-sum-casemacro.lisp

The `T-case` macro associated to a sum fixtype `T` generates a binding of `x.kind`, where `x` is the argument of the `T-case`. If the sum type consists of one summand, the `x.kind` ends up being unused, which causes an error in normal conditions. This commit makes that variable `x.kind` ignorable, thus avoiding the error for the case of a one-summand sum type.
This commit also auto-removes some trailing whitespace.

[FTY] Make the auto-bound kind variable ignorable.

---

books/kestrel/fty/defomap-tests.lisp
books/kestrel/fty/defset-tests.lisp
books/kestrel/fty/fty-omap.lisp
books/kestrel/fty/fty-set.lisp

Adds explicit induction hints such that `defset` and `defomap` will work with `(set-induction-depth-limit 0)`.
Also removes redundant fix-when-recognizer theorems (already covered by the returns specifiers).

[FTY] Make `defset` and `defomap` more robust

---

books/xdoc/tests/defsection-tests.lisp
books/xdoc/top.lisp

This avoids the issue of `defsection` and forms which generates `defsection`s (like `define`) from failing silently on bad `:short` and `:long` forms.
For instance errors in the application of xdoc constructors in a `define` currently cause a silent failure. After this change, the failure is printed like normal to the comment window.

[XDOC] Don't suppress error messages in `defsection`

---

books/projects/x86isa/machine/evex-opcodes-dispatch.lisp

These cause define to create an encapsulate, which seems to be causing slowdown on some Lisps.

[X86ISA] Drop unneeded uses of :ignore-ok.

---

books/centaur/fty/fty-list.lisp

At least a proof generated by `fty::deflist` implicitly assumes that `nfix` is enabled in order to work: `fty::deflist` fails at that theorem if `nfix` is not enabled. This commit enables `nfix` in that theorem.

[FTY] Make a generated proof more robust.

---

books/projects/x86isa/machine/evex-opcodes-dispatch.lisp
books/projects/x86isa/machine/vex-opcodes-dispatch.lisp

By only including the needed instructions, these books can be certified earlier (evex-opcodes-dispatch is very slow on some Lisps).
A few other include-books also were unnecessary and so have been commented out.

[X86ISA] Reduce includes of vex/evex dispatch books.

---

books/kestrel/c/syntax/tests/validator.lisp
books/kestrel/c/syntax/validation-information.lisp
books/kestrel/c/syntax/validator.lisp
books/kestrel/c/transformation/splitgso.lisp

The interpretation of `(type-struct (ident "foo"))` is the collective type of all struct types with tag `"foo"`. To be perfectly precise, one would need to distinguish structs types further based on the scope of their declaration (and of course information about the members).
Similarly, `(type-struct nil)` is the collective type of all tagless structs. To be more precise in this case, we'd need to also represent the location of its declaration, as each declaration of a tagless structure type denotes a new type [C17:6.7.2.3/5].
The validator has been updated to recognize different structure types and check for compatibility as appropriate. Specifically, this involved changes to validation of simple assignments, initializers, and type specifiers.

[C$] Add optional tag to struct types

---

books/projects/rac/src/program/parser/ast/statements.cpp
books/projects/rac/tests/yaml_test/program_structure/basics.yml
books/projects/rac/tests/yaml_test/program_structure/imul-pc.cpp.ref.pc
books/projects/rac/tests/yaml_test/program_structure/mulvar-pc.cpp
books/projects/rac/tests/yaml_test/program_structure/mulvar-pc.cpp.ref.pc

* In a tie expression, the first variable used to be printed twice
* In a MulVarDec, instead of printing the typedef name, it was showing the original type.
Thanks David for the report.

[RAC] Fix pseudo code bug

---

books/projects/python/embedding/types.lisp

Adjust the weights of the floating point enumerator so that they sum to 100, for easier interpretability of the weights as percentages. 
This embedding was introduced as part of a paper submission to the ACL2 2025 conference (see: https://github.com/acl2/acl2/tree/master/books/workshops/2025).

Python embedding: adjust weights of float enumerator to sum to 100

---

books/centaur/glmc/.gitignore

I occasionally see this generated file in my local git repositories (under `books/centaur/glmc/`). I assume it should never be checked in to version control and therefore it is best to add to the local `.gitignore`.

Add `abc.history` to gitignore

---

books/kestrel/fty/database.lisp
books/kestrel/fty/deffold-map-doc.lisp
books/kestrel/fty/deffold-map-tests.lisp
books/kestrel/fty/deffold-map.lisp
books/kestrel/fty/deffold-reduce-doc.lisp
books/kestrel/fty/fold.lisp
books/kestrel/fty/top.lisp
books/std/omaps/core.lisp

This is a fold for FTY types based on `deffold-reduce`. Unlike `deffold-reduce`, it does not take a `:combine` or `:default` flag, since it is a mapping fold. Instead, each case of the map is the relevant constructor applied to the recursively mapped fields.
This PR also includes some minor changes to `deffold-reduce` (a couple typos and a missing include) and to `omap`s (strengthening the `:type-prescription` rule).

[FTY] Add `deffold-map`

---

books/workshops/references/README.org
books/workshops/references/workshops.bib
books/workshops/references/workshops.tex

Update the workshop BibTeX references to cover the 2018, 2020, 2022 and 2023 workshops.

Update BibTeX workshop references to cover 2018-2023 workshops

---

books/ihs/logops-lemmas.lisp

These are useful when `ifix` is kept disabled, which is perhaps uncommon, but avoids, like other built-ins, unnecessary case splits.

[IHS] Add two fixing theorems.

---

books/GNUmakefile
books/build/doc.lisp
books/build/features.sh
books/kestrel/c/syntax/input-files-doc.lisp
books/kestrel/c/syntax/input-files.lisp
books/kestrel/c/syntax/preprocess-file.lisp
books/kestrel/c/syntax/tests/input-files.lisp
books/kestrel/c/syntax/tests/preprocess-file.lisp

Similarly, changes the Makefile flag `OS_HAS_CPP` to `OS_HAS_GCC_C17`.
Updates the feature detection to search for `gcc` instead of `cpp`, and requires that `"-std=c17"` is supported.

Change the `cert_param` `uses-cpp` to `uses-gcc-c17`

---

books/projects/rac/examples/imul/imul.cpp
books/projects/rac/src/program/parser/ast/expressions.cpp
books/projects/rac/src/program/parser/ast/types.cpp
books/projects/rac/src/program/process/typing.cpp
books/projects/rac/src/program/process/typing.h
books/projects/rac/tests/testsuite.py
books/projects/rac/tests/yaml_test/arithmetics/arithmetics.yml
books/projects/rac/tests/yaml_test/arithmetics/int-arith-invalid.cpp
books/projects/rac/tests/yaml_test/data_types/annonymous-struct-in-array.cpp
books/projects/rac/tests/yaml_test/data_types/array-in-struct-with-default-value.cpp
books/projects/rac/tests/yaml_test/data_types/basic.yml
books/projects/rac/tests/yaml_test/data_types/const-arrays-2.cpp
books/projects/rac/tests/yaml_test/data_types/fast-arrays-mixed.cpp
books/projects/rac/tests/yaml_test/data_types/fast-arrays-non-const.cpp
books/projects/rac/tests/yaml_test/data_types/fast-arrays-non-const.ref.stderr
books/projects/rac/tests/yaml_test/data_types/fast-arrays.cpp
books/projects/rac/tests/yaml_test/data_types/global-constant.cpp
books/projects/rac/tests/yaml_test/data_types/initializer-list-ac-types.cpp
books/projects/rac/tests/yaml_test/data_types/initializer-list-mismatch-types.cpp
books/projects/rac/tests/yaml_test/data_types/initializer-list.cpp
books/projects/rac/tests/yaml_test/data_types/std-array-initializer-diff-size.cpp
books/projects/rac/tests/yaml_test/data_types/std-array-initializer-incomplete.cpp
books/projects/rac/tests/yaml_test/data_types/std-array.cpp
books/projects/rac/tests/yaml_test/data_types/struct-default-values-incompatible.cpp
books/projects/rac/tests/yaml_test/data_types/struct-default-values-incompatible.ref.stderr
books/projects/rac/tests/yaml_test/data_types/typedef-array.cpp
books/projects/rac/tests/yaml_test/program_structure/imul-pc.cpp.ref.pc
books/projects/rac/tests/yaml_test/program_structure/variable-decl.cpp

std::arrays should be able to be initialized using {{}} and {} (braces elision). Before, std::arrays were only initialized using {} but for some other (older) compilers, the full syntax must be supported. Brace elision is not implemented, "{}" now reports an error

[RAC] Change array inialization

---

books/xdoc/fancy/xslt.js
books/xdoc/parse-xml.lisp
books/xdoc/prepare-topic.lisp
books/xdoc/topics.lisp

This simplifies and clarifies the XML entity machinery used by xdoc, to support more easily adding additional entities, such as accented letters in names of paper authors (in future commits).
Now there are fewer things that must be kept in sync (4 things instead of 6).
I confirmed that the generated alist constants are the same (except one is reversed, like the others, because it is now generated, like the others -- and it has no duplicate keys).
I confirmed that the big string constant, *xml-entity-stuff*, is the same except for whitespace, which is now more regular since that string is now generated.
I checked the web manual topic "entities" to ensure that things still rendered correctly.  I also checked the output of :doc entities at the ACL2 prompt.

Xdoc entities

---

books/projects/rac/src/program/parser/ast/types.h

When if a two expression's types are compatible, some functions use canBeImplitlyCast (for example when checking a function call). For array (and others types), this function used to always return false instead of returning true when it was the same type.

[RAC] Fix typing array bug

---

books/kestrel/axe/x86/tests/ndsu/run-tests-sub.lisp

Removed ; cert_param: (ttags :all) from this test file. After further review, the book and its dependencies do not use any trust tags, so this parameter is not required.

Remove unnecessary (ttags :all) from run-tests-sub.lisp

---

books/doc/top-topic.lisp
books/oslib/date-logic.lisp
books/oslib/date-raw.lsp
books/oslib/date.lisp

The `oslib::date` function previously called the Common Lisp `get-decoded-time` function in its raw Lisp definition. This change adds an `oslib::get-decoded-time$` function as a wrapper around this Common Lisp function and modifies `oslib::date` to call the ACL2 `get-decoded-time$` function. This minimizes the amount of work done in raw Lisp and exposes more information about the decoded time to ACL2.
Note that the return theorems for `oslib::get-decoded-time$` are rather strong, but I believe they are justified by the spec. Relevant links:
- https://www.lispworks.com/documentation/HyperSpec/Body/f_get_un.htm#get-decoded-time
- https://www.lispworks.com/documentation/HyperSpec/Body/25_ada.htm
- https://www.lispworks.com/documentation/HyperSpec/Body/26_glo_t.htm#time_zone
The return …

[oslib] Introduce `get-decoded-time$` and refactor `date`

---

books/kestrel/c/syntax/grammar.abnf
books/kestrel/c/syntax/parser.lisp
books/kestrel/c/syntax/tests/.gitattributes
books/kestrel/c/syntax/tests/parser.lisp

This adds preprocessing directives as a new lexeme. It is lexed very similarly to line comments, except that when we reach a `#` character, we also look backward to check that any preceding characters on the line are whitespace [C17:6.10/2]. This condition is checked by the new `only-whitespace-backward-through-line` function. This function does not "unread" characters, it simply looks back through the (read portion of the) chars array.

[C$] Extend lexer to handle preprocessing directives

---

books/xdoc/fancy/common.scss
books/xdoc/fancy/desktop.css
books/xdoc/fancy/mobile.css
books/xdoc/fancy/xdata2sql.pl
books/xdoc/fancy/xdataget.pl
books/xdoc/fancy/xdoc.js

This PR improves the web manual search by using sqlite FTS5 to quickly search topics/shorts/longs on the server.
Note that the `desktop.css` and `mobile.css` files are generated from the SCSS files. It looks like there are more changes than there actually are because the SCSS->CSS generator I used didn't match the style of the originals.
The sqlite database has been modified to include more data (topic names and shorts). It also builds an FTS table to allow for FTS5 searches. This increases the size of the database from 310M to 430M.
Search results are annotated with their "score", which is used to rank them. The calculation is fairly ad-hoc. It starts with the FTS BM25 score, but then we adjust it to overweight topics with exact results in the topic names and such.
You can preview these …

Implement server-side seaching for the web manual

---

books/kestrel/c/syntax/tests/validator.lisp
books/kestrel/c/syntax/validator.lisp

This weakens the `type-scalarp` check to only apply when we have a non-`void` type name. Also fixes presumed typo in the function-to-pointer conversion of a type (it seems it should apply to the type of the operand, not the type name).

[C$] Fix validation of casts to `void`

---

books/kestrel/c/syntax/tests/validator.lisp
books/kestrel/c/syntax/types.lisp
books/kestrel/c/syntax/validator.lisp

Many theorems of the name `<function>-when-type-kind-syntaxp` are added to `types.lisp`. These are added to functions which are decided solely by the `type-kind` value of the argument. These theorems just expand the function definition when there is a hypothesis `(equal (type-kind type) kind)` where `kind` is a constant.
I introduce `type-composite` to explicitly construct composite types. Currently, this function is not doing very much interesting, just biasing the "merging" toward more specific (i.e. non-unknown) types. The interesting behavior for composite types has to do with array size and function parameter type lists [C17:6.2.7/3], which we are not modelling in the approximate type system.

[C$] Add type parameter to pointer types

---

books/system/extend-pathname.lisp

This localizes an `in-theory` event in `books/system/extend-pathname.lisp` (this books just brings `extend-pathname` into logic mode). Now, the book can be included without affecting the theory.
This also removes a call of `verify-termination` on a function which is already logic mode and guard verified.

[system] Localize in-theory event

---

books/projects/x86isa/doc.lisp
books/projects/x86isa/linux/doc.lisp

These doc changes are in response to a discussion with Warren about the build instructions being confusing, especially the description of the `X86ISA_EXEC` option, now that we can run a kernel (and thus, handle syscalls) in the model. These changes clarify the build instructions to hopefully reduce ambiguity about the `X86ISA_EXEC` option. The primary change is the addition of a paragraph at the top of the build instructions topic which states that if you're running a kernel in the model, like Linux, the value of `X86ISA_EXEC` is irrelevant along with a link to the doc topic on `app-view`.
The references to full execution and execution of syscall instructions have been clarified to mention that this only applies in app-view with links to the app-view topic.
Additionally, the paths where …

Clarify x86isa model build instructions in context of Linux boot

---

books/interface/emacs/acl2-indent.el

This addresses an issue observed when attempting to do `M-x customize-variable`. This seemed to be calling indent-sexp with zero arguments, while it is defined in `acl2-indent.el` with 1 argument. Making the argument optional fixes the issue.

[interface] Make elisp function argument optional

---

books/kestrel/c/syntax/abstract-syntax-trees.lisp
books/kestrel/c/transformation/tests/call-graph/call-graph.lisp

This largely changes the layouts to `:fulltree`, which will be more memory-efficient than the default `:alist` layout. Identifiers use the `:list` layout so that they are non-`nil`, and so we can therefore create an `ident-option`.

[c$] Change FTY layouts for ASTs
