acl2/acl2

books/arithmetic-3/README, books/arithmetic-5/README, books/tools/defsum.lisp, books/workshops/2006/swords-cook/lcsoundness/defsum.lisp
Maybe these were added by mistake at some point...?
=> Remove ``'' from code fragments

books/projects/quadratic-reciprocity/euclid.lisp
Write guards for quadratic-reciprocity/euclid.
Functions: divide, least-divisor, primep, g-c-d,... .
=> Write guards for quadratic-reciprocity/euclid

books/projects/x86isa/machine/instructions-spec/x86-fp.lisp
Added RTL9 library reference to books/projects/x86isa/machine/instructions-spec/x86-fp.lisp.
=> Added RTL9 library reference to books/projects/x86isa/machine/instructions-spec/x86-fp.lisp

books/rtl/rel11/support/basic.lisp
Making another pull request so it can go through the build server process via the testing branch.
=> Nadezhin's improvements to rtl/rel11/support/basic.lisp

books/centaur/vl/parsetree.lisp
@jaredcdavis or @solswords Please confirm that decreasing the timestamp isn't going to cause weird bugs for you and merge.
=> Fixing typo in VL syntax version datestamp

books/rtl/rel11/support/basic.lisp
ACL2(r) certifies `rtl/rel11/support/basic.lisp` and radix-aware functions in this book.
=> ACL2(r) certifies rtl/rel11/support/basic.lisp and radix-aware functions in this book.

books/centaur/sv/svtv/process.lisp
=> Reversing order of SVTV autoins.

books/centaur/esim/tutorial/counter.v
Thanks to Yan Peng for finding this.
=> Fix warning in ESIM tutorial

books/centaur/sv/svtv/process.lisp
@solswords  Can you please confirm that these are typos and merge?
=> Fixing a typo in SVTV

books/rtl/rel11/rel9-rtl-pkg/support/lib1/bvecp-helpers.lisp
=> Remove unnoticed (include "rtlarr")

books/workshops/2015/chau-kaufmann-hunt/support/fourier-coefficients-2.lisp, books/workshops/2015/chau-kaufmann-hunt/support/fourier-coefficients.lisp, books/workshops/2015/chau-kaufmann-hunt/support/fourier-inner-product.lisp, books/workshops/2015/chau-kaufmann-hunt/support/fourier-sums.lisp
Added fourier-inner-product.lisp file to Fourier series formalization.
=> Added fourier-inner-product.lisp file to Fourier series formalization.

books/workshops/2015/peng-greenstreet/support/examples/DPLL/DPLL_proof.lisp, books/workshops/2015/peng-greenstreet/support/examples/DPLL/DPLL_proof_floor.lisp, books/workshops/2015/peng-greenstreet/support/examples/examples.lisp, books/workshops/2015/peng-greenstreet/support/examples/other-examples.lisp
Remove add-include-book-dir to use relative paths. Hope this works.
=> Remove add-include-book-dir to use relative paths.

books/workshops/2015/peng-greenstreet/support/examples/DPLL/cert.acl2, books/workshops/2015/peng-greenstreet/support/examples/cert.acl2
=> Adding two cert.acl2 files.

books/centaur/sv/cosims/Makefile
Hi @solswords or @jaredcdavis ,
Could you please look at these changes and approve/comment?  I won't accept the pull request until after the "for" cosim tests are added, but I wanted to get your feedback before I was ready to be finished with this.
Thanks,
David
=> Added 'passing' make target to cosims

books/workshops/2015/hardin/support/occurrences-llvm.lisp
Slightly tuned hypotheses for occurrences-llvm.lisp
=> Tuned the hypotheses for occurrences-llvm.lisp

books/std/basic/defs.lisp
=> Fix typo in comment.

books/build/make_cert_help.pl, books/rtl/rel11/lib/excps.lisp, books/rtl/rel11/support/excps.lisp
Submitting against the testing branch.
=> Fixed two bugs in rtl/rel11/lib/excps

books/centaur/sv/svtv/process.lisp
@jaredcdavis or @solswords Could you please have a look and verify?
=> Added define-macros flag to defsvtv

books/kestrel/general/testing-tests.lisp, books/kestrel/general/testing.lisp
This is a (LOCAL ...) of MUST-FAIL, useful to overcome the issue discussed in
the caveat in the documentation of MUST-FAIL.
=> New macro MUST-FAIL$.

books/projects/masc/Makefile, books/projects/masc/examples/Makefile, books/projects/masc/examples/hello.cpp, books/projects/masc/examples/imul/imul.cpp, books/projects/masc/examples/imul/proof.lisp, books/projects/masc/include/masc.h, books/projects/masc/lisp/translate.lisp, books/projects/masc/src/Makefile, books/projects/masc/src/masc-skel, books/projects/masc/src/output.c, books/projects/masc/src/parser.h, books/projects/masc/src/parser.l, books/projects/masc/src/parser.y
=> Updated books/projects/masc

books/projects/farray/LICENSE, books/projects/farray/acl2-customization.lsp, books/projects/farray/cert.acl2, books/projects/farray/farray-resize.lisp, books/projects/farray/farray.lisp, books/projects/farray/package.lsp, books/projects/farray/portcullis.acl2, books/projects/farray/portcullis.lisp
Adding farray to projects, more books to follow
=> Adding farray to projects

books/projects/x86isa/machine/instructions/x86-jump-and-loop-instructions.lisp, books/projects/x86isa/machine/instructions/x86-segmentation-instructions.lisp, books/projects/x86isa/machine/x86-register-readers-and-writers.lisp, books/projects/x86isa/machine/x86-top-level-memory.lisp, books/projects/x86isa/proofs/popcount/popcount.lisp, books/projects/x86isa/proofs/utilities/system-level-mode/marking-mode-utils.lisp
-- Added Dmitry Nadezhin's contribution: functions rm/wm128 are now
logically equal to rb/wb, respectively.
-- Replaced popcount program in proofs/popcount with a more
interesting version.
=> x86isa: Misc. changes

books/centaur/getopt/top.lisp, books/std/util/da-base.lisp, books/std/util/defaggregate.lisp, books/std/util/defsum.lisp, books/std/util/tests/defaggregate.lisp
Here is a proposal to add a :PRED option to DEFAGGREGATE. While I suspect agreement on the usefulness of this addition, I'm not sure if the proposed code changes are the preferred way to implement the addition. Please feel free to reject the pull request if that's the case.
=> A proposal to add a :PRED option to DEFAGGREGATE.

books/centaur/fty/deftypes.lisp
fty::defprod allows type of field to be a macro.
However, defprod is slow in this case because
it can't find user-supplied fix-pred and pred-of-fix theorems.
Often this macro is expanded to (unsinged-byte-p NNN x)
where NNN is a natural constant.
THis commit modifies flextypes-collect-fix/pred-pairs-aux so that it can handle
this particular case.
General solution for any macro is difficult for me now.
=> Make fty::defprod with (unsigned-byte-p NNN x) fields faster.

books/projects/x86isa/tools/execution/exec-loaders/mach-o/mach-o-reader.lisp
=> Fix some error messages and comments in x86 model.

books/centaur/sv/cosims/case_wilds/spec.sv, books/centaur/sv/cosims/run.lsp
Add Verilog cosims test on wildcards in case statements
=> Icarus verilog

books/acl2s/demos/alloy-comparison.lisp, books/acl2s/demos/alloy-support.lisp, books/acl2s/demos/cert.acl2, books/acl2s/demos/diss-examples.lisp, books/acl2s/demos/dsp-defthms.lisp, books/acl2s/demos/dsp-defuns.lisp, books/acl2s/demos/dsp-fixer-rules.lisp, books/acl2s/demos/dsp-preservation-rules.lisp, books/acl2s/demos/dsp-type-and-fixer-defuns.lisp, books/acl2s/demos/dsp.lisp, books/acl2s/demos/pipeline-22Sep2015.lisp, books/acl2s/demos/refinement-sfm06-with-hazards-test.lisp, books/acl2s/demos/refinement-sfm06-with-hazards.lisp, books/acl2s/demos/regress-stats.awk
Added case-studies used for experimental evaluation of Cgen.
=> Cgen case-studies

books/acl2s/demos/README, books/acl2s/demos/acl2-customization.lsp, books/acl2s/demos/dsp.lsp
Added a readme file. Added a customization file provided by Matt. Modified the dsp.lsp script to include the flawed conjecture example used in the motivation section of fixers chapter
=> Minor changes to acl2s/demos.

books/centaur/defrstobj/sketch.lsp, books/centaur/fty/bitstruct.lisp, books/centaur/vl/lint/lucid.lisp, books/centaur/vl/transforms/addnames.lisp
I think this should be a pretty safe commit, but running a regression anyway...
=> Fix cert.pl relocation warnings

books/build/cert.pl
Currently, cert.pl looks for the system books in the following
locations, in order, until one succeeds (defaulting to the second
one):
1) the `books` subdirectory of the directory containing the ACL2
executable cert.pl is using
2) the parent directory of the directory where cert.pl itself lies
This commit adds another option in between the two:
1.5) the value of `(@ system-books-dir)` reported by the ACL2
executable when it is run
This is useful if, for example, your ACL2 executable is actually a
script that sets environment variables or does other kinds of setup
before actually calling ACL2 itself, and that script resides in a
totally different location from the actual ACL2 image that it
eventually launches.
This commit also cleans up a couple of comments, and adds an output
warning …
=> Make cert.pl try harder to find the system books

books/std/util/bstar.lisp
This commit generalizes and factors out some of the guts of
patbind-assocs so that they can later be reused to create similar
patbind functions for other (possibly user-defined) alist-backed data
structures.
Suppose you have a datastructure which is backed by an alist but is
designed to be used via accessor and updater functions, which are
analogous to `assoc` and `acons` but do something slightly more
complicated.
Imagine for example an alist representing a polynomial by mapping
monomials to their coefficients, where only non-zero coefficients are
actually stored.  Then you might have
(defun assoc-polynomial (x alist)
(or (assoc x alist)
(cons x 0)))
(defun acons-polynomial (key datum alist)
(if (equal datum 0)
(delete-assoc key alist)
(acons key datum (delete-assoc key alist))))
This …
=> Make patbind-assocs easily generalizable

books/projects/filesystems/file-system-1.lisp, books/projects/filesystems/file-system-2.lisp, books/projects/filesystems/file-system-3.lisp, books/projects/filesystems/file-system-lemmas.lisp
The 4th, which is a work in progress, will be added soon.
=> Add 3 filesystem models

books/projects/async/serial-adder/async-serial-adder.lisp, books/projects/async/serial-adder/de.lisp, books/projects/async/serial-adder/link-joint.lisp, books/projects/async/serial-adder/list-rewrites.lisp, books/projects/async/serial-adder/primp-database.lisp
Some updates on async serial adder proofs.
=> Some updates on async serial adder proofs.

books/misc/records0.lisp
I believe that those comments were slightly out of date, but perhaps @MattKaufmann can check and confirm that.
=> Fix typos in comments.

books/doc/relnotes.lisp, books/std/io/open-channels.lisp, books/xdoc/topics.lisp
I added a couple sentences to the docs about XDOC to address something that I personally found confusing, in the hope that it will help others in the future.
=> Tweak some docs and some docs about docs

books/centaur/fty/top.lisp
Thanks to Matt for the heads-up.  Sorry for the second XDOC-related breakage I've caused in the last couple weeks.  My excuse is that I'm unfortunately unable to test building the full manual since my laptop doesn't have enough memory...
=> Fix XDOC broken link

books/projects/x86isa/machine/instructions/x86-push-and-pop-instructions.lisp, books/projects/x86isa/machine/x86-decoding-and-spec-utils.lisp, books/projects/x86isa/machine/x86.lisp, books/projects/x86isa/utils/records-0.lisp
=> [x86isa] Incorporate misc. changes from Alessandro Coglio

books/centaur/misc/try-gl-concls.lisp, books/tools/try-gl-concls.lisp
Added a little tool called try-gl-concls that uses GL to return all true conclusions from a list of user-provided conclusions.
=> Added try-gl-concls

books/centaur/misc/try-gl-concls.lisp, books/doc/relnotes.lisp, books/doc/top.lisp
Sorry, forgot to do this the first time round...
=> Made a relnotes entry for try-gl-concls

books/xdoc/topics.lisp
Fixing a typo that when trying to print two \\'s, we need to escape them using \\'s too.
=> Fixing typo.

books/centaur/defrstobj/defrstobj.lisp
I'm waiting until leeroy's testing branch builds successfully to merge this.
=> Updating documentation for defrstobj

books/system/doc/render-doc-base.lisp, books/xdoc/preprocess.lisp, books/xdoc/save-fancy.lisp
This change speeds up the manual build (certification of doc/top.lisp) by around 3-5 minutes by adding a semi-ugly hack to xdoc's get-event, which it uses for expanding preprocessor directives like @(def ...) and @(thm ...).  The idea is that before we start, we traverse the world once and collect a fast alist binding every function/theorem/macro name to the event form we'd get from get-event*.  (Previously, each call of get-event would traverse the world linearly, which took a lot of time -- around 90 seconds in save-rendered with doc/top loaded.) This fast alist is generated and bound in a state global at the beginning of the save/render routine.  If it isn't bound, everything works as before, which is important for using :doc/:xdoc from the terminal.
Submitting this as a pull request …
=> Xdoc: Add a hack to preprocessing to make save/render faster.

books/interface/infix/acl2-formatting.lisp, books/interface/infix/infix.lisp, books/interface/infix/latex-init.lisp, books/interface/infix/latex-theory.lisp, books/interface/infix/scribe-init.lisp, books/interface/infix/scribe-theory.lisp
Hi @MattKaufmann ,
If this looks okay to you, could you please merge this?
Thanks,
David
=> Standardize copyright years

books/centaur/fty/fixtype.lisp
The fty::deffixequiv macro produces three theorems, namely fix-thm,
const-thm, and cong-thm.  Of these, const-thm is a syntaxp-conditioned
reversal of fix-thm; while fix-thm rewrites (F (FOO-FIX X)) to (F X)
under the equivalence relation out-equiv, const-thm rewrites (F X)
to (F (FOO-FIX X)) under out-equiv when X is a constant that doesn't
satisfy (FOO-P X).
The ideal way to prove const-thm is to apply fix-thm to
rewrite (F (FOO-FIX X)) to (F X) under out-equiv, but the surrounding
theory when the event is submitted may cause ACL2 to try to prove it
in a different way, possibly failing or taking far longer than it
should to prove such a trivial corollary of fix-thm.
This commit provides an :in-theory hint to the const-thm event so that
it is carried out in a theory that should allow it …
=> Provide hint for deffixequiv const-thm event

books/projects/filesystems/bounded-nat-listp.lisp, books/projects/filesystems/file-system-1.lisp, books/projects/filesystems/file-system-2.lisp, books/projects/filesystems/file-system-3.lisp, books/projects/filesystems/file-system-4.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/find-n-free-blocks.lisp, books/projects/filesystems/flatten-lemmas.lisp, books/projects/filesystems/set-indices.lisp
A new model is added, which features garbage collection.
=> Update filesystem project

books/projects/async/serial-adder/Makefile, books/projects/async/serial-adder/acl2-customization.lsp, books/projects/async/serial-adder/adder.lisp, books/projects/async/serial-adder/alu-spec.lisp, books/projects/async/serial-adder/assoc-eq-value.lisp, books/projects/async/serial-adder/async-serial-adder-control.lisp, books/projects/async/serial-adder/async-serial-adder.lisp, books/projects/async/serial-adder/cert.acl2, books/projects/async/serial-adder/constants.lisp, books/projects/async/serial-adder/control-modules.lisp, books/projects/async/serial-adder/de.lisp, books/projects/async/serial-adder/f-functions.lisp, books/projects/async/serial-adder/fm9001-spec.lisp, books/projects/async/serial-adder/hard-spec.lisp, books/projects/async/serial-adder/link-joint.lisp, books/projects/async/serial-adder/list-rewrites.lisp, books/projects/async/serial-adder/macros.lisp, books/projects/async/serial-adder/memory.lisp, books/projects/async/serial-adder/package.lsp, books/projects/async/serial-adder/portcullis.acl2, books/projects/async/serial-adder/portcullis.lisp, books/projects/async/serial-adder/primitives.lisp, books/projects/async/serial-adder/primp-database.lisp, books/projects/async/serial-adder/store-n.lisp, books/projects/async/serial-adder/unbound.lisp, books/projects/async/serial-adder/utils.lisp, books/projects/async/serial-adder/vector-macros.lisp, books/projects/async/serial-adder/vector-module.lisp
Added a 3-clause BSD license to the files in the serial-adder directory
=> Added a 3-clause BSD license to the files in the serial-adder directory

books/ihs/logops-definitions.lisp, books/projects/filesystems/file-system-2.lisp, books/projects/filesystems/file-system-3.lisp, books/projects/filesystems/file-system-4.lisp, books/projects/filesystems/file-system-5.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/find-n-free-blocks.lisp, books/projects/filesystems/flatten-lemmas.lisp, books/projects/filesystems/set-indices.lisp
Thanks owed to @MattKaufmann for his quick response to my query about testing xdoc changes.
=> Update with model 5

books/projects/x86isa/doc.lisp, books/projects/x86isa/machine/decoding-and-spec-utils.lisp, books/projects/x86isa/machine/instructions/arith-and-logic.lisp, books/projects/x86isa/machine/instructions/bit.lisp, books/projects/x86isa/machine/instructions/conditional.lisp, books/projects/x86isa/machine/instructions/divide.lisp, books/projects/x86isa/machine/instructions/exchange.lisp, books/projects/x86isa/machine/instructions/fp/bitscan.lisp, books/projects/x86isa/machine/instructions/fp/convert.lisp, books/projects/x86isa/machine/instructions/fp/mxcsr.lisp, books/projects/x86isa/machine/instructions/jump-and-loop.lisp, books/projects/x86isa/machine/instructions/move.lisp, books/projects/x86isa/machine/instructions/multiply.lisp, books/projects/x86isa/machine/instructions/push-and-pop.lisp, books/projects/x86isa/machine/instructions/rotate-and-shift.lisp, books/projects/x86isa/machine/instructions/subroutine.lisp, books/projects/x86isa/machine/new-decode.lisp, books/projects/x86isa/portcullis/package.lsp, books/projects/x86isa/portcullis/sharp-dot-constants.lisp, books/projects/x86isa/top.lisp
WIP: new book to make operand addressing simpler in the future. The  eventual goal is to move towards a more structured and declarative style of instruction specification.
=> [x86isa] Very preliminary work on new instruction specification style

books/workshops/2017/README, books/workshops/2017/sumners/support/README, books/workshops/2017/sumners/support/bakery.lisp, books/workshops/2017/sumners/support/bounded-ords.lisp, books/workshops/2017/sumners/support/general-theory.lisp, books/workshops/2017/sumners/support/sets.lisp, books/workshops/2017/sumners/support/trans-theory.lisp
Submitting (finally) workshop support books for inclusion in repo.
=> Workshop 2017 support books

books/build/cert.pl, books/build/doc.lisp
See #749 for discussion. Sorry I took so long to do this.
=> Improve some comments in cert.pl (fixes #749)

books/workshops/2015/peng-greenstreet/support/config.lisp
Hi Yan,
Does this look okay to you?  Can you test such a change before I commit it?
Thanks,
David
=> For SMT, make python call more generic

books/projects/async/branch.lisp, books/projects/async/fifo/alt-branch.lisp, books/projects/async/fifo/alt-merge.lisp, books/projects/async/fifo/comp-v-or.lisp, books/projects/async/fifo/queue10-as-link.lisp, books/projects/async/fifo/queue2.lisp, books/projects/async/fifo/queue3.lisp, books/projects/async/fifo/queue4-as-link.lisp, books/projects/async/fifo/queue5-as-link.lisp, books/projects/async/fifo/queue8-as-link.lisp, books/projects/async/fifo/round-robin1.lisp, books/projects/async/fifo/round-robin2.lisp, books/projects/async/fifo/round-robin3.lisp, books/projects/async/fifo/wig-wag.lisp, books/projects/async/gcd/comp-gcd-cond.lisp, books/projects/async/gcd/comp-gcd.lisp, books/projects/async/gcd/gcd.lisp, books/projects/async/gcd/queue3-comp-gcd.lisp, books/projects/async/gcd/queue3-gcd.lisp, books/projects/async/merge.lisp
Speed up the proofs of the value and state lemmas for self-timed modules
=> Speed up the proofs of the value and state lemmas

books/projects/async/adders/add-sub.lisp, books/projects/async/adders/adder.lisp, books/projects/async/branch.lisp, books/projects/async/comparators/v-greater.lisp, books/projects/async/comparators/v-less.lisp, books/projects/async/fifo/alt-branch.lisp, books/projects/async/fifo/alt-merge.lisp, books/projects/async/fifo/comp-v-or.lisp, books/projects/async/fifo/queue10-as-link.lisp, books/projects/async/fifo/queue2.lisp, books/projects/async/fifo/queue3.lisp, books/projects/async/fifo/queue4-as-link.lisp, books/projects/async/fifo/queue5-as-link.lisp, books/projects/async/fifo/queue8-as-link.lisp, books/projects/async/fifo/round-robin1.lisp, books/projects/async/fifo/round-robin2.lisp, books/projects/async/fifo/round-robin3.lisp, books/projects/async/fifo/wig-wag.lisp, books/projects/async/gcd/comp-gcd-cond.lisp, books/projects/async/gcd/comp-gcd.lisp, books/projects/async/gcd/gcd-cond.lisp, books/projects/async/gcd/gcd.lisp, books/projects/async/gcd/queue3-comp-gcd.lisp, books/projects/async/gcd/queue3-gcd.lisp, books/projects/async/link-joint.lisp, books/projects/async/macros.lisp, books/projects/async/merge.lisp, books/projects/async/serial-adder/async-serial-adder.lisp, books/projects/async/store-n.lisp, books/projects/async/vector-module.lisp
Automating the async framework
=> Automating the async framework

books/projects/async/adders/add-sub.lisp, books/projects/async/adders/adder.lisp, books/projects/async/branch.lisp, books/projects/async/comparators/v-greater.lisp, books/projects/async/comparators/v-less.lisp, books/projects/async/f-functions.lisp, books/projects/async/fifo/alt-branch.lisp, books/projects/async/fifo/alt-merge.lisp, books/projects/async/fifo/comp-v-or.lisp, books/projects/async/fifo/queue10-as-link.lisp, books/projects/async/fifo/queue2.lisp, books/projects/async/fifo/queue3.lisp, books/projects/async/fifo/queue4-as-link.lisp, books/projects/async/fifo/queue5-as-link.lisp, books/projects/async/fifo/queue8-as-link.lisp, books/projects/async/fifo/round-robin1.lisp, books/projects/async/fifo/round-robin2.lisp, books/projects/async/fifo/round-robin3.lisp, books/projects/async/fifo/wig-wag.lisp, books/projects/async/gcd/comp-gcd-cond.lisp, books/projects/async/gcd/comp-gcd.lisp, books/projects/async/gcd/gcd.lisp, books/projects/async/gcd/queue3-comp-gcd.lisp, books/projects/async/gcd/queue3-gcd.lisp, books/projects/async/hard-spec.lisp, books/projects/async/link-joint.lisp, books/projects/async/merge.lisp, books/projects/async/serial-adder/async-serial-adder.lisp
Added the link module to the async framework
=> Added the link module to the async framework

books/projects/async/fifo/queue2.lisp, books/projects/async/flip-flop.lisp, books/projects/async/gcd/gcd-alg.lisp, books/projects/async/gcd/gcd.lisp, books/projects/async/gcd/queue3-comp-gcd.lisp, books/projects/async/link-joint.lisp, books/projects/async/vector-module.lisp
Added the flip-flop module to the ASYNC project
=> Added the flip-flop module to the ASYNC project

books/std/std-customization.lsp
Previously, EXPLAIN-FN assumed that the only way that a rule could
have failed to apply was that one of its hypotheses failed to be
relieved.  Perhaps that's because EXPLAIN-FN was originally only meant
to deal with rewrite rules, before I changed WHY and WHY-EXPLAIN to
handle other rule types in #754.  (However, even rewrite rules can
sometimes fail for other reasons, such as because of backchain
limits.)
This commit makes EXPLAIN-FN a bit more robust; now it checks if the
failure reason is of the correct form before trying to extract a
term (the term the unrelieved hypothesis rewrote to) from it.  This
also means it's now unnecessary to run :OK-IF (BRR@ :WONP) before
calling EXPLAIN-FN.
=> Fix crash in EXPLAIN-FN

books/projects/hexnet/example-network.lsp, books/projects/hexnet/helper-functions.lisp, books/projects/hexnet/hexnet-model.lisp
Model of a packet-switching network with a hexagonal layout, HEXNET in ACL2. This is an attempt to model the functionalities of the network and packets move through it.
=> Hexnet Model

books/centaur/bitops/rotate.lisp
The hypotheses about positivity of width probably can't be avoided since
they are also hypotheses for the theorems unsigned-byte-p-of-rotate-left
and unsigned-byte-p-of-rotate-right.
Thanks are owed to @kini for the idea.
=> Add theorems about rotate-right and rotate-left

books/kestrel/utilities/strings/chars-codes.lisp, books/projects/filesystems/block-listp.lisp, books/projects/filesystems/bounded-nat-listp.lisp, books/projects/filesystems/fat32.lisp, books/projects/filesystems/file-system-1.lisp, books/projects/filesystems/file-system-3.lisp, books/projects/filesystems/file-system-5.lisp, books/projects/filesystems/file-system-6.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/file-system-m1.lisp, books/projects/filesystems/file-system-m2.lisp, books/projects/filesystems/find-n-free-blocks.lisp, books/projects/filesystems/flatten-lemmas.lisp, books/projects/filesystems/generate-index-list.lisp, books/projects/filesystems/insert-text.lisp, books/projects/filesystems/set-indices.lisp
One of these commits touches the Kestrel books (making a rewrite rule more general) so it would be great if @acoglio or @ericsmithkestrel could review and merge.
=> Workshop related updates

books/std/io/combine.lisp
It's not often that we add lemmas with this kind of heavy use of the proof-builder to the community books. However, the need for these lemmas came up while I was working on my own books, and I was surprised that they didn't already exist. So, I hacked them together using the proof-builder, and I'm submitting this pull request to ask if there's interest in having them in this book - if there is, then I'd think it's worth the trouble to make them go through without proof-builder assistance. Also, I'm not currently using combine16s, combine32s, combine64s and combine64u, but I could imagine formulating versions of these lemmas for these functions, for the sake of completeness. So it would also be good to know if anyone would like to help with this additional task.
@jaredcdavis , as the …
=> Add some lemmas for combine16u and combine32u

books/system/to-do.txt
Per a request by @MattKaufmann .
=> Add a to-do note

books/projects/async/macros.lisp
Changed the names of the value and state lemmas for the DE primitives
=> Changed the names of the value and state lemmas for the DE primitives

books/projects/async/assoc-eq-value.lisp, books/projects/async/macros.lisp, books/workshops/2018/whats-new-books-talk/slides.tex
Updated slides for what's-new-books talk
=> Updated slides for what's-new-books talk

books/projects/async/de.lisp, books/projects/async/index.lisp, books/projects/async/package.lsp, books/projects/async/serial-adder/32-bit-serial-adder-old/store-n.lisp, books/projects/async/store-n.lisp, books/projects/async/utils.lisp
ASYNC: Improved the symbol-index library
=> ASYNC: Improved the symbol-index library

books/workshops/2018/README, books/workshops/2018/sumners/acl2-customization.lsp, books/workshops/2018/sumners/aignet-ipasir-off.lisp, books/workshops/2018/sumners/alu.v, books/workshops/2018/sumners/alu_in.vcd, books/workshops/2018/sumners/cert.acl2, books/workshops/2018/sumners/exa.lisp, books/workshops/2018/sumners/exbase.lisp, books/workshops/2018/sumners/exload.lisp, books/workshops/2018/sumners/exloop.lisp, books/workshops/2018/sumners/exsim.lisp, books/workshops/2018/sumners/extra.lisp, books/workshops/2018/sumners/extypes.lisp, books/workshops/2018/sumners/ipasir-tools-off.lisp, books/workshops/2018/sumners/nxtbl.lisp, books/workshops/2018/sumners/nxtypes.lisp, books/workshops/2018/sumners/package.lsp, books/workshops/2018/sumners/portcullis.acl2, books/workshops/2018/sumners/portcullis.lisp, books/workshops/2018/sumners/readme.lisp, books/workshops/2018/sumners/smq.v, books/workshops/2018/sumners/smq_in.vcd, books/workshops/2018/sumners/support.lisp, books/workshops/2018/sumners/svcnf.lisp, books/workshops/2018/sumners/toy.v, books/workshops/2018/sumners/toy_in.vcd, books/workshops/2018/sumners/vcd.lisp, books/workshops/2018/sumners/vcdtypes.lisp
Submitting supporting materials for ACL2 workshop 2018. Change to README and new files in new directory.
=> Submitting supporting materials for ACL2 workshop 2018

books/workshops/2018/sumners/readme.lisp
Fixing issue with readme.lisp in previous submission
=> Fixing issue with readme.lisp in previous submission

books/projects/async/adders/add-sub.lisp
ASYNC: Fixed an error in adders/add-sub.lisp
=> ASYNC: Fixed an error in adders/add-sub.lisp

books/projects/async/adders/add-sub.lisp, books/projects/async/adders/adder.lisp, books/projects/async/comparators/v-greater.lisp, books/projects/async/comparators/v-less.lisp, books/projects/async/serial-adder/32-bit-serial-adder-old/adder.lisp, books/projects/async/serial-adder/32-bit-serial-adder-old/store-n.lisp, books/projects/async/serial-adder/32-bit-serial-adder-old/vector-module.lisp, books/projects/async/store-n.lisp, books/projects/async/vector-macros.lisp, books/projects/async/vector-module.lisp
=> ASYNC: Cleanup

books/workshops/2018/gamboa-cowles/LICENSE, books/workshops/2018/gamboa-cowles/complex-continuity.lisp, books/workshops/2018/gamboa-cowles/complex-lemmas.lisp, books/workshops/2018/gamboa-cowles/complex-polynomials.lisp, books/workshops/2018/gamboa-cowles/de-moivre.lisp, books/workshops/2018/gamboa-cowles/norm2.lisp
These are the books for the Gamboa/Cowles paper to the 2018 workshop.
=> Added workshops books proving the fundamental theorem of algebra

books/coi/generalize/generalize.lisp, books/coi/util/acl2-customization.lsp, books/coi/util/type-alist.lisp
Updates to generalize, type-alist
=> coi updates

books/acl2s/base-theory.lisp
Updated the theorems in base-theory
=> pete: updated theorems in base-theory

books/acl2s/cgen/cgen-search.lisp, books/acl2s/cgen/testing-regression.lsp
Fixed a bug using code from Harsh and added some tests to the cgen regression
=> Updates to cgen

books/kestrel/utilities/strings/chars-codes.lisp, books/kestrel/utilities/strings/strings-codes.lisp, books/projects/filesystems/file-system-m2.lisp, books/std/typed-lists/unsigned-byte-listp.lisp
This touches the Kestrel books, so perhaps @acoglio could merge.
=> Names and docs

books/coi/util/defun.lisp, books/kestrel/utilities/strings/chars-codes.lisp, books/kestrel/utilities/strings/strings-codes.lisp
Kestrel books are touched, again, but also a fix is attempted for a bug which broke testing builds on leeroy.defthm.com.
=> Small changes and a bug fix

books/std/util/defval.lisp
Making a PR to give @jaredcdavis (original author) and others a chance to review.
See the message of the first commit (the second commit is minor).
=> A proposed improvement to std::defval.

books/projects/async/de.lisp, books/projects/async/serial-adder/32-bit-serial-adder-old/de.lisp
ASYNC: Removed redundant guards in the DE system
=> ASYNC: Removed redundant guards in the DE system

books/std/lists/nthcdr.lisp
As I've noted in the commit messages, the rules remain the same, so no one should be affected by this change one way or the other. Still, since this is a Kookamara book, perhaps @jaredcdavis would like to review.
=> Factor out encapsulated lemmas

books/std/util/defval-tests.lisp, books/std/util/defval.lisp, books/std/util/top.lisp
I'm making a PR since this affects STD, which several people may be using. If nobody objects, I'll merge this a few days from now.
=> [STD] Put DEFVAL test into separate file.

books/doc/relnotes.lisp, books/projects/curve25519/ecp.lisp, books/projects/quadratic-reciprocity/eisenstein.lisp, books/projects/quadratic-reciprocity/euclid.lisp, books/projects/quadratic-reciprocity/euler.lisp, books/projects/quadratic-reciprocity/fermat.lisp, books/projects/quadratic-reciprocity/gauss.lisp, books/projects/quadratic-reciprocity/mersenne.lisp, books/projects/quadratic-reciprocity/pratt.lisp, books/rtl/rel11/support/gl.lisp
Make some include-books local and adjust proofs accordingly.  See the item I added to the relnotes.  This change was approved in principle by Russinoff, but he might want to review the details.  I also deleted some trailing whitespace (my editor does this automatically).
=> Number theory

books/projects/smtlink/verified/computed-hints.lisp
Add some more documentation and fix the broken link issue
=> Add some more documentation and fix the broken link issue

books/projects/filesystems/README.md, books/projects/filesystems/fat32.lisp, books/projects/filesystems/hifat-syscalls.lisp, books/projects/filesystems/hifat.lisp, books/projects/filesystems/lofat.lisp, books/projects/filesystems/test-stuff.lisp, books/projects/filesystems/test/Makefile, books/projects/filesystems/test/compare-disks.lisp, books/projects/filesystems/test/cp-replicant.lisp, books/projects/filesystems/test/mv-replicant.lisp, books/projects/filesystems/test/wc-replicant.lisp
=> Update filesystem books

books/doc/relnotes.lisp, books/std/basic/bytep.lisp, books/std/basic/top.lisp, books/std/io/base.lisp
Making a PR since it affects Std. Please see commit message for details.
If there are no objections, I'll merge in a few days.
=> [std/io & std/basic] Factor out bytep.

books/make-event/proof-by-arith.lisp, books/projects/filesystems/README.md, books/projects/filesystems/lofat.lisp
I'm open to suggestions as far as the doc-string is concerned. I'm trying to convey that proof-by-arith works just as well for encapsulate or make-event as it does for defthm.
=> Doc update

books/doc/top-fast.lisp, books/doc/top.lisp
Somehow these were not in the manual before.
If there are no objections, I'll merge this in a few days.
=> Include additional IHS XDOC topics.

books/projects/filesystems/README.md, books/projects/filesystems/lofat.lisp
=> Update filesystem books and (slightly) xdoc

books/centaur/misc/sparsemap-impl.lisp, books/doc/relnotes.lisp, books/kestrel/utilities/alists/remove-assoc-theorems.lisp, books/std/alists/remove-assoc-equal.lisp, books/std/alists/top.lisp
I accidentally closed the PR with these commits, so I'm opening a new one.
=> Remove assoc equal

books/projects/smtlink/examples/basictypes.lisp, books/projects/smtlink/examples/examples.lisp, books/projects/smtlink/examples/inverter.lisp, books/projects/smtlink/examples/ringosc.lisp, books/projects/smtlink/examples/util.lisp, books/projects/smtlink/verified/Smtlink.lisp
Fixing missing parents and shadowed topic issues in Smtlink xdoc
=> Fixing missing parents and shadowed topic issues in Smtlink xdoc

books/centaur/fty/docgen.lisp, books/std/util/defaggregate.lisp, books/std/util/defval.lisp
Since this affects Std and FTY, I'm making a PR instead of pushing directly.
If nobody objects, I'll merge in a few days.
=> Evaluate :short and :long of various macros

books/kestrel/crypto/ecurve/short-weierstrass-validation.lisp, books/kestrel/crypto/ecurve/top.lisp
add short-weierstrass-validation.lisp and update top.lisp to load the recently added files
=> add short-weierstrass-validation

books/kestrel/crypto/ecdsa/deterministic-ecdsa-exposing-k-secp256k1.lisp, books/kestrel/crypto/ecdsa/deterministic-ecdsa-secp256k1-tests.lisp, books/kestrel/crypto/ecdsa/deterministic-ecdsa-secp256k1.lisp
[crypto] ECDSA Elliptic Curve Digital Signature Algorithm following RFC 6979, specialized for curve secp256k1
=> [crypto] ECDSA Elliptic Curve Digital Signature Algorithm

books/kestrel/bitcoin/bip39-tests.lisp, books/kestrel/bitcoin/tests-top.lisp
=> [bitcoin] bip39 tests

books/kestrel/ethereum/transactions-tests.lisp, books/kestrel/ethereum/transactions.lisp
Improve make-signed-transaction and its doc
=> Improve make-signed-transaction and its doc

books/kestrel/crypto/keccak/cert.acl2, books/kestrel/crypto/keccak/documentation.lisp, books/kestrel/crypto/keccak/package.lsp, books/kestrel/crypto/top.lisp
[crypto] documentation page on Keccak
=> [crypto] documentation page on Keccak

books/kestrel/hdwallet/acl2-customization.lsp, books/kestrel/hdwallet/cert.acl2, books/kestrel/hdwallet/package.lsp, books/kestrel/hdwallet/portcullis.acl2, books/kestrel/hdwallet/portcullis.lisp, books/kestrel/hdwallet/top.acl2, books/kestrel/hdwallet/top.lisp, books/kestrel/hdwallet/wallet-executable.acl2, books/kestrel/hdwallet/wallet-executable.lisp, books/kestrel/hdwallet/wallet-tests.acl2, books/kestrel/hdwallet/wallet-tests.lisp, books/kestrel/hdwallet/wallet.lisp, books/kestrel/top.lisp
Xdoc not hooked up yet due to conflicts.
=> [hdwallet] cryptocurrency wallet spec and executable spec

books/kestrel/bitcoin/bip39.lisp, books/kestrel/crypto/ecurve/secp256k1.lisp, books/kestrel/crypto/ecurve/short-weierstrass.lisp, books/kestrel/crypto/ecurve/top.lisp, books/kestrel/crypto/keccak/documentation.lisp
=> [crypto] elliptic curve xdoc

books/centaur/vl/mlib/json.lisp
Fixing json.lisp for VL to generate JSON output for SystemVerilog
This is just an update to mlib/json.lisp. Subsequent change will fix server options and output.
=> Fixing json.lisp for VL to generate JSON output for SystemVerilog

books/kestrel/crypto/ecdsa/deterministic-ecdsa-secp256k1.lisp, books/kestrel/crypto/interfaces/keccak-256.lisp, books/kestrel/crypto/interfaces/keccak-512.lisp, books/kestrel/crypto/keccak/documentation.lisp
[crypto] convert ecdsa to xdoc constructors and improve
=> [crypto] convert ecdsa to xdoc constructors and improve

books/kestrel/hdwallet/README.md, books/kestrel/hdwallet/build/acl2-on-ccl.df, books/kestrel/hdwallet/build/ccl.df, books/kestrel/hdwallet/build/hdwallet-on-acl2.df, books/kestrel/hdwallet/build/setup-hdwallet.acl2, books/kestrel/hdwallet/wallet, books/kestrel/hdwallet/wallet-tests.sh, books/kestrel/hdwallet/wallet.lisp
README for obtaining, running, and building Docker image containing wallet
=> README for obtaining, running, and building Docker image containing wallet

books/kestrel/crypto/attachments/hmac-sha-512.lisp, books/kestrel/crypto/attachments/pbkdf2-hmac-sha-512.lisp, books/kestrel/crypto/interfaces/hmac-sha-512.lisp, books/kestrel/crypto/interfaces/pbkdf2-hmac-sha-512.lisp, books/kestrel/crypto/interfaces/sha-256.lisp, books/kestrel/crypto/interfaces/sha-512.lisp, books/kestrel/crypto/kdf/doc.acl2, books/kestrel/crypto/kdf/doc.lisp, books/kestrel/crypto/kdf/top.lisp, books/kestrel/crypto/top.lisp, books/kestrel/ethereum/crypto.lisp, books/kestrel/hdwallet/README.md, books/kestrel/hdwallet/wallet.lisp
add kdf doc; misc doc improvements
=> add kdf doc; misc doc improvements

books/kestrel/crypto/ecdsa/secp256k1-interface.lisp, books/kestrel/crypto/ecurve/secp256k1-attachment.lisp, books/kestrel/crypto/ecurve/secp256k1-interface.lisp, books/kestrel/crypto/ecurve/secp256k1.lisp, books/kestrel/crypto/ecurve/short-weierstrass.lisp, books/kestrel/ethereum/crypto.lisp
add more cross-links between ecurve and ecdsa xdocs
=> add more cross-links between ecurve and ecdsa xdocs

books/kestrel/bitcoin/bip44.lisp, books/kestrel/crypto/ecurve/secp256k1.lisp, books/kestrel/crypto/keccak/documentation.lisp, books/kestrel/ethereum/transactions.lisp
add more external links to pages defining crypto
=> add more external links to pages defining crypto

books/kestrel/utilities/strings/chars-codes.lisp, books/kestrel/utilities/strings/strings-codes.lisp, books/projects/filesystems/hifat.lisp, books/projects/filesystems/lofat-to-string-inversion.lisp, books/projects/filesystems/lofat.lisp
These changes were discussed with @acoglio over email.
=> Move lemmas to Kestrel books

books/projects/filesystems/abstract-separate.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/lofat.lisp, books/projects/filesystems/update-data-region.lisp
Filesystem books are also updated.
Thanks, @acoglio and @MattKaufmann , for the suggestions on Slack.
=> Update some documentation

books/doc/relnotes.lisp, books/std/lists/top.lisp, books/std/lists/union.lisp
I'm making a PR, instead of pushing directly, since this affects Std. Unless there are objections, I'll merge in a few days.
Even though this theorem could be added to some existing file, I'm trying to make Std more modular in general.
=> [Std/lists] Add a file for theorems about UNION-EQUAL.

books/doc/relnotes.lisp, books/projects/filesystems/abstract-separate.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/ls-rm-example.lisp, books/std/lists/top.lisp, books/std/lists/union.lisp
I'm making this pull request against the Kestrel branch so I can base my commits off the recent changes to STD. This is in order to make sure there are no regression failures in case my books are affected.
=> Update docs and filesystem books

books/std/typed-lists/symbol-listp.lisp
Since this affects Std, I'm making a PR instead of pushing directly. I'll merge in a few days if there are no objections.
=> [Std/typed-lists] Add theorem SYMBOL-LISTP-OF-REMOVE1-EQUAL.

books/std/lists/remove1-equal.lisp
Since this affects Std/lists, I'm making a PR instead of pushing directly.
I'll merge in a few days if no objections are raised.
=> [Std/lists] Add a theorem about REMOVE1 and SUBSETP.

books/centaur/svl/bits-sbits.lisp, books/centaur/svl/svex-simplify.lisp, books/centaur/svl/type-defs.lisp, books/projects/rp-rewriter/aux-functions.lisp, books/projects/rp-rewriter/extract-formula.lisp, books/projects/rp-rewriter/proofs/extract-formula-lemmas.lisp
=> [svl] another bug in centaur/svl/svex-simplify.lisp is fixed.

books/std/lists/union.lisp
Since this affects Std/lists, I'm making a PR instead of pushing directly. I'll merge in a few days if there are no objections.
=> [Std/lists] Add theorem about UNION-EQUAL.

books/doc/relnotes.lisp, books/system/keyword-to-keyword-value-alistp.lisp, books/system/pseudo-good-worldp.lisp, books/system/pseudo-tests-and-calls-listp.lisp, books/system/pseudo-tests-and-callsp.lisp
I'm making a PR instead of pushing directly so that @MattKaufmann can briefly review first, since this affects his and J's file. The changes should be consistent with our previous agreement.
=> Factor some functions out of [books]/system/pseudo-good-worldp.lisp

books/std/typed-lists/string-listp.lisp
Since this affects Std, I'm making a PR instead of pushing directly. If there are no objections, I'll merge in a few days.
=> [Std/typed-lists] Add a theorem about STRING-LISP.

books/projects/filesystems/abstract-separate.lisp, books/projects/filesystems/fat32.lisp, books/projects/filesystems/file-system-lemmas.lisp, books/projects/filesystems/hifat-to-lofat-inversion.lisp, books/projects/filesystems/lofat-syscalls.lisp, books/projects/filesystems/lofat.lisp, books/projects/filesystems/update-data-region.lisp, books/projects/filesystems/wc-truncate-example.lisp, books/std/lists/prefixp.lisp
Some more lemmas are added to books/std/lists/prefixp.lisp. Filesystem books are updated, too.
=> Move some lemmas to STD

books/misc/check-acl2-exports.lisp
This is for the function subsequencep.
=> Add a defpointer and corresponding content

books/projects/rac/src/parser.y
Previously, the RAC parser did not check if RAC programs violate the placement restrictions on "return" statements described in Section 15.5 of David Russinoff's textbook, "Formal Verification of Floating-Point Hardware Design: A Mathematical Approach".  The parser would rather produce incorrect ACL2 programs if those restrictions were violated (without any warnings).
The parser has been updated so that syntax errors will be reported if RAC programs do not conform to those restrictions.
=> Imposed placement restrictions on RETURN statements in RAC programs

books/system/doc/README
File path updates in books/system/doc/README
=> missed doc update

books/workshops/2020/peng-greenstreet/Makefile, books/workshops/2020/peng-greenstreet/README.md, books/workshops/2020/peng-greenstreet/evaluator.lisp, books/workshops/2020/peng-greenstreet/judgement-fns.lisp, books/workshops/2020/peng-greenstreet/judgements.lisp, books/workshops/2020/peng-greenstreet/partial-eval.lisp, books/workshops/2020/peng-greenstreet/path-cond.lisp, books/workshops/2020/peng-greenstreet/returns-judgement.lisp, books/workshops/2020/peng-greenstreet/term-rectify.lisp, books/workshops/2020/peng-greenstreet/term-substitution.lisp, books/workshops/2020/peng-greenstreet/test-inference.lisp, books/workshops/2020/peng-greenstreet/top.lisp, books/workshops/2020/peng-greenstreet/type-inference-bottomup.lisp, books/workshops/2020/peng-greenstreet/type-inference-topdown.lisp, books/workshops/2020/peng-greenstreet/type-options.lisp, books/workshops/2020/peng-greenstreet/typed-term.lisp, books/workshops/2020/peng-greenstreet/utils/basics.lisp, books/workshops/2020/peng-greenstreet/utils/pseudo-lambda.lisp, books/workshops/2020/peng-greenstreet/utils/pseudo-term.lisp
Adding books for supporting submission "Type Inference Using Meta-extract for Smtlink and Beyond".
=> Adding books for ACL2 Workshop 2020.

books/GNUmakefile, books/workshops/2020/kwan-peng-greenstreet/LICENSE.MIT, books/workshops/2020/kwan-peng-greenstreet/abstract-cs.lisp, books/workshops/2020/kwan-peng-greenstreet/cert.acl2, doc/acl2-code-size.txt, doc/home-page.html
Creating /books/workshops/2020/kwan-peng-greenstreet containing supporting materials for "Cauchy-Schwarz for ACL2 Abstract Vector Spaces".
The books should be certifiable with cert.pl using the standard command described in the Call for Papers.
Please let me know if anything has gone amiss.
Stay healthy and safe!
Cheers,
Carl
=> ACL2 2020 Workshop supporting materials - Kwan, Peng, Greenstreet

books/GNUmakefile, books/workshops/2020/README, books/workshops/2020/gamboa-cowles-gamboa/LICENSE, books/workshops/2020/gamboa-cowles-gamboa/build.sh, books/workshops/2020/gamboa-cowles-gamboa/floor1-non-R.lisp, books/workshops/2020/gamboa-cowles-gamboa/norm-1C.lisp, books/workshops/2020/gamboa-cowles-gamboa/number-field.lisp, books/workshops/2020/gamboa-cowles-gamboa/polylist.lisp, books/workshops/2020/gamboa-cowles-gamboa/prior/raise-to.lisp
Supporting materials for the workshop. Note that number-field.lisp takes forever to certify, so it maybe shouldn't be in "make all".
=> Workshop 2020 supporting materials -- Quadratic Field Extensions

books/projects/arm/fdiv/prescale.lisp, books/projects/arm/fdiv/rounder.lisp
Fixed the failure in books/projects/arm/fdiv/
=> Fixed the failure in books/projects/arm/fdiv/

books/projects/rac/lisp/internal-fns-gen.lisp
Some update on books/projects/rac/lisp/internal-fns-gen.lisp
=> Some update on books/projects/rac/lisp/internal-fns-gen.lisp

books/projects/async/index.lisp, books/std/lists/append.lisp
Thanks are owed to @ericwhitmansmith for a Slack discussion in March
about the new name. I had to make a change to @myall86's books to make
the regression pass, so he might have something to say about this pull
request.
=> Generalise and rename an std/lists/append lemma

books/rtl/rel11/lib/add.lisp, books/rtl/rel11/lib/log.lisp, books/rtl/rel11/support/add.lisp, books/rtl/rel11/support/log.lisp
Added two bit manipulation lemmas to rtl/rel11
=> Added two bit manipulation lemmas to rtl/rel11

books/std/strings/digit-to-char.lisp, books/std/strings/top.lisp
Since this affects Std/strings, I'm making a PR instead of pushing directly.
I'll merge in a few days if there are no objections.
This follows the style of other Std files that provide theorems about built-in functions.
=> [Std/strings] Add a theorem about DIGIT-TO-CHAR.

books/projects/arm/fsqrt/algorithm.lisp, books/projects/rac/lisp/internal-fns-gen.lisp, books/rtl/rel11/lib/srt.lisp, books/rtl/rel11/support/srt.lisp
Fixed a bug in the INTERNAL-FNS-GEN tool suite
=> Fixed a bug in the INTERNAL-FNS-GEN tool suite

books/workshops/2020/hardin/README.md, books/workshops/2020/hardin/fact-leg64-preamble.lisp, books/workshops/2020/hardin/fact-leg64.lisp, books/workshops/2020/hardin/leg64-aux.lisp, books/workshops/2020/hardin/leg64.lisp, books/workshops/2020/hardin/sources/cert_pl_exclude, books/workshops/2020/hardin/sources/leg64.cpp, books/workshops/2020/hardin/sources/leg64.h
Added LEG64 ISA simulator to my workshop books at the request of ACL2 Workshop 2020 attendees.
=> Added LEG64 ISA Simulator

books/rtl/README, books/rtl/rel11/lib/round.lisp, books/rtl/rel11/support/old-round.lisp
Changed the name of a lemma in RTL from rdn-lower-bound to rdn-upper-bound
=> Fixed a typo in the RTL library

books/projects/filesystems/abs-syscalls.lisp, books/projects/filesystems/abstract-separate.lisp, books/projects/filesystems/fat32.lisp, books/projects/filesystems/hifat-syscalls.lisp, books/projects/filesystems/hifat.lisp, books/projects/filesystems/lofat-syscalls.lisp, books/projects/filesystems/lofat.lisp, books/projects/filesystems/partial-collapse.lisp, books/projects/filesystems/test-stuff.lisp, books/projects/filesystems/tricks/chain-leading-to-complete.lisp, books/projects/filesystems/wc-truncate-example.lisp, books/std/lists/sets.lisp
This PR also updates the filesystem books.
=> Add two lemmas to std/lists/sets

books/demos/mini-proveall-book.acl2, books/tools/run-script.lisp
add depends-on form referencing script file to run-script doc and to mini-proveall demo
=> add depends-on for script file

books/centaur/fty/fixtype.lisp
[Making a PR on purpose -- please don't merge until Sol reviews it.]
This was discussed with Sol Swords.
The documentation of DEFFIXTYPE mentions :EXECUTABLEP, but the implementation
uses :EXECP. The former seems preferable to the latter, so we want to replace
the latter with the former in the implementation.
As suggested by Sol, we do that in three steps:
1. We add :EXECUTABLEP without removing :EXECP; the default T, its conjoining
with EXECP, and the disjoining of its negation with (NOT EXECP), should ensure
no change of behavior in existing calls. The full regression passes.
2. We switch existing calls to use :EXECUTABLEP, whose treatment in the
implementation is symmetric to :EXECP, so again there should be no change in
behavior.
3. We remove :EXECP.
This commit does step #1.
=> [FTY] Add the :EXECUTABLEP option to DEFFIXTYPE.

books/centaur/svl/4vec-lemmas.lisp, books/centaur/svl/bits-sbits.lisp, books/centaur/svl/portcullis.acl2, books/centaur/svl/svl-flatten.lisp, books/projects/rp-rewriter/eval-functions.lisp, books/projects/rp-rewriter/lib/mult3/demo/adders_with_plus.sv, books/projects/rp-rewriter/lib/mult3/demo/demo-1.lisp, books/projects/rp-rewriter/lib/mult3/demo/demo-2.lisp, books/projects/rp-rewriter/lib/mult3/doc.lisp, books/projects/rp-rewriter/lib/mult3/svl-top.lisp, books/projects/rp-rewriter/meta-rule-macros.lisp, books/projects/rp-rewriter/portcullis.acl2, books/sorting/merge-sort-term-order.lisp
Also some small changes in the documentation.
=> Added a few lemmas to [svl] and [rp] packages

books/build/make_cert_help.pl
Disclaimer: I don't know perl.  Someone who does should look this over.
=> [cert.pl] Add option to suppress stack traces.

books/std/util/defrule.lisp
This pull request adds documentation for defrulel and defruledl.
=> [std] Add xdoc for defrulel and defruledl.

books/centaur/aignet/eval.lisp, books/centaur/aignet/obs-constprop.lisp, books/centaur/aignet/observability.lisp, books/centaur/fgl/aignet-pathcond-stobj.lisp, books/centaur/fgl/bvar-db.lisp, books/centaur/fgl/interp.lisp, books/centaur/fgl/stack.lisp, books/centaur/fty/fty-list.lisp, books/centaur/fty/tests/terms.lisp, books/centaur/meta/congruence.lisp, books/centaur/sv/mods/compile.lisp, books/centaur/sv/mods/lhs.lisp, books/centaur/sv/mods/moddb.lisp, books/centaur/sv/svex/unroll.lisp, books/centaur/sv/svtv/probe.lisp, books/centaur/svl/svex-eval-wog.lisp, books/centaur/vl/mlib/expr-tools.lisp, books/centaur/vl/mlib/stmt-tools.lisp, books/centaur/vl2014/mlib/stmt-tools.lisp, books/projects/filesystems/hifat.lisp
This seems like a good addition to FTY, considering the number of files individually proving this lemma for their FTY lists.
=> Add an FTY lemma about nth

books/centaur/aignet/aignet-logic.lisp, books/centaur/aignet/eval.lisp, books/centaur/fgl/symbolic-arithmetic.lisp, books/centaur/fty/fty-list.lisp, books/projects/filesystems/hifat.lisp
This is another theorem which books seem to be generating manually for their FTY lists.
=> Add a refinement theorem to FTY

books/std/util/defaggregate.lisp
Resubmit PR#1247 with just the one commit for defaggregate, which was already approved by acoglio and solswords.
=> add ":suppress-xdoc t" option to defaggregate

books/kestrel/number-theory/tonelli-shanks-proof.lisp, books/kestrel/number-theory/tonelli-shanks.lisp, books/kestrel/number-theory/top.lisp
1) Added interface functions to the Tonelli-Shanks modular square root algorithm.
2) Added xdoc code for the Tonelli-Shanks modular square root algorithm.
3) Added proof of correctness of the algorithm and xdoc to the proof.
4) Modified top.lisp to include tonelli-shanks-proof.lisp.
=> Tonelli-Shanks interface functions and proof of correctness

books/nonstd/arc-length/length-of-a-rectifiable-curve.lisp, books/nonstd/circles/circumference-of-a-circle.lisp
1) A Mechanized Proof of the Curve Length of A Rectifiable Curve.
2) Application of the length of a rectifiable curve to find the circumference of a circle.
=> A Mechanized Proof of the Curve Length of A Rectifiable Curve

books/kestrel/number-theory/defprime.lisp
=> add list items in xdoc for defprime

books/nonstd/circles/area-of-a-circle/README.md, books/nonstd/circles/area-of-a-circle/area-of-a-circle-1.lisp, books/nonstd/circles/area-of-a-circle/area-of-a-circle-2.lisp
This is an applicaion of integration by substitution in ACL2(r)(books/nonstd/integrals/u-substitution.lisp)
=> area of a circle - application of u-substitution.lisp

books/centaur/fty/fty-sugar.lisp
This avoids executing strip-cars every time a structure created by defprod is checked.  Profiling showed that the call to strip-cars was allocating the majority of the memory in a large proof that checked well-formedness of many (tens of millions) of small structures created with defprod.  This change also reduces the number of passes through the alist.  This change uses MBE and so effects execution only, not the logical definitions generated.
Feel free to use all, some or none of this implementation, to change the style as desired, etc.
=> [FTY] Reduce consing in recognizers for defprod, etc.

books/projects/apply/loop.lisp, books/system/apply/apply-prim-support.lisp, books/system/apply/apply-prim.lisp, books/system/apply/loop-scions.lisp
A few changes to speed up build of projects/apply/top (with permission from J Moore).
=> Reduce dependencies and speed up build for projects/apply/top

books/centaur/fgl/def-fgl-rewrite.lisp, books/centaur/gl/tutorial.lisp, books/centaur/glmc/glmc.lisp, books/centaur/sv/tutorial/boothpipe.lisp, books/centaur/vl/loader/preprocessor/defines.lisp, books/std/bitsets/sbitsets.lisp
I think these are all straightforward.
=> [centaur] Fix various xdoc issues.

books/demos/stobj-table-examples.lisp
Adding books/demos/stobj-table-examples.lisp .. this book has one small example and one extended example of using the new ACL2 stobj-tables feature
=> Adding books/demo/stobj-table-examples.lisp

books/nonstd/nsa/Banach-Tarski/README.md, books/nonstd/nsa/Banach-Tarski/banach-tarski-s2.lisp, books/nonstd/nsa/Banach-Tarski/countable-sets.lisp, books/nonstd/nsa/Banach-Tarski/hausdorff-paradox-1.lisp, books/nonstd/nsa/Banach-Tarski/hausdorff-paradox-2.lisp
1) Added John Cowles as one of the contributors to hausdorff-paradox-2.lisp.
2) countable-sets.lisp: Contains proof of the cartesian product of two countable sets is countable.
3) banach-tarski-s2.lisp: Contains proof of the Banach-Tarski theorem on S^2.
4) Updated README.
=> A formal proof of the Banach-Tarski theorem on S^2.

books/nonstd/circles/area-of-a-circle/area-of-a-circle-1.lisp, books/nonstd/circles/area-of-a-circle/area-of-a-circle-2.lisp, books/nonstd/integrals/u-substitution.lisp
Modified some definitions and names of the theorems.
=> corrections

books/nonstd/nsa/Banach-Tarski/README.md
updated README for the Banach-Tarski theorem.
=> updated README

books/kestrel/syntheto/examples/isomorphism.lisp, books/kestrel/syntheto/shallow/functions.lisp
Also minor tweak to make example work better
=> Fix bug found by Matt that could cause lisp error

bin/new-useless-runes-files.sh, books/.gitignore, books/build/cert.pl, books/build/cert_features.lsp, other-events.lisp, type-set-b.lisp
This contains all the changes discussed on slack.
I did a regression and interactively tested ACL2(r) as well and it turns off useless runes there.
There is another branch containing the doc.
=> Cert heed useless runes 2

books/workshops/2022/README, books/workshops/2022/stobj-tables/stobj-table-recognizer-issue.lisp
Adding stobj-tables paper supporting materials
=> Adding supporting materials for stobj-tables paper

books/workshops/2022/README
Updating README file for Mertcan's supporting materials
=> Updating README for Mertcan's supporting materials

books/workshops/2022/russinoff-calendar/calendar.cpp
Adding calendar.cpp to workshop books
=> Adding calendar.cpp file to workshop books

books/build/lib/Bookscan.pm
This change makes $debugging work.
=> Two calls to debug_print_event got errors when $debugging was set.

books/projects/rac/src/Makefile
Added that flag to support old g++ versions.
=> [RAC] Added the -std=c++11 flag to src/Makefile

books/kestrel/apt/parteval-tests.lisp, books/kestrel/apt/parteval.lisp
Add test case that would have caught the error
=> Fix handling of multiple fixed args.

books/kestrel/std/system/fresh-namep.lisp
Opening a new pull request with just the changes to `books/`, as per the discussion in https://github.com/acl2/acl2/pull/1404.
=> Lift fresh-namep-msg-weak and fresh-namep-listp-msg-weak into logic mode

books/quicklisp/top.lisp
As suggested in Issue #395.
Closes #395.
=> Add a sentence to Quicklisp documentation

books/kestrel/utilities/system/numbered-names.lisp
The `get-numbered-name-index-*` functions required minor modifications to prove the functions had the suggested return types.
=> Guard-verify some numbered-names utilities

books/misc/hons-help.lisp
Closes #319.
That Issue suggested to turn the (now obsolete) doc strings into XDOC. The file already had some XDOC. This commit completes the job, so to speak.
I'm leaving this PR pending just in case anybody objects. It can be merged later.
=> Turn doc strings into XDOC.

books/std/util/define.lisp
=> Slightly expand doc of `define`.

books/acl2s/utilities.lisp
We've found these proof builder macros useful when automatically generating proof-builder instructions.
Ping @pmanolios
=> [acl2s] Add some additional proof builder macros to acl2s/utilities

books/projects/vwsim/vwsim-doc.lisp
Updated the VWSIM local documentation build
=> Updated VWSIM doc

books/projects/vwsim/vwsim-doc.lisp
Checks if the canonical-pathname exists on the machine
=> Fixed VWSIM doc path

books/projects/arm/utils/aarch64-specs.lisp
Add aarch64 specs for fpdotadd, bfdot, and bfmmla.
=> Update AArch64 specifications

books/projects/arm/utils/bits-meta.lisp, books/projects/arm/utils/rtl-utils.lisp
Also adding some useful lemmas in rtl-utils.lisp
=> Meta rules for simplifying applications of the bits function

books/kestrel/apt/doc.lisp, books/kestrel/apt/lift-iso-doc.lisp, books/kestrel/apt/lift-iso-tests.lisp, books/kestrel/apt/lift-iso.lisp, books/kestrel/apt/propagate-iso-doc.lisp, books/kestrel/apt/propagate-iso.lisp
Speed up a few proofs and remove guard-debugs
=> Documentation for lift-iso and cleanup

books/acl2s/installation.lisp
Update the ACL2s install instructions XDOC topic(s).
=> [acl2s] Update ACL2s install instructions

books/interface/emacs/acl2-indent.el
Define some functions missing in Emacs 24 so it doesn't break. Works almost as well as in later versions.
=> Fix for Emacs 24. Minor adjustments.

books/centaur/gl/hyp-fix.lisp, books/tools/match-tree.lisp, books/xdoc/importance.lisp
These were found by the Linter.
=> Fix some format strings with missing args.

books/arithmetic/README
The list of contents was out of date.
=> Update arithmetic-1 README.

books/workshops/2023/community-books-acl2-2023.tex
Per Alessandro's email, I wrote short summaries of my workshop book and also @ankitku 's for the workshop 2023 slides.
=> wrote summaries of my book and ankit's

books/centaur/bitops/floor.lisp, books/centaur/bitops/merge.lisp, books/misc/callers-and-ancestors.lisp, books/projects/sat/lrat/incremental/clrat-parser.lisp, books/textbook/chap11/compress.lisp
This pull request strictly generalises a set of lemmas, still, I thought I'd put it up for review before merging.
=> Generalise lemmas

books/projects/pdf-parser/README.md
As per requested https://github.com/acl2/acl2/pull/1612#issuecomment-2248524271, I have added copyright info to the README.
=> Adding copyright and license

books/projects/arm/utils/aarch64-specs.lisp, books/projects/rac/lisp/alt-const-fns-gen.lisp, books/projects/rac/lisp/expand-reduce-cp.lisp
1. Change aarch64-post-comp function
2. Add basic debug capability in expand-reduce-cp
3. Bugfix in alt-const-fns-gen
=> Changes to arm rounding logic; debug capability in expand-reduce-cp

books/projects/include-doc.lisp, books/projects/leo/LICENSE, books/projects/leo/acl2-customization.lsp, books/projects/leo/cert.acl2, books/projects/leo/grammar.abnf, books/projects/leo/grammar.lisp, books/projects/leo/package.lsp, books/projects/leo/portcullis.acl2, books/projects/leo/portcullis.lisp, books/projects/leo/top.lisp
Add `leo` to projects directory.
Did books regression and xdoc check on linux and Mac M3.
=> [projects] add leo project

books/acl2s/installation.lisp
Updates to the installation instructions. Updates include:
1. Switch to the newest version of Eclipse
2. Update video installation instructions
3. Update homebrew plugin links to newest release
=> Update installation.lisp to reflect dependency updates

books/projects/x86isa/machine/tty-raw.lsp
Warren observed very poor performance booting Linux on the x86isa model
when running under CCL on Mac OS with the tty-raw.lsp loaded. It seems
`read-char-no-hang,` which was previously called once per executed
instruction, is very slow on Mac OS.
To resolve this, we read the socket on a separate thread, which blocks
waiting for data. This thread places the read bytes in a queue (which is
a list for simplicity, but of course has the expected performance
implications) which can be quickly read from the main thread.
Thanks to Warren for reporting this issue.
=> Move reading from socket in tty-raw to separate thread

books/xdoc/fancy/index-seo.php
The SEO friendly version of xdoc put the xkey in the path component of
the url (i.e. URLs would look like `index-seo.php/ACL2___TOP`). While
this is more idiomatic than having them be a query parameter, this
caused mod_evasive to recognize each page as separate and thus ratelimit
them separately instead of together.
This moves the xkey to an `xkey` query parameter and updates the URLs
accordingly.
=> Use query params for xkey in SEO friendly xdoc

books/interface/emacs/acl2-indent.el
Previously wasn't treating foo::|fie| as a single atom.
Also make C-M-q (indent-sexp) use indent-region so behaves consistently. Mainly affects comment indenting.
=> Fix indenting of function expressions like foo::|fie|

books/projects/filesystems/abs-separate.lisp, books/projects/filesystems/abs-syscalls.lisp, books/projects/filesystems/absfat/partial-collapse.lisp, books/projects/filesystems/absfat/path-clear.lisp, books/projects/filesystems/eqfat.lisp, books/projects/filesystems/hifat-syscalls.lisp, books/projects/filesystems/l-models/file-system-5.lisp, books/projects/filesystems/lofat-syscalls.lisp, books/projects/filesystems/lofat/lofat-place-file.lisp, books/projects/filesystems/lofat/lofat-pwrite.lisp, books/projects/filesystems/lofat/update-data-region.lisp, books/projects/filesystems/oracle.lisp, books/projects/filesystems/tar-stuff.lisp, books/projects/filesystems/test/tar-writer.lisp
Remove occurrences of :guard-debug t (might speed up some proofs).
=> Filesystems :guard-debug

books/projects/x86isa/machine/linear-memory.lisp
These were commented out due to slowness and had bit-rotted a bit.  I got them working again (except one rule that seems no longer true and has no analogue for similar functions).  I also sped up the proofs.  Now rml512 and wml512 each take about 70 seconds, so I think it's worth uncommenting them.  Further speedups may be possible, especially once PR#1705 is in.
=> [X86ISA] Restore and update rml512 and wml512.

books/projects/x86isa/machine/linear-memory.lisp
=> [X86ISA] Speed up some proofs.

books/quicklisp/top.lisp
This adds an XDOC page for `osicat` which describes the observed build failures, the remedy, and a deeper explanation of the cause.
Thanks to @bendyarm for doing the original debugging of this issue. More detail of the issue can be found in his Zulip post: https://acl2.zulip.kestrel.institute/#narrow/stream/25-continuous-integration-leeroy-jenkins/topic/Osicat.20fails/near/24762.
=> Add XDOC documentation of `osicat` build failures

books/ihs/basic-definitions.lisp
This is an `n`-ary version of `logapp`.
=> [IHS] Add `logappn`.

books/kestrel/axe/x86/tests/ndsu/add-AF.c, books/kestrel/axe/x86/tests/ndsu/add-PF=0.c, books/kestrel/axe/x86/tests/ndsu/add-PF=1.c, books/kestrel/axe/x86/tests/ndsu/add-SF.c, books/kestrel/axe/x86/tests/ndsu/add-ZF.c, books/kestrel/axe/x86/tests/ndsu/and-CF.c, books/kestrel/axe/x86/tests/ndsu/and-SF.c, books/kestrel/axe/x86/tests/ndsu/and-ZF.c, books/kestrel/axe/x86/tests/ndsu/or-CF.c, books/kestrel/axe/x86/tests/ndsu/or-SF.c, books/kestrel/axe/x86/tests/ndsu/or-ZF.c
Properties related to flag updates for x86 "add", "and", and "or" instructions.
=> Flag Properties: x86 AL Instructions

books/doc/practices.lisp
The current `best-practices` is a small draft topic. This rewrites the topic from scratch (keeping the subtopics). The content is largely a style guide and aims for widely agreed upon conventions.
If anyone objects to any particular point, I'd be happy to discuss removing or qualifying it. Again, this guide is intended to apply to the community books in general and so should get broad buy-in from the community.
Likewise, I'm happy to hear any suggested additions.
=> [doc] Rewrite best-practices

books/build/doc.lisp, books/doc/more-topics.lisp, books/doc/publications.lisp
See commit messages for rationale.
=> Doc improvements

books/centaur/fty/database.lisp
The form of these definitions is the one generated by `deflist`.
=> [FTY] Add some list types for FTY aggregates.

books/kestrel/c/syntax/disambiguator.lisp, books/kestrel/c/syntax/tests/validator.lisp, books/kestrel/c/syntax/validator.lisp
This makes the change to both the disambiguator and the validator.
=> [C$] Add identifier to scope before processing initializer
